app/controllers/about_controller.rb
app/controllers/application_controller.rb
app/controllers/concerns/security_handling.rb
app/views/about/contact.en.html.erb
app/views/about/cookies.en.html.erb
app/views/about/index.en.html.erb
app/views/about/privacy.en.html.erb
app/views/about/terms_and_conditions.en.html.erb
app/views/layouts/_footer_links.html.erb
config/locales/en.yml
config/routes.rb
spec/controllers/about_controller_spec.rb

This adds in working pages for the footer links.

Footer pages

---

app/attributes/yes_no.rb
app/controllers/steps/caution/under_age_controller.rb
app/forms/concerns/single_question_form.rb
app/forms/steps/caution/under_age_form.rb
app/services/caution_decision_tree.rb
app/value_objects/generic_yes_no.rb
app/views/steps/caution/under_age/edit.html.erb
config/locales/en.yml
config/routes.rb
db/migrate/20190307102108_add_under_age_to_disclosure_check.rb
db/schema.rb
spec/attributes/yes_no_spec.rb
spec/controllers/steps/caution/under_age_controller_spec.rb
spec/forms/steps/caution/under_age_form_spec.rb
spec/services/caution_decision_tree_spec.rb
spec/support/form_validation_shared_examples.rb
spec/support/matchers/validation_helpers.rb
spec/value_objects/generic_yes_no_spec.rb

- question asking How old were you when you got the caution?
- under_age field to disclosure-check table.
- the SingleQuestionForm from C100 application 
-  yes-no question form shared specs from C100

Add under age question

---

app/controllers/steps/caution/caution_type_controller.rb
app/forms/steps/caution/caution_type_form.rb
app/services/caution_decision_tree.rb
app/value_objects/caution_type.rb
app/views/steps/caution/caution_type/edit.html.erb
config/locales/en.yml
config/routes.rb
db/migrate/20190307150657_add_caution_type_to_disclosure_check.rb
db/schema.rb
spec/controllers/steps/caution/caution_type_controller_spec.rb
spec/forms/steps/caution/caution_type_form_spec.rb
spec/services/caution_decision_tree_spec.rb
spec/value_objects/caution_type_spec.rb

[Link to story](https://www.pivotaltracker.com/n/projects/2311302/stories/164006798)
- question asking What type of caution did you get
- question_type field to disclosure-check table.
- display different answer based on under age question

Add  what type of caution did you get step

---

app/controllers/steps/caution/conditional_end_date_controller.rb
app/forms/steps/caution/caution_type_form.rb
app/forms/steps/caution/conditional_end_date_form.rb
app/services/caution_decision_tree.rb
app/value_objects/caution_type.rb
app/views/steps/caution/conditional_end_date/edit.html.erb
config/locales/en.yml
config/routes.rb
db/migrate/20190308135300_add_caution_conditional_end_date_to_disclosure_check.rb
db/schema.rb
spec/controllers/steps/caution/conditional_end_date_controller_spec.rb
spec/forms/steps/caution/conditional_end_date_form_spec.rb
spec/services/caution_decision_tree_spec.rb
spec/value_objects/caution_type_spec.rb

[Link to ticket](https://www.pivotaltracker.com/n/projects/2311302/stories/164006813)
This adds in the condition end date step for the cautions path.

Condition end date step

---

app/controllers/steps/conviction/exit_controller.rb
app/controllers/steps/conviction_step_controller.rb
app/services/check_decision_tree.rb
app/services/conviction_decision_tree.rb
app/value_objects/caution_type.rb
app/views/steps/conviction/exit/show.en.html.erb
config/routes.rb
spec/controllers/steps/conviction/exit_controller_spec.rb
spec/models/disclosure_check_spec.rb
spec/services/check_decision_tree_spec.rb
spec/services/conviction_decision_tree_spec.rb
spec/services/expiry_date_calculator_spec.rb

[Link to the story](https://www.pivotaltracker.com/n/projects/2311302/stories/164490634)
- add exit page for conviction path
- add conviction Decision tree
- remove any factory bot from persisting

add exit page

---

README.md
app/views/home/index.en.html.erb
config/locales/en.yml

[Link to story](https://www.pivotaltracker.com/n/projects/2311302/stories/163976122)
Update start page copy to the following based on [prototype](https://ex-offenders.glitch.me/start.html?)

update start page copy

---

app/controllers/steps/caution/condition_complied_controller.rb
app/forms/steps/caution/condition_complied_form.rb
app/services/caution_decision_tree.rb
app/value_objects/caution_type.rb
app/views/steps/caution/condition_complied/edit.html.erb
config/locales/en.yml
config/routes.rb
db/migrate/20190312154353_add_caution_condition_complied_to_disclosure.rb
db/schema.rb
spec/controllers/steps/caution/condition_complied_controller_spec.rb
spec/forms/steps/caution/condition_complied_form_spec.rb
spec/services/caution_decision_tree_spec.rb

This adds in the question for if you have complied with the conditions of your caution.
[
Link to story](https://www.pivotaltracker.com/n/projects/2311302/stories/164006850)

Add condition complied step

---

app/services/caution_decision_tree.rb
app/services/expiry_date_calculator.rb
spec/services/caution_decision_tree_spec.rb
spec/services/expiry_date_calculator_spec.rb

On selecting Yes to `Did you stick to the conditions of the caution?` proceed to caution results page
On selecting No to `Did you stick to the conditions of the caution?` stay on the same page.  This just a holding point till we get feedback from design.

complete caution with conditional journey

---

app/controllers/application_controller.rb
app/controllers/steps/conviction_step_controller.rb
app/forms/base_form.rb
app/forms/concerns/single_question_form.rb
app/forms/form_attribute_methods.rb
lib/govuk_components/error_helpers.rb
lib/govuk_components/form_builder.rb
spec/fixtures/files/radio_button_fieldset_legend_options.html
spec/forms/base_form_spec.rb
spec/lib/govuk_components/form_builder_spec.rb

[Link to ticket](https://www.pivotaltracker.com/n/projects/2311302/stories/164299483)
Get 100% test coverage.
- add spec
- add nocov comment for methods which we will use at a later date

100% test coverage

---

app/views/steps/conviction/exit/show.en.html.erb
features/caution.feature
features/conviction.feature
features/step_definitions/common.rb
features/support/env.rb
lib/tasks/all_tests.rake
lib/tasks/cucumber.rake

Prepare cucumber for expanding the scenarios.

Setup cucumber tests

---

.circleci/config.yml
.rubocop.yml

[Link to story](https://www.pivotaltracker.com/n/projects/2311302/stories/163977721)

add circleci config

---

Dockerfile

Some assets (fonts and images) were not found as they were using a digest after the precompile, butthere are some hardcoded references in the `govuk-frontend` files that will not be able to use the rails digest mechanism.
In order to fix this problem without having to modify the `govuk-frontend` files to embed rails code (like `asset_path()`) we copy over the non-digested files along with the digested ones.
Also removed the ENV variable `SECRET_KEY_BASE` as Rails 5 uses a different mechanism and we don't need it anymore.

Fix missing assets

---

.circleci/config.yml

Update circleci config with deploy_staging workflow

add deploy_staging workflow to circleci config

---

app/controllers/steps/caution/condition_exit_controller.rb
app/services/caution_decision_tree.rb
app/views/steps/caution/condition_exit/show.en.html.erb
config/routes.rb
spec/controllers/steps/caution/condition_exit_controller_spec.rb
spec/services/caution_decision_tree_spec.rb

[Link to ticket ](https://www.pivotaltracker.com/n/projects/2311302/stories/164776328)
On selecting NO for the following question `Did you stick to the conditions of the caution?` display caution condition exit page

Add condition exit page

---

app/controllers/bare_application_controller.rb
app/controllers/status_controller.rb
app/services/disclosure_checker_app/status.rb
config/routes.rb
spec/controllers/status_controller_spec.rb
spec/services/disclosure_checker_app/status_spec.rb

[Link to Story](https://www.pivotaltracker.com/n/projects/2311302/stories/164490716)
- copy Ping Endpoint from C100
- copy health check from C100

Add ping endpoint

---

app/controllers/application_controller.rb
app/controllers/home_controller.rb
app/controllers/step_controller.rb
app/controllers/warning_controller.rb
app/views/warning/reset_session.html.erb
config/locales/en.yml
config/routes.rb
spec/controllers/home_controller_spec.rb

[Link to story](https://www.pivotaltracker.com/n/projects/2311302/stories/164768529)
The following has been completed in this PR:
- Mechanism to warn a user before resetting the session
- Give user the choose to continue with the current session or start a new one

Add a mechanism to warn users before reseting a session

---

features/caution.feature

This relates to ticket on Pivotal Tracker.
Paths to write:

Add happy paths to cucumber tests

---

app/controllers/steps/conviction/known_conviction_date_controller.rb
app/forms/steps/conviction/known_conviction_date_form.rb
app/services/check_decision_tree.rb
app/services/conviction_decision_tree.rb
app/views/steps/conviction/known_conviction_date/edit.html.erb
config/locales/en/conviction.yml
config/locales/en/errors.yml
config/locales/en/helpers.yml
config/routes.rb
db/migrate/20190401140247_add_known_conviction_date_to_disclosure_check.rb
db/schema.rb
features/conviction.feature
lib/generators/step/templates/edit/edit.html.erb
spec/controllers/steps/conviction/known_conviction_date_controller_spec.rb
spec/forms/steps/conviction/known_conviction_date_form_spec.rb
spec/services/check_decision_tree_spec.rb
spec/services/conviction_decision_tree_spec.rb

[Link to story](https://www.pivotaltracker.com/n/projects/2311302)
Add the first step on the conviction journey.

Add Step: Do you know the date you were convicted?

---

app/controllers/steps/conviction/under_age_conviction_controller.rb
app/forms/steps/conviction/under_age_conviction_form.rb
app/services/conviction_decision_tree.rb
app/views/steps/conviction/under_age_conviction/edit.html.erb
config/locales/en/conviction.yml
config/locales/en/errors.yml
config/locales/en/helpers.yml
config/routes.rb
db/migrate/20190402094014_add_under_age_conviction_to_disclosure_check.rb
db/schema.rb
lib/generators/step/templates/date/edit.html.erb
spec/controllers/steps/conviction/under_age_conviction_controller_spec.rb
spec/forms/steps/conviction/under_age_conviction_form_spec.rb
spec/services/conviction_decision_tree_spec.rb

[Link to story](https://www.pivotaltracker.com/n/projects/2311302/stories/165022959)
Add step: How old were you when you got convicted?

Add step: How old were you when you got convicted?

---

app/controllers/steps/conviction/conviction_date_controller.rb
app/forms/steps/conviction/conviction_date_form.rb
app/services/conviction_decision_tree.rb
app/views/steps/conviction/conviction_date/edit.html.erb
config/locales/en/conviction.yml
config/locales/en/errors.yml
config/locales/en/helpers.yml
config/routes.rb
db/migrate/20190402104426_add_conviction_date_to_disclosure_checkt.rb
db/schema.rb
spec/controllers/steps/conviction/conviction_date_controller_spec.rb
spec/forms/steps/conviction/conviction_date_form_spec.rb
spec/services/conviction_decision_tree_spec.rb

[Link to story](https://www.pivotaltracker.com/n/projects/2311302/stories/165022921)
Add step: When did you get convicted?

Add step When did you get convicted?

---

app/controllers/steps/conviction/community_order_controller.rb
app/forms/steps/conviction/community_order_form.rb
app/services/base_decision_tree.rb
app/services/conviction_decision_tree.rb
app/value_objects/community_order.rb
app/views/steps/conviction/community_order/edit.html.erb
config/locales/en/conviction.yml
config/locales/en/helpers.yml
config/routes.rb
db/migrate/20190411094219_add_community_order_to_disclosure_check.rb
db/schema.rb
spec/controllers/steps/conviction/community_order_controller_spec.rb
spec/forms/steps/conviction/community_order_form_spec.rb
spec/services/conviction_decision_tree_spec.rb

[Link to Story](https://www.pivotaltracker.com/n/projects/2311302/stories/165272589)
Add Step:  What was your community order?

Add Step: Which type of conviction were you given?

---

app/controllers/steps/conviction/custodial_sentence_controller.rb
app/forms/steps/conviction/custodial_sentence_form.rb
app/services/conviction_decision_tree.rb
app/value_objects/custodial_sentence.rb
app/views/steps/conviction/custodial_sentence/edit.html.erb
config/locales/en/conviction.yml
config/locales/en/helpers.yml
config/routes.rb
db/migrate/20190411132611_add_custodial_sentence_to_disclosure_check.rb
db/schema.rb
spec/controllers/steps/conviction/custodial_sentence_controller_spec.rb
spec/forms/steps/conviction/custodial_sentence_form_spec.rb
spec/services/conviction_decision_tree_spec.rb

[Link to story](https://www.pivotaltracker.com/n/projects/2311302/stories/165273524)
Add Step: What was your custodial sentence?

Add Step: What was your custodial sentence?

---

app/controllers/steps/conviction/discharge_controller.rb
app/forms/steps/conviction/discharge_form.rb
app/services/conviction_decision_tree.rb
app/value_objects/discharge.rb
app/views/steps/conviction/discharge/edit.html.erb
config/locales/en/conviction.yml
config/locales/en/helpers.yml
config/routes.rb
db/migrate/20190411140312_add_discharge_to_disclosure_check.rb
db/schema.rb
spec/controllers/steps/conviction/discharge_controller_spec.rb
spec/forms/steps/conviction/discharge_form_spec.rb
spec/services/conviction_decision_tree_spec.rb

[Link to story](https://www.pivotaltracker.com/n/projects/2311302/stories/165273607)
Add step:  Which discharge were you given?

Add step: Which discharge were you given?

---

app/controllers/steps/conviction/financial_controller.rb
app/forms/steps/conviction/financial_form.rb
app/services/conviction_decision_tree.rb
app/value_objects/financial.rb
app/views/steps/conviction/financial/edit.html.erb
config/locales/en/conviction.yml
config/locales/en/helpers.yml
config/routes.rb
db/migrate/20190412093815_add_financial_to_disclosure_check.rb
db/schema.rb
spec/controllers/steps/conviction/financial_controller_spec.rb
spec/forms/steps/conviction/financial_form_spec.rb
spec/services/conviction_decision_tree_spec.rb

[Link to story](https://www.pivotaltracker.com/n/projects/2311302/stories/165273638)
Add Step: What were you ordered to pay?

Add Step: What were you ordered to pay?

---

app/controllers/steps/conviction/motoring_controller.rb
app/forms/steps/conviction/motoring_form.rb
app/services/conviction_decision_tree.rb
app/value_objects/motoring.rb
app/views/steps/conviction/motoring/edit.html.erb
config/locales/en/conviction.yml
config/locales/en/helpers.yml
config/routes.rb
db/migrate/20190412142931_add_motoring_to_disclosure_check.rb
db/schema.rb
spec/controllers/steps/conviction/motoring_controller_spec.rb
spec/forms/steps/conviction/motoring_form_spec.rb
spec/services/conviction_decision_tree_spec.rb

[Link to story](https://www.pivotaltracker.com/n/projects/2311302/stories/165273711)
Add Step: What was your motoring conviction?

ADD STEP: What was your motoring conviction?

---

app/controllers/steps/conviction/military_controller.rb
app/forms/steps/conviction/military_form.rb
app/services/conviction_decision_tree.rb
app/value_objects/military.rb
app/views/steps/conviction/military/edit.html.erb
config/locales/en/conviction.yml
config/locales/en/helpers.yml
config/routes.rb
db/migrate/20190412140355_add_military_to_disclosure_check.rb
db/schema.rb
spec/controllers/steps/conviction/military_controller_spec.rb
spec/forms/steps/conviction/military_form_spec.rb
spec/services/conviction_decision_tree_spec.rb

[Link to story](https://www.pivotaltracker.com/n/projects/2311302/stories/165273672)
Add Step: What was your military conviction?

Add Step: What was your military conviction?

---

app/controllers/steps/conviction/rehabilitation_prevention_order_controller.rb
app/forms/steps/conviction/rehabilitation_prevention_order_form.rb
app/services/conviction_decision_tree.rb
app/value_objects/rehabilitation_prevention_order.rb
app/views/steps/conviction/rehabilitation_prevention_order/edit.html.erb
config/locales/en/conviction.yml
config/locales/en/helpers.yml
config/routes.rb
db/migrate/20190415101028_add_rehabilitation_prevention_order_to_disclosure_check.rb
db/schema.rb
spec/controllers/steps/conviction/rehabilitation_prevention_order_controller_spec.rb
spec/forms/steps/conviction/rehabilitation_prevention_order_form_spec.rb
spec/services/conviction_decision_tree_spec.rb

[Link to story](https://www.pivotaltracker.com/n/projects/2311302/stories/165273738)
Add Step: Which order were you given?

Add Step: Which order were you given?

---

app/controllers/steps/conviction/conviction_end_date_controller.rb
app/forms/steps/conviction/conviction_end_date_form.rb
app/services/base_decision_tree.rb
app/services/conviction_decision_tree.rb
app/value_objects/conviction_type.rb
app/views/steps/conviction/conviction_end_date/edit.html.erb
config/locales/en/conviction.yml
config/locales/en/errors.yml
config/locales/en/helpers.yml
config/routes.rb
db/migrate/20190416080132_add_conviction_end_date_to_disclosure_check.rb
db/schema.rb
spec/controllers/steps/conviction/conviction_end_date_controller_spec.rb
spec/forms/steps/conviction/conviction_end_date_form_spec.rb
spec/forms/steps/conviction/conviction_type_form_spec.rb
spec/services/conviction_decision_tree_spec.rb

[Link to story](https://www.pivotaltracker.com/n/projects/2311302/stories/165375414)
Add Step: When did the conviction end?

Add Step: When did the conviction end?

---

app/helpers/application_helper.rb
app/views/layouts/_analytics.html.erb
app/views/layouts/_tag_manager.html.erb
app/views/layouts/_tag_manager_no_script.html.erb
app/views/layouts/application.html.erb
spec/helpers/application_helper_spec.rb

[Link to story](https://www.pivotaltracker.com/n/projects/2311302/stories/163976682)
Replace google analytics code with google tag manager.

Replace google analytics code with google tag manager

---

app/controllers/steps/conviction/conviction_length_controller.rb
app/forms/steps/conviction/conviction_length_form.rb
app/services/conviction_decision_tree.rb
app/value_objects/conviction_length_type.rb
app/views/steps/conviction/conviction_length/edit.html.erb
config/locales/en/conviction.yml
config/locales/en/errors.yml
config/locales/en/helpers.yml
config/routes.rb
db/migrate/20190610093304_add_conviction_length_to_disclosure_check.rb
db/schema.rb
spec/controllers/steps/conviction/conviction_length_controller_spec.rb
spec/forms/steps/conviction/conviction_length_form_spec.rb
spec/services/conviction_decision_tree_spec.rb

Basic step length of conviction step without any styling.  The styling will be in the next PR

Add Step: Was the length of conviction given in weeks or months?

---

app/presenters/caution_result_presenter.rb
app/presenters/conviction_result_presenter.rb
app/presenters/question_answer_row.rb
app/presenters/results_presenter.rb
app/services/conviction_expiry_calculator.rb
app/views/steps/check/results/_caution.en.html.erb
app/views/steps/check/results/_conviction.en.html.erb
app/views/steps/check/results/shared/_row.html.erb
app/views/steps/check/results/show.en.html.erb
config/locales/en/caution.yml
config/locales/en/results.yml
spec/factories/disclosure_check.rb
spec/presenters/caution_result_presenter_spec.rb
spec/presenters/conviction_result_presenter_spec.rb
spec/presenters/question_answer_row_spec.rb
spec/services/conviction_expiry_calculator_spec.rb

The attributes to show are still a bit WIP but we need to show something for now.
In order to do this, a bit of refactor had to be done in the struct `QuestionAnswerRow`, which has been now converted to a class.

Implement convictions summary

---

app/controllers/steps/conviction/conviction_length_controller.rb
app/controllers/steps/conviction/conviction_length_type_controller.rb
app/forms/steps/conviction/conviction_length_form.rb
app/forms/steps/conviction/conviction_length_type_form.rb
app/services/conviction_decision_tree.rb
app/views/steps/conviction/conviction_length_type/edit.html.erb
config/locales/en/conviction.yml
config/locales/en/errors.yml
config/locales/en/helpers.yml
config/routes.rb
spec/controllers/steps/conviction/conviction_length_type_controller_spec.rb
spec/forms/steps/conviction/conviction_length_form_spec.rb
spec/forms/steps/conviction/conviction_length_type_form_spec.rb
spec/services/conviction_decision_tree_spec.rb

Separate conviction length and conviction length type into two separate questions.

Add Step: Enter length of conviction given in weeks or months?

---

app/services/caution_decision_tree.rb
app/views/steps/caution/caution_type/edit.html.erb
app/views/steps/caution/condition_complied/edit.html.erb
app/views/steps/caution/conditional_end_date/edit.html.erb
app/views/steps/caution/known_date/edit.html.erb
app/views/steps/check/kind/edit.html.erb
config/locales/en/caution.yml
config/locales/en/helpers.yml
features/caution.feature
features/conviction.feature
lib/govuk_components/form_builder.rb
spec/fixtures/files/radio_button_fieldset.html
spec/fixtures/files/radio_button_fieldset_error.html
spec/fixtures/files/radio_button_fieldset_legend_options.html
spec/services/caution_decision_tree_spec.rb

Update caution path copy to match [prototype copy](https://moj-disclosure-checker.herokuapp.com/v3)

Update caution path copy

---

app/forms/steps/conviction/conviction_type_form.rb
app/value_objects/conviction_length_type.rb
app/value_objects/conviction_type.rb
app/views/steps/conviction/conviction_length_type/edit.html.erb
app/views/steps/conviction/conviction_type/edit.html.erb
app/views/steps/conviction/known_date/edit.html.erb
config/locales/en/helpers.yml
config/locales/en/results.yml
spec/forms/steps/conviction/conviction_length_type_form_spec.rb
spec/forms/steps/conviction/conviction_subtype_form_spec.rb
spec/forms/steps/conviction/conviction_type_form_spec.rb
spec/value_objects/conviction_type_spec.rb

Update conviction path copy to match prototype

Update conviction path copy

---

app/controllers/steps/conviction/compensation_paid_controller.rb
app/forms/steps/conviction/compensation_paid_form.rb
app/views/steps/conviction/compensation_paid/edit.html.erb
config/locales/en/conviction.yml
config/locales/en/errors.yml
config/locales/en/helpers.yml
config/routes.rb
db/migrate/20190618100314_add_compensation_paid_to_disclosure_check.rb
db/schema.rb
spec/controllers/steps/conviction/compensation_paid_controller_spec.rb
spec/forms/steps/conviction/compensation_paid_form_spec.rb

Basic step compensation paid step.  This step hasn't been link to the conviction path, this will come in and another PR after the compensation date step has been created.

Add compensation paid step

---

features/conviction_financial_discharge.feature
features/step_definitions/common.rb

Add feature tests for conviction discharge basis on [Conviction rules matrix](https://docs.google.com/spreadsheets/d/1ZSCk-wgMfIc22GQahKH_ys4u-E9GWIn6dQ7mm5t1RFI/edit#gid=0).

Add conviction discharge feature

---

config/locales/en/helpers.yml
features/conviction_hospital_guardianship_order.feature

Add feature tests for conviction hospital or guardianship order  basis on [Conviction rules matrix](https://docs.google.com/spreadsheets/d/1ZSCk-wgMfIc22GQahKH_ys4u-E9GWIn6dQ7mm5t1RFI/edit#gid=0).

Add conviction hospital or guardianship order feature

---

features/conviction_financial.feature

Add feature tests for conviction financial feature basis on [Conviction rules matrix](https://docs.google.com/spreadsheets/d/1ZSCk-wgMfIc22GQahKH_ys4u-E9GWIn6dQ7mm5t1RFI/edit#gid=0).

Add conviction financial feature

---

app/services/calculators/immediately_calculator.rb
app/value_objects/conviction_type.rb
features/conviction_youth_rehabilitation_order.feature
spec/services/calculators/immediately_calculator_spec.rb
spec/services/conviction_expiry_calculator_spec.rb

Small class for when spent time is immediately.
Currently just return the start date of the conviction.

Add immediately calculator

---

app/services/calculators/fine_calculator.rb
app/value_objects/conviction_type.rb
spec/services/calculators/fine_calculator_spec.rb
spec/services/conviction_expiry_calculator_spec.rb

Small class to calculate the spent date for fine based on the following logic:
- Conviction start date + 6 months

Add fine calculator

---

app/services/calculators/compensation_calculator.rb
app/services/conviction_expiry_calculator.rb
app/value_objects/conviction_type.rb
spec/services/calculators/compensation_calculator_spec.rb
spec/services/conviction_expiry_calculator_spec.rb

Small class to calculate spent time for compensation to a victim sub type
- Return Compensation payment date
Also update specs to check that the correct calculator is return for each given conviction sub type

Add compensation calculator

---

app/services/base_calculator.rb
app/services/calculators/conditional_caution_calculator.rb
app/services/calculators/detention_calculator.rb
app/services/caution_check_result.rb
spec/factories/disclosure_check.rb
spec/services/calculators/conditional_caution_calculator_spec.rb

Small class to calculate spent time for conditional caution
- If (conditions end date) - (caution given date) < 3 months: ends on condition end date
-  If (conditions end date) - (caution given date) is greater than or equal to 3 months: ends on caution given date + 3 months

Add conditional caution calculator

---

app/value_objects/conviction_type.rb
config/locales/en/helpers.yml
config/locales/en/results.yml
spec/forms/steps/conviction/conviction_type_form_spec.rb
spec/value_objects/conviction_type_spec.rb

Add Armed forces conviction type and subtype with the correct flow and result.  I am waiting on the correct copy.

Add armed forces conviction type and subtypes

---

app/services/calculators/detention_calculator.rb
spec/services/calculators/detention_calculator_spec.rb

Instead of `>= 4 years` it needs to be, after legal clarification, just greater than.

Update detention calculator

---

app/forms/concerns/single_question_form.rb
app/forms/steps/conviction/compensation_paid_form.rb
app/forms/steps/conviction/conviction_length_type_form.rb
app/forms/steps/conviction/conviction_subtype_form.rb
spec/forms/steps/conviction/compensation_paid_form_spec.rb
spec/forms/steps/conviction/conviction_length_type_form_spec.rb
spec/forms/steps/conviction/conviction_subtype_form_spec.rb

I think with this PR all the possible combinations or at least the realistic ones are covered.
If we add or remove some more steps, please lets not forget to also update if needed the reset mechanism.

Reset remaining form attributes

---

app/views/about/cookies.en.html.erb

These are the final copy changes indicated by Matt.

Copy amendments to the cookies page

---

app/assets/javascripts/application.js
app/assets/javascripts/modules/ga-events.js
app/helpers/application_helper.rb
app/views/layouts/_analytics.html.erb
app/views/layouts/_tag_manager.html.erb
app/views/layouts/_tag_manager_no_script.html.erb
app/views/layouts/application.html.erb
spec/helpers/application_helper_spec.rb

Remove google tag manager code.
Add google analytics code.  
Now send, which radio button was selected when any form is submit i.e

remove google tag manager and add google analytics

---

spec/factories/disclosure_check.rb
spec/presenters/conviction_result_presenter_spec.rb

Improve  conviction_result_presenter_spec add more details to #summary spec

Improve the Summary specs

---

app/views/home/index.en.html.erb

This should match the current latest version of the prototype and the correct link to the guidance.

Update service start page

---

app/forms/steps/conviction/conviction_length_type_form.rb
features/conviction_custodial_sentence.feature
spec/forms/steps/conviction/conviction_length_type_form_spec.rb

Display `No length was given` option  for sub type hospital orders

no length date given option for hospital orders

---

config/locales/en/helpers.yml
config/locales/en/results.yml
features/conviction_custodial_sentence.feature

Update  detention_training_order option from `Detention and training order` to `Detention and training order (DTO)`
Also update `custodial_ sentence` sub types hint text

update custodial_ sentence content

---

app/presenters/question_answer_row.rb
app/views/steps/check/results/_caution.en.html.erb
app/views/steps/check/results/_conviction.en.html.erb
app/views/steps/check/results/show.en.html.erb
config/locales/en/results.yml
spec/presenters/caution_result_presenter_spec.rb
spec/presenters/conviction_result_presenter_spec.rb
spec/presenters/question_answer_row_spec.rb

* Use long date format in results table
* Copy changes

Update results page

---

.circleci/config.yml

Using the same CircleCI flow as [C100](https://github.com/ministryofjustice/c100-application/blob/master/.circleci/config.yml)

Add production circleci flow

---

app/assets/javascripts/modules/ga-events.js
app/views/steps/caution/conditional_end_date/edit.html.erb
config/locales/en/caution.yml
config/locales/en/helpers.yml

Add expandable and collapsable box with content about when a condition has not ended.
Update hint text.

Update content in conditional end date view

---

config/locales/en/errors.yml

Updated error message for conditional cautions

---

app/views/steps/check/results/_caution.en.html.erb
app/views/steps/check/results/_conviction.en.html.erb
app/views/steps/check/results/show.en.html.erb

Copy change for caution and conviction result page

update caution and conviction result page copy

---

config/locales/en/caution.yml
config/locales/en/check.yml
config/locales/en/conviction.yml
config/locales/en/errors.yml

Update page title as agreed in the [ticket](https://www.pivotaltracker.com/n/projects/2311302/stories/167218973l)

Update page titles

---

app/assets/javascripts/modules/ga-events.js

We are going to track the year part of the dates. This will be done automatically as we already do with radios or links.
Removed `getCheckboxFormData()` function because this was not in use for this service.
Fixed the `revealingLinkClass` class. It was missing the initial dot.

Track in GA the year part of dates

---

.circleci/config.yml
.env.test.example
config/locales/en/helpers.yml
features/adults/caution.feature
features/caution.feature
features/youth/caution.feature

Update over caution type hints and add feature specs for over 18  caution journeys

display over 18 caution type

---

app/value_objects/conviction_type.rb
config/locales/en/helpers.yml
config/locales/en/results.yml
features/youth/conviction_prevention_and_reparation_order.feature
features/youth/conviction_youth_rehabilitation_order.feature
spec/forms/steps/conviction/conviction_subtype_form_spec.rb
spec/value_objects/conviction_type_spec.rb

Move Restraining Order, Reparation Order and Sexual harm prevention order convictions into the Prevention and Reparation Order

Move sub types into Prevention and Reparation Order

---

config/locales/en/helpers.yml

Update hint text to Prevention and Reparation orders

---

app/views/home/index.en.html.erb

With link to the terms and conditions page.
This link will track in GA.

Add disclaimer to home page

---

config/locales/en/helpers.yml

Amend the YRO hint text

---

app/value_objects/conviction_type.rb
config/locales/en/conviction.yml
config/locales/en/helpers.yml
config/locales/en/results.yml
features/adults/conviction_custodial_sentence.feature
features/adults/conviction_motoring.feature
features/adults/prevention_and_reparation_order.feature
spec/services/conviction_length_choices_spec.rb
spec/value_objects/conviction_type_spec.rb

Pending the calculator class in a couple of them, and also uncomment a couple of steps in the scenario `Motoring convictions without length`.

Add motoring convictions

---

app/services/calculators/motoring_calculator.rb
app/value_objects/conviction_type.rb
config/locales/en/results.yml
features/adults/conviction_motoring.feature
spec/services/calculators/motoring_calculator_spec.rb
spec/value_objects/conviction_type_spec.rb

Add motoring calculators 
- start date plus 3 years (36 months)
- start date plus 5 years (60 months)
Update  ADULT_ENDORSEMENT and  ADULT_PENALTY_POINTS  with the correct motoring  calculator
Uncomment the final step in the adult motoring feature tests.

Add Motoring calculators

---

app/services/calculators/sentence_calculator.rb
spec/services/calculators/sentence_calculator_spec.rb

Add a day to spent time in sentence calculator

---

config/locales/en/helpers.yml
config/locales/en/results.yml
features/adults/prevention_and_reparation_order.feature
features/youth/conviction_custodial_sentence.feature
features/youth/conviction_prevention_and_reparation_order.feature

update youth conviction types labels and hint text

---

app/assets/stylesheets/local/custom.scss
app/views/about/privacy.en.html.erb

Privacy notice copy changes

---

config/locales/en/conviction.yml
config/locales/en/helpers.yml
features/youth/conviction_custodial_sentence.feature

update question copy for DTO length question

---

app/views/steps/check/results/_caution.en.html.erb
app/views/steps/check/results/_conviction.en.html.erb
app/views/steps/check/results/shared/_summary.en.html.erb
app/views/steps/check/results/show.en.html.erb
config/locales/en/results.yml
features/youth/conviction_custodial_sentence.feature
features/youth/conviction_financial.feature

According to latest changes and legal.
Extracted some of the common content to a partial.

Update results page copy

---

config/locales/en/helpers.yml
config/locales/en/results.yml
features/adults/prevention_and_reparation_order.feature
features/youth/conviction_prevention_and_reparation_order.feature

Update conviction type label from `prevention and reparation order` to `prevention or reparation order`

Update conviction type prevention and reparation order label

---

app/views/home/index.en.html.erb

small copy change to the start page

---

config/locales/en/helpers.yml

As per latest copy review.
---

Update financial and supervision hint text

---

config/locales/en/helpers.yml
features/adults/conviction_financial.feature
features/youth/conviction_financial.feature

To read:
`Have you paid the compensation in full?`

Amend financial compensation header

---

app/views/home/index.en.html.erb

Update service start page copy

---

config/locales/en/helpers.yml
features/adults/conviction_custodial_sentence.feature

Small change to question and results page about when sentence started.

Change to custodial sentence question for adults

---

config/locales/en/helpers.yml

This hint text should be the same as for adults.

Update hint text for youths

---

app/views/steps/mvp/confirmation/show.en.html.erb
app/views/steps/mvp/info/edit.en.html.erb
config/locales/en/helpers.yml

And a small copy change to confirmation page.
This copy might still be subject to change but at least we get the general feeling of how it looks.

Add latest copy to MVP landing page

---

app/views/about/terms_and_conditions.en.html.erb

Small updates based on how the service has changes since we first created this copy and the inclusion of 'draft version' in the heading.

Updates to T&C page

---

app/controllers/backoffice/participants_controller.rb
app/models/participant.rb
app/views/backoffice/participants/_participant_row.html.erb
app/views/backoffice/participants/_participant_table.html.erb
app/views/backoffice/participants/index.en.html.erb
config/routes.rb
spec/controllers/backoffice/participants_controller_spec.rb
spec/factories/participant.rb
spec/models/participant_spec.rb
spec/rails_helper.rb

Page to list opted-out and opted-in  participants

---

app/controllers/steps/mvp_step_controller.rb
app/views/backoffice/participants/_participant_row.html.erb
app/views/backoffice/participants/index.en.html.erb
app/views/pilot/show.en.html.erb
config/locales/en/helpers.yml

And remove the now unused `Steps::MvpStepController`.

Fix some styling issues

---

app/views/pilot/show.en.html.erb

Two minor changes for the landing page:
1. There is a full stop missing from the final sentence!
2. Instead of saying `We'd like to ask if you could take a few minutes`I would suggest `Please could you take a few minutes`

small copy changes to pilot landing page

---

app/controllers/pilot_controller.rb
app/models/participant.rb
app/views/backoffice/participants/_participant_table.html.erb
spec/controllers/pilot_controller_spec.rb

And a few minor copy changes in the backoffice.

Track pilot landing page access

---

app/controllers/concerns/security_handling.rb

Only allow internal users access to the back office.

Stop pilot participants from using the backoffice

---

app/views/pilot/show.en.html.erb

Update pilot landing page for YOT Bulletin

---

app/views/pilot/show.en.html.erb

Update pilot landing page - remove the term young offender

---

app/presenters/conviction_result_presenter.rb
app/presenters/results_presenter.rb
app/services/calculators/motoring_calculator.rb
app/services/conviction_decision_tree.rb
app/views/steps/check/results/show.en.html+conviction_no_record.erb
config/locales/en/helpers.yml
config/locales/en/results.yml
features/adults/conviction_motoring.feature
spec/services/calculators/motoring_calculator_spec.rb
spec/services/conviction_decision_tree_spec.rb

- Add new non conviction results page
- Exit adult penalty notice journey if the conviction isn't endorsed

Update adult penalty notice journey

---

app/views/steps/check/results/shared/_disclaimer.en.html.erb
app/views/steps/check/results/shared/_meaning.en.html.erb
app/views/steps/check/results/shared/_summary.en.html.erb
app/views/steps/check/results/show.en.html+conviction_not_spent.erb
app/views/steps/check/results/show.en.html+conviction_spent.erb

Several copy changes to the final result page.

Update result page content

---

app/controllers/experiments_controller.rb
app/controllers/steps/conviction/conviction_type_controller.rb
app/controllers/steps/conviction/exit_motoring_controller.rb
app/services/check_decision_tree.rb
app/services/conviction_decision_tree.rb
app/views/steps/conviction/exit_motoring/show.html.erb
config/routes.rb
features/step_definitions/common.rb
spec/controllers/steps/conviction/exit_motoring_controller_spec.rb
spec/services/conviction_decision_tree_spec.rb

Add a feature flag to enable/disable adult motoring journey
Also add exit motoring page

Add feature-flag to enable/disable adult motoring journey

---

config/locales/en/conviction.yml

```<title>Conviction date - Check when a caution or conviction is spent - GOV.UK</title>```
will be come
```<title>Start date - Check when a caution or conviction is spent - GOV.UK</title>```
for conviction/know_date page title

Change ‘conviction date’ to ‘start date’

---

app/controllers/about_controller.rb
app/views/about/accessibility.en.html.erb
app/views/layouts/_footer_links.html.erb
config/locales/en/layouts.yml
config/routes.rb

- Add link in the footer to accessibility statement
- Add  accessibility statement copy
You can find the copy document is [here](https://docs.google.com/document/d/1x1fsCFG2ewlixVFlZhKQ-HxSR2jYoIO1V7Ryj96fJIQ/edit#heading=h.tbi70ua5oje3).

Add Accessibility statement

---

app/assets/stylesheets/local/custom.scss
app/views/steps/check/check_your_answers/shared/_check.html.erb
app/views/steps/check/check_your_answers/shared/_check_row.html.erb
app/views/steps/check/results/show.en.html+multiples.erb

Add the remaining copy to the results page, as per prototype (it might still change), and tweak the margins of some elements using custom CSS.

Finalise copy for multiple results

---

app/controllers/application_controller.rb
app/helpers/analytics_helper.rb
app/helpers/experiments_helper.rb
spec/helpers/analytics_helper_spec.rb

We are extending the YOT pilot by opening up the adults journeys also to them.

Enable adults for YOT participants

---

app/controllers/application_controller.rb
app/controllers/experiments_controller.rb
app/controllers/steps/check/under_age_controller.rb
app/helpers/experiments_helper.rb
app/services/check_decision_tree.rb
config/routes.rb
features/adults/caution.feature
features/step_definitions/common.rb
features/youth/caution.feature
spec/services/check_decision_tree_spec.rb

Remove adult feature flag code  and update specs and feature tests

Remove adult feature flag

---

app/views/steps/conviction/exit_motoring/show.html.erb

Update motoring kick out copy

---

config/locales/en/helpers.yml
config/locales/en/results.yml
features/youth/conviction_youth_rehabilitation_order.feature

A few copy changes as per feedback.

Amend copy in referral order

---

app/views/pilot/show.en.html.erb

Update landing page copy too match this [document](https://docs.google.com/document/d/1ynb8Xmgx-Y0IEpg3AVZ54YhndDIpdZBVdLOUelU4pJk/edit#)

Update landing page copy for adult release

---

app/views/home/index.en.html.erb

Remove mention of over 18 in home page

---

app/views/pilot/show.en.html.erb

Update title to `About this pilot`

Update landing page title

---

app/controllers/steps/conviction/conviction_bail_controller.rb
app/forms/steps/conviction/conviction_bail_form.rb
app/views/steps/conviction/conviction_bail/edit.html.erb
config/locales/en/conviction.yml
config/locales/en/errors.yml
config/locales/en/helpers.yml
config/routes.rb
db/migrate/20191120110442_add_conviction_bail_to_disclosure_check.rb
db/schema.rb
spec/controllers/steps/conviction/conviction_bail_controller_spec.rb
spec/forms/steps/conviction/conviction_bail_form_spec.rb

A yes-no question form, with corresponding DB migration, to ask the user if they spent any time on bail with an electronic tag, as if they do, the rehabilitation calculation will be different.
This is the first PR of a series, and it is not yet linked to the journey so the question will not show until we update the decision tree in a later PR.

Add bail yes-no question

---

app/decorators/conviction_decorator.rb
app/forms/steps/conviction/conviction_bail_form.rb
app/forms/steps/conviction/conviction_subtype_form.rb
app/services/conviction_decision_tree.rb
config/locales/en/helpers.yml
features/adults/conviction_custodial_sentence.feature
features/youth/conviction_custodial_sentence.feature
spec/decorators/conviction_decorator_spec.rb
spec/forms/steps/conviction/conviction_bail_form_spec.rb
spec/forms/steps/conviction/conviction_subtype_form_spec.rb
spec/services/conviction_decision_tree_spec.rb

This will show the bail questions if the conviction is bailable. If not, normal flow applies.
Also updated the feature tests.
Individual commits for clarity.

Update decision tree for bail questions

---

config/locales/en/helpers.yml

Minor amendments to discharge convictions date hint text, and conditional discharge radio hint text.

More hint copy amendments

---

app/views/steps/check/results/show.en.html+caution_not_spent.erb
app/views/steps/check/results/show.en.html+caution_spent.erb
app/views/steps/check/results/show.en.html+conviction_never_spent.erb
app/views/steps/check/results/show.en.html+conviction_no_record.erb
app/views/steps/check/results/show.en.html+conviction_not_spent.erb
app/views/steps/check/results/show.en.html+conviction_spent.erb
features/adults/caution.feature
features/youth/caution.feature

Replace `Your` with `This` as per content designer suggestions.

Amend results page spent date panel

---

app/assets/javascripts/modules/ga-events.js

Same code as we have used on the C100 service.
This will allow us to track checkboxes on GA.

Add checkbox tracking

---

config/locales/en/helpers.yml
features/youth/conviction_military.feature

Make this copy the same as over-18s.

Update under-18s military conviction copy

---

README.md
app/views/about/terms_and_conditions.en.html.erb
config/locales/en.yml
spec/helpers/application_helper_spec.rb

As per latest decisions and to match the new domain.

Minor service rename

---

app/controllers/steps/conviction/compensation_paid_amount_controller.rb
app/controllers/steps/conviction/compensation_payment_receipt_controller.rb
app/controllers/steps/conviction/compensation_unable_to_tell_controller.rb
app/forms/steps/conviction/compensation_paid_amount_form.rb
app/forms/steps/conviction/compensation_payment_receipt_form.rb
app/services/conviction_decision_tree.rb
app/views/steps/conviction/compensation_paid_amount/edit.html.erb
app/views/steps/conviction/compensation_payment_receipt/edit.html.erb
app/views/steps/conviction/compensation_unable_to_tell/show.html.erb
config/locales/en/conviction.yml
config/locales/en/helpers.yml
config/routes.rb
db/migrate/20200329155646_add_compensation_payment_over_100_to_disclosure_checks.rb
db/migrate/20200329155945_add_compensation_receipt_sent_to_disclosure_checks.rb
db/schema.rb
features/adults/conviction_financial.feature
features/youth/conviction_financial.feature
spec/controllers/steps/conviction/compensation_paid_amount_controller_spec.rb
spec/controllers/steps/conviction/compensation_payment_receipt_controller_spec.rb
spec/controllers/steps/conviction/compensation_unable_to_tell_controller_spec.rb
spec/services/conviction_decision_tree_spec.rb

We are introducing two new questions around payments
Story: https://mojdigital.teamwork.com/#/tasks/19826007

Add questions about compensation orders

---

app/views/steps/check/results/shared/_disclaimer.en.html.erb
app/views/steps/check/results/shared/_guidance.en.html.erb
app/views/steps/check/results/shared/_summary.en.html.erb
app/views/steps/check/results/show.en.html+caution_not_spent.erb
app/views/steps/check/results/show.en.html+caution_spent.erb
app/views/steps/check/results/show.en.html+conviction_never_spent.erb
app/views/steps/check/results/show.en.html+conviction_not_spent.erb
app/views/steps/check/results/show.en.html+conviction_spent.erb
app/views/steps/check/results/show.en.html+multiples.erb

We have decided the section no longe should be used.
Story: https://mojdigital.teamwork.com/#/tasks/19966300

Update results page content

---

app/views/steps/check/results/shared/_disclaimer.en.html.erb

Story: https://mojdigital.teamwork.com/#/tasks/19966300

Update missing text

---

config/locales/en/helpers.yml

Story: https://mojdigital.teamwork.com/#/files/4650265

Update content on conviction type and community

---

app/views/home/index.en.html.erb

Story: https://mojdigital.teamwork.com/#/files/4650265

update the start page text

---

features/adults/conviction_motoring.feature

Some refactoring and clean up on the adult motoring feature

Update feature test for adult motoring conviction

---

app/presenters/caution_result_presenter.rb
app/services/calculators/caution_calculator.rb
app/services/caution_decision_tree.rb
app/views/steps/check/results/show.en.html+caution_spent_simple.erb
features/adults/caution.feature
features/youth/caution.feature
spec/factories/disclosure_check.rb
spec/presenters/caution_result_presenter_spec.rb
spec/services/calculators/caution_calculator_spec.rb
spec/services/caution_decision_tree_spec.rb

Story: https://mojdigital.teamwork.com/#/tasks/21186055
- Update caution decision tree
- Update caution result presenter
Co-authored-by: @njseeto

Simplify youth adult cautions journey v2

---

features/adults/conviction_custodial_sentence.feature
features/adults/conviction_motoring.feature
features/youth/conviction_custodial_sentence.feature

Story: https://mojdigital.teamwork.com/#/tasks/21346675
Refactor cucumber tests to use `@date_travel` to future proof tests.

Refactor Cucumber Tests to use @date_travel

---

app/views/about/accessibility.en.html.erb

As per request, we are making it more similar to the one we have on CAS, as both uses the same third-party supplied feedback service.

Update accessibility statement copy

---

app/value_objects/conviction_type.rb
config/locales/en/helpers.yml
features/adults/conviction_financial.feature
features/adults/conviction_motoring.feature
features/youth/conviction_financial.feature
features/youth/conviction_motoring.feature
spec/value_objects/conviction_type_spec.rb

Task: https://mojdigital.teamwork.com/#/tasks/21185793
If these changes are approved the questions will look as follows:
YOUTH:
ADULT:

Clarify that motoring fines do not come under Financial Penalties.

---

app/forms/steps/caution/caution_type_form.rb
app/views/steps/caution/caution_type/edit.html.erb
config/locales/en/helpers.yml
spec/forms/steps/caution/caution_type_form_spec.rb
spec/i18n_spec.rb

Task: https://mojdigital.teamwork.com/#/tasks/21707821

Migrate caution type to use new gem

---

app/views/steps/conviction/compensation_paid_amount/edit.html.erb
config/locales/en/helpers.yml

Story: https://mojdigital.teamwork.com/#/tasks/21707829

Update Design System for steps/conviction/compensation_paid_amount

---

app/forms/steps/conviction/conviction_type_form.rb
app/views/steps/conviction/conviction_type/edit.html.erb
config/locales/en/helpers.yml
spec/forms/steps/conviction/conviction_type_form_spec.rb

Story: https://mojdigital.teamwork.com/#/tasks/21725157

Update Design System for steps/conviction/conviction_type

---

app/forms/steps/check/under_age_form.rb
app/views/steps/check/under_age/edit.html.erb
config/locales/en/helpers.yml
spec/forms/steps/check/under_age_form_spec.rb

Task: https://mojdigital.teamwork.com/#/tasks/21707824

Update Design System for under_age

---

app/forms/steps/conviction/conviction_subtype_form.rb
app/views/steps/conviction/conviction_subtype/edit.html.erb
config/locales/en/helpers.yml
spec/forms/steps/conviction/conviction_subtype_form_spec.rb
spec/i18n_spec.rb

Story: https://mojdigital.teamwork.com/#/tasks/21725158

Update Design System for steps/conviction/conviction_subtype

---

app/views/steps/conviction/conviction_bail/edit.html.erb
config/locales/en/helpers.yml

Task: https://mojdigital.teamwork.com/#/tasks/21725161

Upgrade Design System for steps/conviction/conviction_bail

---

app/views/steps/conviction/motoring_endorsement/edit.html.erb
config/locales/en/errors.yml
config/locales/en/helpers.yml

Task: https://mojdigital.teamwork.com/#/tasks/21742527

Update Design System for steps/conviction/motoring_endorsement

---

app/forms/steps/conviction/conviction_length_type_form.rb
app/views/steps/conviction/conviction_length_type/edit.html.erb
config/locales/en/helpers.yml
spec/forms/steps/conviction/conviction_length_type_form_spec.rb

Story: https://mojdigital.teamwork.com/#/tasks/21725160

Update Design System for steps/conviction/conviction_length_type

---

app/forms/steps/conviction/conviction_length_form.rb
app/views/steps/conviction/conviction_length/edit.html.erb
config/locales/en/helpers.yml
spec/forms/steps/conviction/conviction_length_form_spec.rb

Task: https://mojdigital.teamwork.com/#/tasks/21742522

Update Design System for steps/conviction/conviction_length

---

Dockerfile

Duplicated copy instruction of Gemfile

Remove duplicated copy instruction

---

app/views/layouts/_phase_banner.html.erb

Ticket: https://mojdigital.teamwork.com/#/tasks/19307648

Change phase banner from alpha to beta

---

app/value_objects/conviction_type.rb
config/locales/en/helpers.yml
config/locales/en/results.yml
features/adults/conviction_community_prevention_reparation.feature
spec/services/conviction_length_choices_spec.rb
spec/value_objects/conviction_type_spec.rb

Ticket: https://mojdigital.teamwork.com/#/tasks/22730239
* Fix youth supervision order
* Remove adult supervision order
More details in the individual commits.

Tweak supervision orders

---

app/views/steps/check/results/shared/_motoring.en.html.erb

Ticket: https://mojdigital.teamwork.com/#/tasks/22457677
This link was not fully accessible before.

Copy change in results link

---

app/views/about/terms_and_conditions.en.html.erb
app/views/home/index.en.html.erb
app/views/steps/check/results/shared/_disclaimer.en.html.erb
app/views/steps/check/results/shared/_summary.en.html.erb

Ticket: https://mojdigital.teamwork.com/#/tasks/22457649
Copy changes to the disclaimers and terms and conditions across the service in response to some GDS feedback.

Copy changes to disclaimers and terms

---

spec/factories/disclosure_check.rb

Story: https://trello.com/c/Ru4rQKsv/57-dc-write-real-multiple-conviction-examples
Follow up on #425 
Usage example:
```ruby
FactoryBot.create(:disclosure_check, :with_prison_sentence)
FactoryBot.create(:disclosure_check, :with_prison_sentence, :with_conviction_bail)
FactoryBot.create(:disclosure_check, :youth, :with_bind_over)
FactoryBot.create(:disclosure_check, :adult, :with_bind_over)
FactoryBot.create(:disclosure_check, :adult, :with_sexual_harm_order)
FactoryBot.create(:disclosure_check, :adult, :with_bind_over)
```

Add more individual conviction factories

---

config/locales/en/layouts.yml

Story: https://trello.com/c/js5uPmbP/51-dc-update-beta-banner-wording

Update BETA banner wording

---

app/services/calculators/multiples/multiple_offenses_calculator.rb
spec/services/calculators/multiples/given_scenarios_spec.rb
spec/services/calculators/multiples/multiple_offenses_calculator_spec.rb

Ticket: https://trello.com/c/AeZ9GHp0
This is supposed to "fix" yet another edge case, but using a very basic "memory" where we store the spent date after any drag-though so in the following iteration of the loop, we use it if present and keep dragging the date if needed (and store back again in the memory).
We've made the minimum amount of changes but there are other approaches.

Improve multiples calculator with a memory (relevant orders fix)

---

README.md
spec/services/calculators/multiples/given_scenarios_spec.rb
spec/services/calculators/multiples/multiple_offenses_calculator_spec.rb

I've added references to the graphs on tests that I thought it would be beneficial,
I did not want to add them on all as it could cause potential misunderstandings.
I've also added references to the README.md so that newcomers can see it and get familiar with
the most important part of this service - the calculations.
Ticket: https://trello.com/c/kT50EDZ7

Improve documentation to explain multiple convictions

---

app/views/steps/check/results/shared/_meaning.en.html.erb
app/views/steps/check/results/shared/_meaning_cautions.en.html.erb

Story: 
https://trello.com/c/p8SfPgjj/133-updated-links-for-dc-start-page-on-govuk
Implementation Story: 
https://trello.com/c/Yr1hrUVZ/122-dc-govuk-start-page-redirect-guidance-links-on-results-page-to-the-mainstream-guide

Update copy on results page

---

app/value_objects/conviction_type.rb
config/locales/en/conviction.yml
config/locales/en/helpers.yml
features/adults/conviction_military.feature
features/youth/conviction_military.feature
spec/value_objects/conviction_type_spec.rb

https://user-images.githubusercontent.com/136777/110816404-38c9ad80-8283-11eb-9580-cbf7a49a2460.mov
Currently we do not ask the length of a military service detention,
according to legal, we must ask for that length and then add 12 months for adults or 6 months for youth.
The correct interpretation is the following:
For adults, it's 12 months after the length given
For youth, it's 6 months after the length given
Story: https://trello.com/c/WzSPxKYw

Correction on Military Service Detention

---

config/locales/en/helpers.yml
config/locales/en/results.yml
docs/relevant_orders.md
features/adults/conviction_community_prevention_reparation.feature
features/youth/conviction_prevention_reparation.feature

Story: https://trello.com/c/Zmxsw5Np

Update conviction name to Sexual harm prevention order

---

lib/generators/step/templates/question/edit.html.erb
lib/generators/step/templates/show/show.html.erb

This is only to update the templates used by the generators.

Update Question generator

---

app/helpers/experiments_helper.rb
app/views/steps/check/results/show.en.html+conviction_indefinite.erb
features/adults/caution.feature
features/adults/conviction_community_prevention_reparation.feature
features/adults/conviction_custodial_sentence.feature
features/adults/conviction_discharge.feature
features/adults/conviction_financial.feature
features/adults/conviction_military.feature
features/adults/conviction_motoring.feature
features/step_definitions/common.rb
features/youth/caution.feature
features/youth/conviction_custodial_sentence.feature
features/youth/conviction_discharge.feature
features/youth/conviction_financial.feature
features/youth/conviction_military.feature
features/youth/conviction_motoring.feature
features/youth/conviction_prevention_reparation.feature
features/youth/conviction_referral_supervision_yro.feature
spec/support/step_controller_shared_examples.rb

🎏This PR enables the multiples conviction journey. 🎏
We are getting this ready for next weeks deploy.
On hold until legal sign off
Will need copy updates from content designer, I will do those in a separate PR against this PR, then we can ship it all together, as I don't want to clog the deployment pipeline with this until we have sign off.
Story: https://trello.com/c/IimlbdWM

🎏Feature flag enable multiples journey

---

docs/relevant_orders.md

This is just a mirror update of our [spreadsheet](https://docs.google.com/spreadsheets/d/1o7OligQtUKNIz_nzREb3PSUEQZje2by1_6BEKybGATc/edit#gid=583473806).

Update Relevant Orders documentation

---

docs/relevant_orders.md

Fixes #489
I've looked into the wrong column to update this information, it was in reversed order.

Correct subject to drag through column

---

app/views/steps/check/check_your_answers/show.en.html.erb
config/locales/en/helpers.yml
features/step_definitions/common.rb

As per service designer latest prototype.

Minor copy changes to CYA next steps section

---

features/multiples/cautions_and_convictions.feature

This feature example covers a journey with two convictions (Discharge Order and Community Order).
I may be able to cut the number of steps in the future, right now I just wanted to have a feature test that goes around a second round.

Add feature for multiple convictions

---

app/views/steps/check/check_your_answers/show.en.html.erb

Story: 
https://trello.com/c/EZIZpkfD/264-dc-check-your-answers-page-design-updates

Update copy around buttons in CYA page

---

app/views/steps/check/results/shared/_feedback.en.html.erb

Ticket: https://trello.com/c/PslLguBi
Update the end of service survey with a new one as provided by user researcher.
As this survey is longer (it has an extra question) I've had to tweak the styling of it so it shows in full length.

Update results page survey

---

app/views/steps/check/check_your_answers/show.en.html.erb
app/views/steps/check/results/show.en.html.erb
config/locales/en/check.yml
features/fixtures/files/steps_check_kind.html
features/fixtures/files/steps_check_kind_with_errors.html

Ticket: https://trello.com/c/WpAWw9Sc
A few copy changes suggested by our content designer.
There are a couple copy changes remaining that needs discussion, will be made in a separate PR when decided.

Minor copy changes

---

app/views/steps/check/results/shared/_dbs_visibility.html.erb
app/views/steps/check/results/show.en.html.erb
config/locales/en/results.yml
features/adults/caution.feature
features/adults/conviction_discharge.feature

Ticket: https://trello.com/c/WpAWw9Sc
This is a follow-up to PR #550. There was a missing paragraph that has been implemented in this PR.
However this PR might not be required, just leaving here until we get confirmation from content designer.

Explain DBS `may appear` in results page

---

Gemfile
Gemfile.lock
app/views/layouts/govuk_template.html.erb
app/views/steps/check/check_your_answers/shared/_row.html.erb
app/views/steps/check/results/shared/_row.html.erb
config/initializers/form_builder.rb
features/fixtures/files/steps_check_kind.html
features/fixtures/files/steps_check_kind_with_errors.html
features/fixtures/files/steps_conviction_known_date.html
features/fixtures/files/steps_conviction_known_date_with_errors.html
package.json
yarn.lock

Ticket: https://trello.com/c/mAgT1TEW
Use the latest version of `govuk-frontend` which contains some markup changes.
This is a follow-up to the previous PR #562.

Upgrade to govuk-frontend 4.0.0

---

.github/workflows/test-build-deploy.yml
README.md

Rename default branch

---

.github/dependabot.yml

By default up to 5 PRs will be created for each package ecosystem.

CDPT-630 Add dependabot config

---

Gemfile
Gemfile.lock

Replace web-console with better_errors

Add better errors

---

.github/workflows/test-build-deploy.yml

Update build_tag to be shown on /ping page.

Pass env vars to docker image and fix build tag

---

.github/workflows/manual-deploy.yml

This should allow deploys to staging from a branch/PR.

Create manual deploy workflow

---

.github/workflows/deploy.yml

Remove input from manual workflow

---

config/locales/en/errors.yml

Minor change needed to the grammar

Schedule18 grammar fix for error translation

---

app/forms/steps/conviction/conviction_schedule18_form.rb
app/views/steps/conviction/conviction_schedule18/edit.html.erb
config/locales/en/conviction.yml
config/locales/en/helpers.yml
features/adults/conviction_custodial_sentence.feature
features/youth/conviction_custodial_sentence.feature
spec/forms/steps/conviction/conviction_schedule18_form_spec.rb

As per the Jira ticket https://dsdmoj.atlassian.net/jira/software/c/projects/CDPT/boards/1152?modal=detail&selectedIssue=CDPT-982, additional wording required for the Schedule 18 policy source link

Screen one content change schedule18

---

app/views/layouts/_notification_banner.html.erb
app/views/layouts/govuk_template.html.erb
app/views/steps/check/check_your_answers/show.en.html.erb
app/views/steps/check/kind/edit.html.erb
app/views/steps/check/results/show.en.html.erb
config/locales/en/layouts.yml
features/notification_banner.feature
features/step_definitions/common.rb

Adds banner to show info about upcoming changes on the following pages:
- start
- check your answers
- results

CDPT-969 Add notification banner

---

app/value_objects/conviction_type.rb
features/multiples/cautions_and_convictions.feature
spec/services/calculators/multiples/multiple_offenses_calculator_scenarios_spec.rb
spec/value_objects/conviction_type_spec.rb

Change to legislation for calculation of community order rehabilitation times.

CDPT-947 Community Orders are spent at end of order

---

app/value_objects/conviction_type.rb
config/locales/en/helpers.yml
config/locales/en/results.yml
spec/forms/steps/conviction/conviction_subtype_form_spec.rb
spec/services/conviction_length_choices_spec.rb
spec/value_objects/conviction_type_spec.rb

An "Any other order with requirement" option was missing for under 18s.

Add youth other requirement order

---

app/controllers/application_controller.rb
config/locales/en/errors.yml

A maintenance page will appear in place of every page on the site.

CDPT-1059 Enable maintenance mode

---

app/views/steps/check/results/shared/_dbs_visibility.html.erb
features/adults/caution.feature
features/adults/conviction_discharge.feature
features/youth/caution.feature

Remove whether conviction / caution will appear on a standard or enhanced DBS check.

CDPT-1112 Remove enhanced check details

---

app/views/steps/check/results/show.en.html.erb

Update text to better reflect differences between different DBS checks

CDPT-1114 Update DBS wording

---

app/controllers/home_controller.rb
app/views/home/index.en.html.erb
app/views/steps/check/kind/edit.html.erb
app/views/steps/check/results/show.en.html.erb
features/02_cookies_consent.feature
features/adults/caution.feature
features/fixtures/files/steps_check_kind.html
features/fixtures/files/steps_check_kind_with_errors.html
features/multiples/cautions_and_convictions.feature
features/notification_banner.feature
features/step_definitions/common.rb
features/youth/caution.feature
spec/controllers/home_controller_spec.rb

- New starting page with disclaimer
- Add disclaimer to results page
- Remove text about adding all sentences

CDPT-1113 Disclaimers

---

app/views/home/index.en.html.erb
app/views/steps/check/kind/edit.html.erb

Moves back link to disclaimer page, and links first step page to disclaimer page.

Add back link

---

.github/workflows/test.yml
Gemfile
Gemfile.lock
app/controllers/errors_controller.rb
spec/controllers/backoffice/home_controller_spec.rb
spec/controllers/errors_controller_spec.rb
spec/spec_helper.rb

Add Test code coverage check

---

.github/workflows/deploy.yml

Tagging doesn't make sense here

Just push image

---

Dockerfile
config/database.yml

Removed download of rds certificate and disabled staging verification as this is not used for any other Ruby apps.

Remove check for certificate
