lib/generators/step/USAGE
lib/generators/step/step_generator.rb
lib/generators/step/templates/date/controller.rb
lib/generators/step/templates/date/controller_spec.rb
lib/generators/step/templates/date/edit.html.erb
lib/generators/step/templates/date/form.rb
lib/generators/step/templates/date/form_spec.rb

In a similar way to the other steps generators, this will generate a
form prepared to take a date input.

Add a date step generator

---

Gemfile
Gemfile.lock

The version 4.0.0 of the `gov_uk_date_fields` gem has been published, with support for the new design system.
https://github.com/ministryofjustice/gov_uk_date_fields/releases/tag/v4.0.0
We can use Rubygems instead of pointing directly to the repository.

Update `gov_uk_date_fields` gem

---

app/controllers/steps/caution/result_controller.rb
app/presenters/caution_result_presenter.rb
app/services/caution_decision_tree.rb
app/views/home/index.en.html.erb
app/views/steps/caution/result/shared/_row.html.erb
app/views/steps/caution/result/show.html.erb
config/locales/en.yml
config/routes.rb
spec/controllers/steps/caution/result_controller_spec.rb
spec/helpers/application_helper_spec.rb
spec/presenters/caution_result_presenter_spec.rb
spec/services/caution_decision_tree_spec.rb

[Link to story](https://www.pivotaltracker.com/n/projects/2311302/stories/164006866)
- caution result page
- CautionResultPresenter to present the questions and answers for simple caution journey
Result page in the [prototype](http://localhost:3000/steps/caution/result), i have updated it to use gov.uk design system

add caution result page

---

app/controllers/concerns/completion_step.rb
app/controllers/concerns/error_handling.rb
app/controllers/errors_controller.rb
app/controllers/step_controller.rb
app/controllers/steps/caution/result_controller.rb
app/errors/errors.rb
app/views/errors/check_completed.html.erb
app/views/steps/caution/result/show.html.erb
config/locales/en.yml
config/routes.rb
spec/controllers/application_controller_spec.rb
spec/controllers/steps/caution/result_controller_spec.rb
spec/support/step_controller_shared_examples.rb

https://www.pivotaltracker.com/story/show/164861902
In order to know when a check has been completed, we change their `status` attribute from `in_progress` to `completed`.
This also allow us to handle errors when trying to modify a completed check, and in the future will let us know which checks we can purge from the database, among other functionality we might want to introduce.
Note: the copy in the views is temporary until we have the final sign-off.

Mark a check as completed

---

Gemfile
Gemfile.lock
config/i18n-tasks.yml
config/initializers/i18n.rb
config/locales/en/caution.yml
config/locales/en/check.yml
config/locales/en/date.yml
config/locales/en/errors.yml
config/locales/en/helpers.yml
config/locales/en/home.yml
config/locales/en/layouts.yml
config/locales/en/service.yml
config/locales/en/shared.yml
config/locales/en/warning.yml
spec/i18n_spec.rb
spec/lib/govuk_components/form_builder_spec.rb

Locale file can be come very large, quickly an it becomes a chore to update the locale file.   I have separated the main section into different files to make editing/adding keys easier.

Split locale file  into several smaller files

---

.circleci/config.yml
.dockerignore
Dockerfile.nginx
README.md
config/nginx.conf

The change to CircleCI is needed as we now have 2 containers inside the deployment, one is named `webapp` and is the rails application, the other is named `nginx`. The names are now accurate to what they represent.
Some other minor improvements to the documentation.

Update Circle CI deployment

---

app/controllers/steps/caution/known_caution_date_controller.rb
app/forms/steps/caution/known_caution_date_form.rb
app/helpers/application_helper.rb
app/presenters/caution_result_presenter.rb
app/services/caution_decision_tree.rb
app/services/check_decision_tree.rb
app/services/expiry_date_calculator.rb
app/views/steps/caution/known_caution_date/edit.html.erb
app/views/steps/caution/result/shared/_row.html.erb
app/views/steps/caution/result/show.html.erb
config/locales/en/caution.yml
config/locales/en/errors.yml
config/locales/en/helpers.yml
config/routes.rb
db/migrate/20190328091950_add_known_caution_date_to_disclosure_check.rb
db/schema.rb
features/caution.feature
spec/controllers/steps/caution/known_caution_date_controller_spec.rb
spec/factories/disclosure_check.rb
spec/forms/steps/caution/known_caution_date_form_spec.rb
spec/helpers/application_helper_spec.rb
spec/presenters/caution_result_presenter_spec.rb
spec/services/caution_decision_tree_spec.rb
spec/services/check_decision_tree_spec.rb

[Link to ticket](https://www.pivotaltracker.com/n/projects/2311302/stories/164953853)
Add the following 
- a step between caution or conviction question  and enter caution date
- migration to add known_caution_date to disclosure-check table.
- update caution decision tree to bypass entering caution date if not know
- update caution result page to display caution date if caution date is known else this:
> Your caution expired on the day you were given it
- update feature tests

add new step known caution date

---

app/controllers/steps/conviction/conviction_type_controller.rb
app/forms/steps/conviction/conviction_type_form.rb
app/services/conviction_decision_tree.rb
app/value_objects/conviction_type.rb
app/views/steps/conviction/conviction_type/edit.html.erb
config/locales/en/conviction.yml
config/locales/en/errors.yml
config/locales/en/helpers.yml
config/routes.rb
db/migrate/20190402130429_add_conviction_type_to_disclosure_checkt.rb
db/schema.rb
lib/govuk_components/form_builder.rb
spec/controllers/steps/conviction/conviction_type_controller_spec.rb
spec/forms/steps/conviction/conviction_type_form_spec.rb
spec/lib/govuk_components/form_builder_spec.rb
spec/services/conviction_decision_tree_spec.rb

[Link to story](https://www.pivotaltracker.com/n/projects/2311302/stories/165022999)
Add the following
- a step a new to select type of conviction
- conviction type value object
- update form builder to add radio hint messages as describe in the [design system](https://design-system.service.gov.uk/components/radios/)
You see conviction type radio buttons with hints below:

Add Step: Which type of conviction were you given?

---

app/forms/steps/conviction/known_date_form.rb
config/locales/en/errors.yml
spec/forms/steps/conviction/known_date_form_spec.rb

Now we are re-using some DB attributes in different form objects, we need a way to specify different error messages depending on the step we are.
I didn't remember, but the gem provides this mechanism out of the box. The only thing we need to do is reorganise a bit the locales, as shown in this PR.
We should do the same for the rest of errors.

Make errors specific for each form

---

config/locales/en/helpers.yml
db/migrate/20190606134632_remove_columns_from_disclosure_check.rb
db/schema.rb
spec/factories/disclosure_check.rb

Delete caution_date, under_age_conviction and conviction_date columns.
General clean up any use of the above column names.

remove unused db columns

---

app/services/caution_decision_tree.rb
app/services/check_decision_tree.rb
app/services/conviction_decision_tree.rb
app/services/expiry_date_calculator.rb
config/locales/en/helpers.yml
features/caution.feature
features/conviction.feature
spec/presenters/caution_result_presenter_spec.rb
spec/services/caution_decision_tree_spec.rb
spec/services/check_decision_tree_spec.rb
spec/services/conviction_decision_tree_spec.rb

Update question flow for both conviction and caution paths to match MVP flow diagram https://dsdmoj.atlassian.net/wiki/spaces/CJDT/pages/1390018589/Disclosure+Checker
Please note the conviction path only goes up to entering a conviction date.
I another pr will be open for length of conviction.

Update question flow

---

app/forms/steps/conviction/conviction_length_form.rb
app/forms/steps/conviction/conviction_subtype_form.rb
app/views/steps/conviction/conviction_length/edit.html.erb
config/locales/en/errors.yml
config/locales/en/helpers.yml
lib/govuk_components/form_builder.rb
spec/fixtures/files/text_field.html
spec/fixtures/files/text_field_error.html
spec/fixtures/files/text_field_no_page_heading.html
spec/forms/steps/conviction/conviction_length_form_spec.rb
spec/lib/govuk_components/form_builder_spec.rb

Similar to what we did for `#radio_button_fieldset`, we must reimplement the `#text_field` method in order to produce the new markup expected with the new Design System.
It works in a similar way to `#radio_button_fieldset` and supports most of the options.
Also, the hint can be customised and will take its locales from the `conviction_length_type` attribute value. So we can change the hint based on weeks, months or years.

Conviction length text field

---

config/locales/en/helpers.yml
features/caution.feature
features/conviction_custodial_sentence.feature
features/step_definitions/common.rb

Add feature tests for conviction custodial sentence basis on [Conviction rules matrix](https://docs.google.com/spreadsheets/d/1ZSCk-wgMfIc22GQahKH_ys4u-E9GWIn6dQ7mm5t1RFI/edit#gid=0).
Update Caution feature tests to include exact text

Add conviction custodial sentence feature specs

---

lib/govuk_components/error_helpers.rb
spec/fixtures/files/error_summary_text_box.html
spec/lib/govuk_components/error_helpers_spec.rb

Error message link will now focus on the text box. <img width="909" alt="Screen Shot 2019-06-24 at 13 37 03" src="https://user-images.githubusercontent.com/22822829/60019183-34132f00-9685-11e9-90c4-f42695affe0b.png">

fix issue with error message focus with text boxes

---

Gemfile
Gemfile.lock
app/forms/base_form.rb
app/forms/steps/conviction/conviction_subtype_form.rb
app/value_objects/conviction_type.rb
app/views/steps/conviction/known_date/edit.html.erb
config/locales/en/conviction.yml
config/locales/en/helpers.yml
features/conviction_custodial_sentence.feature
features/conviction_financial.feature
features/conviction_financial_discharge.feature
features/conviction_youth_rehabilitation_order.feature
spec/forms/base_form_spec.rb
spec/forms/steps/conviction/conviction_subtype_form_spec.rb

Depending on the subtype of conviction, the header of this step can vary, so for example in most cases we talk about an `order` but in a few cases it can be a `sentence`, a `discharge` or even a `treatment`.
In order to do that we've bumped the version of the `gov_uk_date_fields` in this PR ministryofjustice/gov_uk_date_fields#36
Updated the cucumber tests to also test properly these headers.
Please note this is the first PR, but another one will be needed to do the same with other steps (and update the FormBuilder to also use the `i18n_attribute` for consistency).

 Make the `known_date` header dynamic

---

app/forms/steps/conviction/conviction_length_type_form.rb
app/views/steps/conviction/conviction_length/edit.html.erb
app/views/steps/conviction/conviction_length_type/edit.html.erb
app/views/steps/conviction/conviction_subtype/edit.html.erb
config/locales/en/helpers.yml
features/conviction_custodial_sentence.feature
features/conviction_financial_discharge.feature
features/conviction_hospital_guardianship_order.feature
features/conviction_youth_rehabilitation_order.feature
features/step_definitions/common.rb
lib/govuk_components/form_builder.rb
spec/forms/steps/conviction/conviction_length_type_form_spec.rb
spec/lib/govuk_components/form_builder_spec.rb

Same as we did in the previous PR #83, we are going to rename the previous `virtual_attribute` to `i18n_attribute` and a bit of refactor.
* Update the views to use this new option and the locales according the matrix.
* Update cucumber tests.
Note: for now, the `conviction_length` text field will not pick the `i18n_attribute`, that will be done in the next PR.

 Implement `i18n_attribute` for radio_button_fieldset

---

app/services/base_calculator.rb
app/services/calculators/conviction_end_date_calculator.rb
app/services/conviction_expiry_calculator.rb
app/value_objects/conviction_type.rb
spec/services/calculators/conviction_end_date_calculator_spec.rb
spec/services/conviction_expiry_calculator_spec.rb

Small class to calculate the end of conviction by adding conviction start date (known_date) with conviction length.  i.e  2000-01-01 + 1.year. 
Please note:  conviction length type is saved as  plural (months, weeks, days) has to be singular for the calculation.

Add conviction end date calculator

---

app/services/calculators/detention_calculator.rb
app/value_objects/conviction_type.rb
spec/services/calculators/detention_calculator_spec.rb

Small class to calculate the spent date for detention based on the following logic:
- If conviction length is 6 months or less: conviction start date + conviction length + 18 months
- If conviction length is over 6 months and less than or equal to 30 months: conviction start date + conviction length + 2 years
- If conviction length is over 30 months and less than 4 years: conviction start date + conviction length + 3.5 years
- If conviction length is 4 years or over: never spent"

Add detention calculator

---

app/helpers/application_helper.rb
app/views/application/_step_subsection.html.erb
app/views/steps/conviction/compensation_paid/edit.html.erb
app/views/steps/conviction/compensation_payment_date/edit.html.erb
app/views/steps/conviction/conviction_length/edit.html.erb
app/views/steps/conviction/conviction_length_type/edit.html.erb
app/views/steps/conviction/is_date_known/edit.html.erb
app/views/steps/conviction/known_date/edit.html.erb
config/locales/en/helpers.yml
config/locales/en/results.yml
config/locales/en/shared.yml
features/conviction_discharge.feature
features/step_definitions/common.rb
spec/helpers/application_helper_spec.rb

Identical to what we do with the `step_header` to render the "back" link, in some steps we want to show the conviction subtype as a subsection.
The locales have been reorganised a bit so we can take advantage of shared keys.

 Add subsection to the conviction views

---

app/forms/base_form.rb
app/forms/steps/conviction/conviction_length_type_form.rb
app/forms/value_object_methods.rb
app/services/calculators/youth_rehabilitation_order_calculator.rb
app/services/conviction_decision_tree.rb
app/value_objects/conviction_length_type.rb
config/locales/en/errors.yml
config/locales/en/helpers.yml
config/locales/en/results.yml
spec/forms/base_form_spec.rb
spec/forms/steps/conviction/conviction_length_type_form_spec.rb
spec/services/conviction_decision_tree_spec.rb
spec/value_objects/conviction_length_type_spec.rb

This will jump straight to results, and do not ask for the length.
This radio will only show for `community_order` children convictions.
A bit of refactor in the value-object methods and decision tree.

 Add new radio for `no length given`

---

app/presenters/caution_result_presenter.rb
app/presenters/conviction_result_presenter.rb
app/presenters/results_presenter.rb
app/services/caution_check_result.rb
app/services/conviction_check_result.rb
spec/presenters/caution_result_presenter_spec.rb
spec/presenters/conviction_result_presenter_spec.rb
spec/services/caution_check_result_spec.rb
spec/services/conviction_check_result_spec.rb

In the presenters we had a `#calculator_class` method that wasn't really returning the (new) calculator classes introduced in the ConvictionType.
This was done before the calculators were introduced.
I've renamed this method and also the associated classes to not have the wording 'Calculator' in them.

Rename some classes to avoid confusion

---

app/views/errors/invalid_session.html.erb
app/views/errors/not_found.html.erb
app/views/errors/unhandled.html.erb
app/views/layouts/_sentry_feedback.html.erb
config/locales/en/errors.yml

Although the copy will probably change , at least we have something to show and this will stop the stack trace showing in the browser.
Also, in parallel sentry will be setup to start accepting exceptions from this service.

Add content to error pages

---

app/helpers/conviction_helper.rb
app/services/calculators/detention_calculator.rb
app/views/steps/check/results/_conviction.en.html.erb
config/locales/en/results.yml
spec/helpers/conviction_helper_spec.rb
spec/services/calculators/detention_calculator_spec.rb

Update the conviction result page to return the correct title and statement in the right tense.
Copy can be [found here](https://docs.google.com/spreadsheets/d/1ZSCk-wgMfIc22GQahKH_ys4u-E9GWIn6dQ7mm5t1RFI/edit#gid=0)

update conviction result page

---

package.json
yarn.lock

According to the changelog there are no breaking changes and just fixes to existing classes or new functionality for use with Nunjucks.
https://github.com/alphagov/govuk-frontend/releases

Bump `govuk-frontend` version

---

README.md
app/views/about/cookies.en.html.erb
app/views/home/index.en.html.erb
config/i18n-tasks.yml
config/locales/en.yml
config/locales/en/date.yml
config/locales/en/home.yml
config/locales/en/service.yml
config/locales/en/warning.yml
features/caution.feature
features/conviction.feature
features/step_definitions/common.rb
spec/helpers/application_helper_spec.rb

The name of the service has changed.
I've done a bit of reorg in the locales, so we don't have many 1 string files.
Also removed the `home` page_title locale as it is not used.
Note: fixed as part of this PR, although unrelated, the cookies page as it was missing a closing div.

Rename service and reorg locales

---

app/views/home/index.en.html.erb

Update the copy and layout of the service home page, according to latest version of the prototype.
Note some links are to the glitch guidance prototype, until the guidance is published on GOV.UK pages.

Update home page

---

app/forms/steps/caution/caution_type_form.rb
spec/forms/steps/caution/caution_type_form_spec.rb

If CautionTypeForm changes with regards to the database (for example, if user advance but then go back and change their answers) we need to ensure some dependent attributes down the line are also reset, to avoid inconsistencies in the decision trees or result page.
This is easily done returning early from the `#persist!` method if there are no changes in the form.
I will do a similar thing with convictions in a separate PR.
Note: unrelated, but I removed the safe navigation operator in the `#under_age?`, ensuring we do the validations if we have a `disclosure_check`.

Reset `caution_type` dependent attributes

---

app/forms/steps/caution/conditional_end_date_form.rb
config/locales/en/errors.yml
spec/forms/steps/caution/conditional_end_date_form_spec.rb

Return an error message when conditional end date is before caution date i.e  
caution date: 1/7/2019 and when conditional end date: 1/7/2018

Validate that conditional end date is after caution date

---

app/forms/steps/check/kind_form.rb
app/forms/steps/conviction/conviction_type_form.rb
config/locales/en/helpers.yml
config/locales/en/results.yml
features/caution.feature
spec/forms/steps/check/kind_form_spec.rb
spec/forms/steps/conviction/conviction_type_form_spec.rb

Same as with previous PR #112.
Only resetting the most inmediate attributes and not all of them, because each form should take care of resetting the following ones, if needed.
Also I fixed a capitalisation typo in the locales.

Reset `kind` and `conviction_type` dependent attributes

---

app/views/about/cookies.en.html.erb
app/views/warning/reset_session.html.erb

In the reset session warning, and in the cookie pages. Mainly removing references to C100 and/or application, and replacing with "check".
The cookies page copy is still provisional but based on other services so pretty standard, should not be that many changes.

Fix some styling and copy issues

---

app/controllers/steps/conviction/compensation_not_paid_controller.rb
app/services/conviction_decision_tree.rb
app/views/steps/check/exit_over18/show.en.html.erb
app/views/steps/conviction/compensation_not_paid/show.en.html.erb
config/routes.rb
features/conviction_financial.feature
spec/controllers/steps/conviction/compensation_not_paid_controller_spec.rb
spec/services/conviction_decision_tree_spec.rb

This exit page was missing, temporarily pointing to the under18 page.
Also, added the back link to the under18 exit page.

Add compensation not paid exit page

---

app/presenters/caution_result_presenter.rb
config/locales/en/results.yml
spec/factories/disclosure_check.rb
spec/presenters/caution_result_presenter_spec.rb
spec/services/caution_check_result_spec.rb

The results of the conditional caution didn't include the conditional end date.
Also, updated the order of the question-answer pairs to match prototype.
TODO: the output date should be localised to follow the usual ISO 8601 format. This might require a refactor of the presenters.

Update caution results page

---

app/value_objects/conviction_type.rb
cucumber.yml
features/armed_forces.feature
spec/forms/steps/conviction/conviction_type_form_spec.rb
spec/value_objects/conviction_type_spec.rb

We will not have these for MVP, but as we've done most of the work and we will eventually need them, instead of removing everything let's just hide the parent group.
This mechanism can also be used in the future to show/hide any other convictions if needed.
Added a default cucumber profile that skips scenarios tagged as `@skip`.

Hide armed forces convictions

---

app/presenters/conviction_result_presenter.rb
config/locales/en/results.yml
spec/presenters/conviction_result_presenter_spec.rb

Add  compensation_payment_date to conviction result table

Add compensation_payment_date to conviction result table

---

app/presenters/question_answer_row.rb
config/locales/en.yml
spec/factories/disclosure_check.rb
spec/presenters/caution_result_presenter_spec.rb
spec/presenters/question_answer_row_spec.rb

This will format the user-provided dates following ISO 8601.
Before: `2018-12-01`
Now: `01/12/2018`
Updated the factory to produce predictable dates to simplify and avoid flaky tests.

Format result page dates

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/local/custom.scss
app/assets/stylesheets/local/panels.scss
app/helpers/result_helper.rb
app/views/steps/check/results/show.en.html.erb
config/locales/en.yml
config/locales/en/results.yml
features/caution.feature

* Removed the `back` link, as it has no effect on the results page (the user can't go back to a completed check).
* Removed the leading zeros in the day in the long date.
* Made some elements `nowrap`.
Note: `local/panels.scss` was not being used, so I renamed it to `custom` and added the nowrap style there.
Before:
After:

Styling fixes in the results page

---

app/forms/steps/conviction/conviction_subtype_form.rb
spec/forms/steps/conviction/conviction_subtype_form_spec.rb

This attribute also needs to be reset, as we do in cautions, when the conviction subtype changes.

Reset conviction `known_date`

---

app/models/disclosure_check.rb
config/application.rb
lib/tasks/daily_tasks.rake
spec/models/disclosure_check_spec.rb
worker.sh

This will run daily through a cronjob pod, and will purge old checks so the database doesn't grow unnecessarily with stale data.

Add daily maintenance rake task

---

app/views/steps/conviction/compensation_payment_date/edit.html.erb
config/locales/en/caution.yml
config/locales/en/conviction.yml
config/locales/en/helpers.yml

* Updated the hint text for the conviction `known_date` step.
* Removed unused locales
* Update the `compensation_payment_date` step to have lead text (thus we can't continue using page_heading).

Update date steps copy and hints

---

app/presenters/caution_result_presenter.rb
app/presenters/conviction_result_presenter.rb
app/presenters/results_presenter.rb
config/locales/en/results.yml
spec/presenters/caution_result_presenter_spec.rb
spec/presenters/conviction_result_presenter_spec.rb

The conviction length is split into two bits of information, the actual length (a number) and the metric (weeks, months, years or `no_length`).
Previously we had these separate in the summary table in the results page, but as part of the service review, it was decided to combine it into one line, if possible.
We do this by extending the functionality of the presenters, to be able to override the value of an attribute and use a custom method to build the one-liner.
Also, I've removed the individual test of the `#question_attributes` method, because it is tested more in-deep in the `describe '#summary'`, so it was redundant. This method is now private.
Before:
After:
When no date was given:

Combine conviction length details in results page

---

README.md
config/locales/en/helpers.yml

Adding some hint texts.
Unrelated, but removed `conviction_hospital_guardianship_order.feature` from the README, as we don't have this anymore, and simplified a bit this section so we don't have to remember to maintain it when we add/remove features.

Copy amendments in YRO orders

---

config/environments/production.rb

We are already using Logstash, with log level of `:info` but this extra code, was making the production logs also output the SQL queries (debug).
We don't need this, as it is very verbose.

Disable SQL logs in production

---

Dockerfile.nginx
config/nginx.conf
docker-compose.yml

In order to replicate as much as possible the setup we have on kubernetes, where we can't run root containers, we are going to change the nginx image to the `bitnami` one and adapt the config so it works.
A similar approach to this, will be needed in our staging kubernetes environment.

Use a non-root nginx container

---

Dockerfile.nginx
config/nginx.conf

This way we don't need to fix permissions, and is the same approach we use on kubernetes.

Simplify nginx config (docker-compose only)

---

app/helpers/application_helper.rb
app/views/layouts/_analytics.html.erb
app/views/steps/check/exit_over18/show.en.html.erb
app/views/steps/check/results/_caution.en.html.erb
app/views/steps/check/results/_conviction.en.html.erb
app/views/steps/conviction/compensation_not_paid/show.en.html.erb
spec/helpers/application_helper_spec.rb

Goals will only track 1 event per session, so for example a user checking several cautions or convictions one after another, would only track as 1 completed check, the first one, even if they did 10 different checks.
This implementation was created for another service in the past with good results:
https://github.com/ministryofjustice/tax-tribunals-datacapture/pull/547
Some small changes to cater to this service.

Enable GA ecommerce transaction tracking

---

app/views/about/terms_and_conditions.en.html.erb
app/views/errors/check_completed.html.erb
app/views/steps/check/exit_over18/show.en.html.erb
config/locales/en/results.yml

* Add the missing `govuk-link` class to some links.
* Add `rel="external"` to the external links so these are tracked as outbound on GA.

Add missing attributes to a few links

---

app/views/about/cookies.en.html.erb

The sections header size were inconsistent and, in the table, some classes were wrong or missing.
Added the link to opt-out of GA.

Fix markup and styling of cookies page

---

app/helpers/analytics_helper.rb
app/helpers/application_helper.rb
app/views/steps/check/results/_caution.en.html.erb
app/views/steps/check/results/_conviction.en.html.erb
app/views/steps/check/results/show.en.html.erb
config/locales/en/results.yml
spec/helpers/analytics_helper_spec.rb
spec/helpers/application_helper_spec.rb

Add to the completed transaction an extra bit of information whether the caution or the conviction is spent (yes/no values).
This is done with custom dimensions.
A bit of refactor and moving code related to GA to a separate helper `analytics_helper.rb`
Removed the unused method `#display_result`
Fixed the results page title.

Add GA custom dimension (spent)

---

app/controllers/concerns/bypass_under_age.rb
app/controllers/experiments_controller.rb
app/controllers/steps/caution/under_age_controller.rb
app/controllers/steps/conviction/under_age_controller.rb
app/helpers/application_helper.rb
app/services/base_decision_tree.rb
app/services/caution_decision_tree.rb
app/services/conviction_decision_tree.rb
config/routes.rb
spec/helpers/application_helper_spec.rb
spec/services/caution_decision_tree_spec.rb
spec/services/conviction_decision_tree_spec.rb

This is a simple mechanism to drop a cookie (or delete the cookie) so the adults journey can be enabled, while undergoing development/test, without affecting users accessing the service.

 Add feature-flag mechanism for adults journey

---

app/forms/steps/caution/caution_type_form.rb
app/forms/steps/conviction/conviction_type_form.rb
app/value_objects/conviction_type.rb
app/views/steps/conviction/conviction_type/edit.html.erb
config/locales/en/helpers.yml
config/locales/en/results.yml
spec/forms/steps/conviction/conviction_type_form_spec.rb
spec/value_objects/conviction_type_spec.rb

Some changes to the form object, in the same way we did for cautions.
Separate parent types for youth and adults in the value object.
In essence, all new parent types, and their children, must have different names (even if they are identical to the youth ones) so we can customise the copy, they can have different calculators, and they track differently in GA, etc.

Prepare conviction types for adults

---

app/services/calculators/addition_calculator.rb
app/value_objects/conviction_type.rb
config/locales/en/helpers.yml
config/locales/en/results.yml
features/adults/prevention_and_reparation_order.feature
spec/services/calculators/addition_calculator_spec.rb
spec/value_objects/conviction_type_spec.rb

Create adult prevention and reparation orders convictions journey with the following
- add prevention and reparation orders conviction type
- add prevention and reparation orders conviction sub types
- add plus twelve months calculator
- add adult prevention and reparation order convictions feature

Add adult Prevention and reparation orders convictions journey

---

app/helpers/analytics_helper.rb
app/views/steps/check/results/shared/_feedback.en.html.erb
app/views/steps/check/results/show.en.html.erb
config/application.rb
spec/helpers/analytics_helper_spec.rb

We now have the "real" surveys.
Add the end of service embedded survey (like we did in C100) and update the link in the phase banner.
Ensure we propagate `check=unknown` to the survey if we don't have a current_disclosure_check record, or we have it, but it doesn't have the `kind` attribute yet.

Add embedded survey and update phase link

---

app/forms/steps/caution/caution_type_form.rb
app/value_objects/caution_type.rb
config/locales/en/helpers.yml
config/locales/en/results.yml
spec/forms/steps/caution/caution_type_form_spec.rb
spec/services/caution_decision_tree_spec.rb
spec/value_objects/caution_type_spec.rb

To make these consistent with the adult convictions, we are going to rename the adult cautions value-objects, previously `simple_caution` and `conditional_caution`, to be prefixed with `adult`
Updated the spec to test more thoroughly.

Rename adult cautions for consistency

---

config/locales/en/helpers.yml

There was a duplication in the input label and in the hint.
Remove the hint text as it is redundant.
Before:
After:

Remove superfluous hint text

---

app/forms/steps/conviction/conviction_length_form.rb
config/locales/en/errors.yml
spec/forms/steps/conviction/conviction_length_form_spec.rb

Change conviction_length attribute from Integer to string as it was bypassing only_integer validation.
i.e before the user entered `1.5` it was casting the user string to an integer `1` and would bypass validation.

Stop conviction_length_form from accepting a non-integer number

---

app/value_objects/conviction_type.rb
config/locales/en/helpers.yml
config/locales/en/results.yml
spec/services/conviction_length_choices_spec.rb
spec/value_objects/conviction_type_spec.rb

For now this is empty until we start moving or adding convictions into this category.
Note: pending hint text copy. Will be added when we know it.

Add youth `Prevention and reparation orders` category

---

app/value_objects/conviction_type.rb
config/locales/en/helpers.yml
config/locales/en/results.yml
features/youth/conviction_youth_rehabilitation_order.feature
spec/forms/steps/conviction/conviction_length_type_form_spec.rb
spec/forms/steps/conviction/conviction_subtype_form_spec.rb
spec/value_objects/conviction_type_spec.rb

This is now named `youth rehabilitation order` but follows same rules and calculation as `unpaid work` and remains in same category.

Rename `unpaid work`

---

app/presenters/conviction_result_presenter.rb
app/presenters/results_presenter.rb
app/views/steps/check/results/_caution.en.html.erb
app/views/steps/check/results/_conviction.en.html.erb
app/views/steps/check/results/shared/_panel.html.erb
app/views/steps/check/results/show.en.html.erb
features/youth/conviction_custodial_sentence.feature
features/youth/conviction_financial.feature
spec/presenters/caution_result_presenter_spec.rb
spec/presenters/conviction_result_presenter_spec.rb

Only for custodial sentences (youth and adults).
A bit of refactor to make this more DRY and to prepare for the possibility of having to add more bits of information depending on the caution or conviction type, etc.

Add callout in results page

---

app/views/steps/conviction/conviction_length/edit.html.erb

So mobile devices automatically show the number pad, and to also do an early validation at browser level.
This is already added automatically to the date elements so no need to do the same there.

Add type number and pattern to input text

---

app/services/base_calculator.rb
spec/services/base_calculator_spec.rb
spec/services/calculators/conditional_caution_calculator_spec.rb
spec/services/calculators/detention_calculator_spec.rb
spec/services/calculators/prison_sentence_calculator_spec.rb

Fix how the difference between two dates is calculated in months.
For example:
before 29/4/2004 to 28/5/2005 would return 3 months,  now the method will return 2 months
before 1/1/2019 to 31/1/2019 would return 1 month, now  the method will return 0 months

update length_in_months method

---

app/forms/steps/conviction/conviction_length_form.rb
app/services/calculators/sentence_calculator.rb
app/validators/sentence_length_validator.rb
app/value_objects/conviction_type.rb
config/locales/en/errors.yml
spec/factories/disclosure_check.rb
spec/forms/steps/conviction/conviction_length_form_spec.rb
spec/value_objects/conviction_type_spec.rb

This affected DTO and suspended prison convictions.
These can only go up to a maximum sentence length (24 months currently) and, if over, the user will receive a validation error (same kind of validation as when they enter a non numeric value, etc.)

Add sentence length validation

---

app/services/base_calculator.rb
app/services/calculators/conditional_caution_calculator.rb
app/services/calculators/sentence_calculator.rb
spec/services/base_calculator_spec.rb

As conviction length is given in several different format (weeks, months, years) we need to convert the different types of lengths into months i.e
- weeks to months = length * (52/12)
- years to month = length * 12
- months just return the length

Calculate conviction length in months

---

app/views/about/terms_and_conditions.en.html.erb
app/views/home/index.en.html.erb

Update start page and term and conditions copy 
The reason for doing the start page and t&c copy in one pull request because start page was linking to a new section in the t&c page.

update start page and t&c copy

---

config/locales/en/helpers.yml
features/youth/conviction_custodial_sentence.feature

Instead of `When were you given ...` for these orders we change this step header to read `When did the xxxx start?`

Amend custodial and hospital headers

---

app/views/about/terms_and_conditions.en.html.erb
app/views/home/index.en.html.erb

Need to change "how to use the guidance this service gives you" bullet to:
"how to use the information this service gives you"
(and same change to header in T&Cs).
Start page change
T&C change

update start page copy

---

config/locales/en/helpers.yml

And make sure the 'example' do not wrap if it doesn't fully fit in one line.

Amend known date hint text

---

app/value_objects/conviction_type.rb
config/locales/en/helpers.yml
config/locales/en/results.yml
features/adults/prevention_reparation.feature
features/youth/conviction_prevention_reparation.feature
spec/value_objects/conviction_type_spec.rb

Just an internal renaming, for consistency and to avoid confusion, not affecting user interface.
The previous name apart from being too long, gave the impression it was an order in itself, instead of a "group" of orders, or category (the `and` was changed to `or` in the user interface as per PR #197).

Improve prevention/reparation value-object naming

---

Gemfile.lock

Bump nokogiri from 1.10.3 to [1.10.4](https://github.com/sparklemotion/nokogiri/blob/master/CHANGELOG.md)

Bump nokogiri from 1.10.3 to 1.10.4 

---

app/value_objects/conviction_type.rb
config/locales/en/helpers.yml
config/locales/en/results.yml
features/adults/conviction_custodial_sentence.feature
features/adults/conviction_military.feature
features/adults/conviction_motoring.feature
spec/value_objects/conviction_type_spec.rb

You can find the pivotal ticket [here](https://www.pivotaltracker.com/n/projects/2311302/stories/167849617)
CONVICTION TYPES changes 
```
Military [can delete 'convictions']
For example, a dismissal or service detention
Custody or hospital order [will need to be moved to alpha order]
For example, a prison sentence or a hospital order given under the Mental Health Act
Motoring
For example, penalty points or a driving ban
```
Adult military conviction sub type no hint text
Change the order of adult custodial sentence sub type to alpha and update hint text
```
Hospital order
You were given a hospital order instead of a prison sentence because of mental health concerns
Prison sentence
You were sent to prison (also known as being taken into custody)
Suspended prison sentence
You were given a …
```

Update adult copy

---

config/locales/en/helpers.yml
config/locales/en/results.yml
spec/i18n_spec.rb

It was easy to change some copy in one place and miss another place.
With these simple tests we will have at least an early warning to ensure we don't forget to update the locales in all the right places.

Add a few i18n sanity check tests

---

Dockerfile
README.md
app/assets/javascripts/application.js
app/assets/stylesheets/application.scss
app/views/home/index.en.html.erb
app/views/layouts/application.html.erb
app/views/layouts/govuk_template.html.erb
app/views/steps/caution/conditional_end_date/edit.html.erb
features/adults/community_order.feature
lib/govuk_components/error_helpers.rb
package.json
spec/fixtures/files/error_summary.html
yarn.lock

Individual commits for easier review.
Bump the version of the `govuk-frontend` modules to the latest one (**v3.0.0**)
There are some breaking changes (mainly in the paths), that we had to update, and also some markup changes or improvements, as per Changelog here:
https://github.com/alphagov/govuk-frontend/releases/tag/v3.0.0
Most of the changes (at least the breaking ones) are implemented as part of this PR but there are other markup refinements that will be incorporated as separate PRs, as well as we are aware the contrast in a link in the results page is not great and will be changed once we have a decision from the content designer.

Use govuk-frontend v3.0.0

---

app/assets/javascripts/modules/ga-events.js
app/helpers/application_helper.rb
app/views/errors/check_completed.html.erb
app/views/errors/invalid_session.html.erb
app/views/errors/not_found.html.erb
app/views/errors/unhandled.html.erb
app/views/home/index.en.html.erb
app/views/steps/check/results/shared/_feedback.en.html.erb
app/views/steps/check/results/shared/_summary.en.html.erb
app/views/warning/reset_session.html.erb
config/locales/en.yml
config/locales/en/errors.yml
config/locales/en/helpers.yml
features/step_definitions/common.rb
lib/govuk_components/form_builder.rb
spec/helpers/application_helper_spec.rb
spec/lib/govuk_components/form_builder_spec.rb

Individual commits for easier review.
Some of the markup was old, from a time before the new design system.
Other was just oversights.
I've updated most of what I could find, mainly around links and buttons. Also I've done a big cleanup of unused GA javascript (most of it a copy of the C100) as we don't have or track the kind of HTML elements we were tracking on C100.

Update and improve some markup

---

Gemfile
Gemfile.lock
app/assets/javascripts/modules/ga-events.js
app/views/steps/conviction/conviction_length/edit.html.erb

The recommended way to use the numeric inputs is to be of type `text` but with pattern and inputmode attributes.
The dates gem has been updated to produce this new markup [0] following the reports of issues with previous markup [1].
Also updated the `conviction_length` step to produce an input of type `text`, instead of number, and add the `inputmode` attribute.
[0] https://github.com/ministryofjustice/gov_uk_date_fields/releases/tag/v4.1.0
[1] https://github.com/alphagov/govuk-frontend/issues/1449

Bump to `gov_uk_date_fields` gem (inputmode)

---

app/views/steps/caution/conditional_end_date/edit.html.erb
app/views/steps/caution/known_date/edit.html.erb
app/views/steps/conviction/compensation_payment_date/edit.html.erb
app/views/steps/conviction/known_date/edit.html.erb
app/views/steps/shared/_unknown_date_details.html.erb
config/locales/en.yml
config/locales/en/caution.yml

Add a `<details>` block to all date steps we have in the application, to explain more about it.
All are the same, except for conditional caution, where the copy is slighly different.
As we are reusing the same markup, it has been extracted to a partial that can be passed a few variables.

Add details to date steps

---

config/locales/en/helpers.yml

Sentence calculation policy team requested that this word be changed.

Changed 'convicted' to 'sentenced' in hint text

---

package.json
yarn.lock

Update to latest published govuk-frontend version.
No breaking changes.

Bump govuk-frontend to version 3.1.0

---

config/locales/en/conviction.yml

Add a callout to:
- over-18s prison
- over-18s suspended prison
- under-18s detention
The under-18s DTO doesn’t need the callout (as the sentence can’t be extended) but needs everything else.

Add callout to sentence length page

---

app/controllers/application_controller.rb
app/controllers/concerns/security_handling.rb

Enable basic access authentication on the present of environment variable  `HTTP_AUTH_ENABLED`
Only can be enable for controllers which inherit from `application_controller.rb` i.e it won't be enable for StatusController action like ping etc.

Add basic http auth

---

app/controllers/concerns/security_handling.rb
app/controllers/steps/mvp/info_controller.rb
app/models/participant.rb
spec/models/participant_spec.rb

As we are removing the opt-in/opt-out mechanism from the landing page (and we might even end up removing the landing page completely) we need another way to track which participants are using the MVP.
We can do this with the unique set of http auth credentials as these reference individual YOTs.

Use the http auth to track MVP visits

---

app/controllers/concerns/security_handling.rb
app/helpers/analytics_helper.rb
app/views/layouts/_analytics.html.erb
spec/helpers/analytics_helper_spec.rb

At least during the pilot, we will need a way of measuring success and we will need to know how many checks have been completed per YOT.
This will link together the analytics belonging to each YOT so it is easier to evaluate the metrics we get.
There is no personal identification involved.

Enable GA userId for MVP pilot

---

app/services/calculators/sentence_calculator.rb
spec/services/calculators/sentence_calculator_spec.rb

For empale:   If you get convicted  of `Detention`  as under 18  for 1 month on 5 Feb 2017.  
The spent date of your conviction should be 4 September 2018
Perviously it was 6 September 2018.  
How a spent date is worked out for any custody sentence:
A = Conviction date 
B = Length of conviction
C = Rehabilitation period 
**Conviction end date**  = (A + B) - 1 day    
i.e  `5/2/2017 + 1 calendar month = 5/3/2017 - 1 day  = 4/3/2017 `
**Spent date** = Conviction end date + C
i.e `4/3/2017 + 18 calendar months = 4/9/2019

update sentence calculator base on legal advice

---

config/participants.yml
lib/tasks/tools.rake

* Defaults to 1 generated references, down from 10.
* Added more documentation and outputs the SHA directly.

Improve the generation of participant references

---

app/value_objects/conviction_type.rb
config/locales/en/helpers.yml
config/locales/en/results.yml
features/adults/conviction_motoring.feature
spec/services/conviction_length_choices_spec.rb
spec/value_objects/conviction_type_spec.rb

Update adult motoring conviction subtypes to the following:
- Disqualification
- Fine
- Fixed penalty notice (FPN)
- Penalty points

Update adult motoring conviction subtypes

---

app/controllers/steps/conviction/motoring_endorsement_controller.rb
app/forms/steps/conviction/motoring_endorsement_form.rb
app/views/steps/conviction/motoring_endorsement/edit.html.erb
config/locales/en/conviction.yml
config/locales/en/helpers.yml
config/routes.rb
db/migrate/20190926082054_add_motoring_endorsement_to_disclosure_check.rb
db/schema.rb
spec/controllers/steps/conviction/motoring_endorsement_controller_spec.rb
spec/forms/steps/conviction/motoring_endorsement_form_spec.rb

- Add basic yes/no question step
- Add motoring_endorsement column.
- Please note i haven't plumbed this step into the overall motoring journey, this will be done in the next PR.

Add motoring endorsement step

---

app/decorators/conviction_decorator.rb
app/presenters/conviction_result_presenter.rb
app/value_objects/conviction_type.rb
app/value_objects/value_object.rb
app/views/steps/check/results/show.en.html+conviction_spent.erb
spec/decorators/conviction_decorator_spec.rb
spec/presenters/conviction_result_presenter_spec.rb
spec/value_objects/conviction_type_spec.rb
spec/value_objects/value_object_spec.rb

The `ConvictionType` value-object was getting too big and it might grow further with motoring convictions.
A new module, that is included in the value object, named `ConvictionDecorator` will group together some of these utility and query methods to reduce complexity when testing and also avoid having more attributes than neccessary (we still maintain `skip_length` because this one is used by a lot of different convictions, not just 2 like compensation).
Also, added to the superclass `ValueObject` an `inquiry` method to simplify doing things like checking if a conviction is of a specific type or not.
So for example, it is now possible to do this (might be useful for decision trees):
```ruby
c = ConvictionType::ADULT_MOTORING_FINE
c.inquiry.foobar?
=> false
c.inquiry.adult_motoring_fine? …
```

Refactor some conviction methods into decorator

---

app/controllers/steps/conviction/motoring_disqualification_end_date_controller.rb
app/forms/steps/conviction/motoring_disqualification_end_date_form.rb
app/views/steps/conviction/motoring_disqualification_end_date/edit.html.erb
config/locales/en/conviction.yml
config/locales/en/errors.yml
config/locales/en/helpers.yml
config/routes.rb
db/migrate/20190926135912_add_motoring_disqualification_end_date_to_disclosure_check.rb
db/schema.rb
spec/controllers/steps/conviction/motoring_disqualification_end_date_controller_spec.rb
spec/forms/steps/conviction/motoring_disqualification_end_date_form_spec.rb

- Add basic date question step
- Add motoring_endorsement_end_date column.
- Please note i haven't plumbed this step into the overall motoring journey, this will be done in the next PR.

Motor disqualification end date step

---

app/services/conviction_decision_tree.rb
features/adults/conviction_motoring.feature
spec/services/conviction_decision_tree_spec.rb

Update adult motoring journey to do the following
- display motoring disqualification end date step after `known_date` step when `conviction_type `is `adult_disqualification`
- display result page on submitting `motoring_disqualification_end_date`

Update adult motoring journey - Add disqualification end date step

---

app/controllers/steps/conviction/motoring_lifetime_ban_controller.rb
app/forms/steps/conviction/motoring_lifetime_ban_form.rb
app/views/steps/conviction/motoring_lifetime_ban/edit.html.erb
config/locales/en/conviction.yml
config/locales/en/helpers.yml
config/routes.rb
db/migrate/20190926082054_add_motoring_endorsement_to_disclosure_check.rb
db/migrate/20190930094336_add_motoring_lifetime_ban_to_disclosure_check.rb
db/schema.rb
spec/controllers/steps/conviction/motoring_lifetime_ban_controller_spec.rb
spec/forms/steps/conviction/motoring_lifetime_ban_form_spec.rb

- Add basic yes/no question step
- Add motoring_lifetime_ban column.
- Please note i haven't plumbed this step into the overall motoring journey, this will be done in the next PR.

Add motoring lifetime ban step

---

app/services/conviction_decision_tree.rb
config/locales/en/helpers.yml
features/adults/conviction_motoring.feature
spec/services/conviction_decision_tree_spec.rb

Update adult motoring journey to do the following
- display lifetime ban step after conviction_sub type step when conviction_subtype is adult_disqualification
- display result page on submitting  `yes` to lifetime ban 
- display motoring_endorsement step  on submitting  `no` to lifetime ban 
- update feature tests

Update adult motoring journey - Add motoring lifetime ban step

---

app/services/calculators/motoring_calculator.rb
app/value_objects/conviction_type.rb
spec/services/calculators/motoring_calculator_spec.rb
spec/value_objects/conviction_type_spec.rb

Update motoring calculator with the new rules from policy:
- disqualification conviction has got the following rules:
-  If a lifetime ban was given   = `never spent`
- disqualification with endorsement 
- If (end_date - start_date) is less than or equal to 5 years =  `start_date + 5 years`
- If (end_date - start_date) is greater than 5 years =  `end_date`
- disqualification without  endorsement = `end date`
- Motoring penalty notice conviction has got the following rules:
- Penalty notice with endorsement  =  `start_date + 5 years`
- Penalty notice without endorsement = `no conviction`
- Motoring fine conviction has got the following rules:
- Motoring fine with endorsement  =  `start_date + 5 years`
- Motoring fine without endorsement = `start_date + 1 year`
- Motoring penalty points …

Update adult motoring calculators

---

app/forms/steps/conviction/motoring_disqualification_end_date_form.rb
app/services/calculators/motoring_calculator.rb
config/locales/en/helpers.yml
spec/forms/steps/conviction/motoring_disqualification_end_date_form_spec.rb
spec/services/calculators/motoring_calculator_spec.rb
spec/support/form_validation_shared_examples.rb

Allow a user not to enter a date in the motoring disqualification end date step if they don't have an end date.

Allow no end date for motoring disqualification

---

app/forms/steps/caution/conditional_end_date_form.rb
app/forms/steps/caution/known_date_form.rb
app/forms/steps/conviction/compensation_payment_date_form.rb
app/forms/steps/conviction/known_date_form.rb
app/forms/steps/conviction/motoring_disqualification_end_date_form.rb
config/locales/en/errors.yml

Remove 'invalid date' error message coming from gov_uk_date_fields gem.
Update blank message to combine empty date and incorrect formatted date into one error message

Disclosure checker date field error messages

---

app/validators/sensible_date_validator.rb
spec/support/form_validation_shared_examples.rb

When a user only enters day and month they currently get  the following error message:
`The date of the conviction is not valid`
They should get the following error message
`Enter the date of the conviction in the format dd/mm/yyyy`
This is because if you enter day: 1,  month : 2  and leave year blank.
you get the following date 
`(byebug) value`
`Sun, 01 Feb 0000`
`(byebug) value.is_a?(Date)`
`true`
I have added a small check to make sure the year is greater than 0

Return a blank date error if the year is not greater than 0

---

app/views/steps/check/results/shared/_guidance.en.html.erb
app/views/steps/check/results/show.en.html+caution_not_spent.erb
app/views/steps/check/results/show.en.html+caution_spent.erb
app/views/steps/check/results/show.en.html+conviction_never_spent.erb
app/views/steps/check/results/show.en.html+conviction_not_spent.erb
app/views/steps/check/results/show.en.html+conviction_spent.erb

Move disclaimer callout  to partial.
Update the following templates:
- show.en.html+conviction_never_spent.erb
- show.en.html+caution_spent.erb
- show.en.html+caution_not_spent.erb
- show.en.html+conviction_spent.erb
- show.en.html+conviction_not_spent.erb
For more details  see PR #[258](https://github.com/ministryofjustice/disclosure-checker/pull/258)

Update result page content - change call about guidance only

---

app/models/application_record.rb
app/models/check_group.rb
app/models/disclosure_check.rb
app/models/disclosure_report.rb
app/models/participant.rb
db/migrate/20191016114935_create_disclosure_report.rb
db/migrate/20191016120112_create_check_group.rb
db/migrate/20191016121824_add_check_group_to_disclosure_checks.rb
db/schema.rb
spec/models/disclosure_report_spec.rb

In preparation for multiple convictions, we need new data models to hold the structured data.
Individual commits for clarity.
Basically, added 2 new models: `CheckGroup` and `DisclosureReport` and updated existing `DisclosureCheck`.

Add new data models for multiple convictions

---

app/controllers/steps/check/check_your_answers_controller.rb
app/views/steps/check/check_your_answers/show.html.erb
config/locales/en/check.yml
config/routes.rb
spec/controllers/steps/check/check_your_answers_controller_spec.rb

Add a basic check your answer page, reusing `ResultsPresenter` to display question and answer.

Add check your answer page

---

app/controllers/application_controller.rb
app/controllers/checks_controller.rb
app/models/disclosure_check.rb
config/routes.rb
db/migrate/20191017102652_remove_check_group_unique_constraint.rb
db/schema.rb
spec/controllers/checks_controller_spec.rb

The controller will handle creating new checks belonging to an existing group (existing proceedings) or a new group (new proceedings). Will be hooked to the CYA page in following PRs.
If the check belongs to an existing group, we default to kind `conviction` (as only convictions can be added to proceedings) and redirect to the under age path.
If the check is for a new group, it can be a conviction or a caution so we redirect to the `kind` path instead as we can't assume the kind.
Exposed a new helper method to get the current `DisclosureReport` which can be used in the CYA too when iterating through the different groups (proceedings).

Add basic actions to add new checks

---

app/controllers/experiments_controller.rb
app/controllers/steps/check/results_controller.rb
app/views/steps/check/check_your_answers/show.html.erb
config/locales/en/helpers.yml
config/routes.rb
spec/controllers/steps/check/results_controller_spec.rb

Add feature-flag to enable/disable multiple journeys
Display check your answers page if the multiples feature flag is enable and show_results parameter isn't set.
Add a button on check your answer page to go to result page.

Add feature-flag to enable/disable multiple journeys

---

app/controllers/application_controller.rb
app/controllers/steps/check/check_your_answers_controller.rb
app/controllers/steps/check/results_controller.rb
app/controllers/steps/check/under_age_controller.rb
app/controllers/steps/conviction/conviction_type_controller.rb
app/helpers/experiments_helper.rb
app/views/steps/check/check_your_answers/show.html.erb
spec/controllers/steps/check/check_your_answers_controller_spec.rb
spec/controllers/steps/check/results_controller_spec.rb

Also, remove back link and include the `CompletionStep` module.
As part of another commit, as we grow the number of feature flag, reorganised the methods to have all of them together.

Add button to create new check

---

app/controllers/concerns/completion_step.rb
app/controllers/steps/check/check_your_answers_controller.rb
app/controllers/steps/check/results_controller.rb
app/services/base_decision_tree.rb
spec/controllers/steps/check/check_your_answers_controller_spec.rb
spec/services/caution_decision_tree_spec.rb
spec/services/conviction_decision_tree_spec.rb
spec/support/matchers/decision_tree_matcher.rb
spec/support/step_controller_shared_examples.rb

Now we have 2 different completions: one for the individual check (a caution or a conviction) and another for the whole set of checks (one or more) past the CYA page.
In order to be more precise when a check is completed, the action of completing an individual check has been moved to the decision tree who is responsable for knowing when to redirect the user to the results page.
In following PRs we will introduce a proper error handling when an individual check is completed or when the whole report is completed, along with the functionality to cancel an "in-progress" check.

Refactor completion mechanism

---

app/controllers/concerns/error_handling.rb
app/controllers/errors_controller.rb
app/controllers/step_controller.rb
app/errors/errors.rb
app/views/errors/report_completed.html.erb
config/locales/en/errors.yml
config/routes.rb
spec/controllers/application_controller_spec.rb
spec/support/step_controller_shared_examples.rb

Same as we had with check completed, we now have a new scenario where a "report" (definition of report being a bunch of cautions and conviction checks) have been completed.
This happens at the very end of the service once the loop over the multiple caution or convictions have been done and the user wants to see the final results.
This should be transparent to a user without the 'multiples' feature flag enabled.
Some copy is still TBD.

Extend error handling to deal with reports

---

app/helpers/application_helper.rb
app/models/disclosure_report.rb
config/locales/en/helpers.yml
lib/govuk_components/form_builder.rb
spec/helpers/application_helper_spec.rb
spec/lib/govuk_components/form_builder_spec.rb
spec/support/view_spec_helpers.rb

After the first check has been completed, following ones will show a 'Go back to check your answers' link below the 'Continue' button.
This, in essence, will take the user to the CYA and leave the check in the session, but still marked as `in-progress`, so the CYA page must cope with this (the presenter must exclude not completed checks).

Show link to go back to check your answers

---

app/controllers/checks_controller.rb
app/controllers/concerns/starting_point_step.rb
spec/controllers/checks_controller_spec.rb
spec/support/step_controller_shared_examples.rb

With the introduction of the CYA page, when adding a new caution or conviction, the back link in the first step will point to the home page, instead of the CYA as it would be expected.
Also, more importantly, if the user clicks this `back` link and loads the home page, the session will be reset.
This is fixed so the `back` link after adding a new caution or conviction takes the user back to the CYA instead of the home page, without overriding any existing navigation stack.

Fix back links after adding new checks

---

app/views/home/index.en.html.erb

Feedback shows users are stumbling with what 'spent' means.
Added a succinct definition to the start page.

Add 'spent' definition to start page

---

app/views/errors/check_completed.html.erb
app/views/errors/report_completed.html.erb
app/views/steps/conviction/compensation_not_paid/show.en.html.erb

If multiples is enabled and we have at least one completed check, we will let the user jump to CYA page if they fall into this kickout page, otherwise they don't have a way out.
Also added a 'start again' button for consistency with other pages. This will reset the session.
Added the `govuk-link--no-visited-state` class to a few other links.

Add link to CYA on compensation not paid

---

app/controllers/checks_controller.rb
spec/controllers/checks_controller_spec.rb

When adding a conviction to an existing proceeding (group), we can skip the 'under_age' question, as all checks inside the same group will have the same age.
We pick the first check in the group and take this age to use it in the new check being initialized.
Also, as a consequence, we redirect to the question after (conviction type).

Default age of new convictions inside a group

---

app/presenters/results_presenter.rb
app/services/calculators/motoring_calculator.rb
app/services/calculators/sentence_calculator.rb
spec/presenters/conviction_result_presenter_spec.rb
spec/services/calculators/motoring_calculator_spec.rb
spec/services/calculators/sentence_calculator_spec.rb

The variant method was a bit confusing.
Made it more explicit by declaring the `:no_record` or `:never_spent` values instead of using booleans.
Also this allow us to have more values in the future, if needed.

Make more explicit the expiry date

---

app/models/check_group.rb
app/models/disclosure_check.rb
app/presenters/check_answers_presenter.rb
app/presenters/check_group_presenter.rb
app/presenters/check_presenter.rb
app/presenters/check_row.rb
app/views/steps/check/check_your_answers/shared/_check.html.erb
app/views/steps/check/check_your_answers/shared/_check_row.html.erb
spec/factories/disclosure_check.rb
spec/presenters/check_answers_presenter_spec.rb
spec/presenters/check_group_presenter_spec.rb
spec/presenters/check_presenter_spec.rb
spec/presenters/check_row_spec.rb

Iterate over the different CheckGroups with completed checks  in the current DisclosureReport, rendering the caution or convictions inside each.

Display checks grouped by check group in CYA page

---

app/controllers/steps/check/check_your_answers_controller.rb
app/controllers/steps/check/results_controller.rb
app/presenters/check_answers_presenter.rb
app/presenters/check_group_presenter.rb
app/views/steps/check/results/show.en.html+multiples.erb
spec/controllers/steps/check/check_your_answers_controller_spec.rb
spec/controllers/steps/check/results_controller_spec.rb
spec/presenters/check_answers_presenter_spec.rb
spec/presenters/check_group_presenter_spec.rb

At the moment just a basic show page, re-using the `CheckAnswersPresenter` to list again all the cautions and convictions.
Next steps, as follow-up PRs, will be to introduce the spent date panels in each of the groups, making use of the `MultipleOffensesCalculator` from PR #281.
Also, adding the remaining copy in the results page as per design.

Show results page for multiple checks

---

app/services/base_multiples_calculator.rb
app/services/calculators/multiples/multiple_offenses_calculator.rb
app/services/calculators/multiples/same_proceedings.rb
app/services/calculators/multiples/separate_proceedings.rb
spec/services/calculators/multiples/multiple_offenses_calculator_spec.rb
spec/services/calculators/multiples/multiple_proceedings_calculator_spec.rb
spec/services/calculators/multiples/same_proceedings_spec.rb
spec/services/calculators/multiples/separate_proceedings_spec.rb

This is a proof of concept, and a preliminary work for what could be the multiples calculator.
It is still WIP and not properly working under all scenarios, but it currently will work for:
- A group of convictions in the same proceedings (any type of conviction, but with the limitation at the moment of at most 1 prison sentence in the group).
- Any number of individual (separate proceedings) cautions (simple or conditional) and, at most, 1 conviction of any type (if there is more than 1 conviction, the calculation will be wrong).
The way to use it (at least initially, as I expect some refactors) is, somewhere in the Results presenter to call:
```ruby
calculator = Calculators::Multiples::MultipleOffensesCalculator.new(disclosure_report)
calculator.process!
```
And then, in each group where …

Preliminary PoC for multiples calculator

---

app/controllers/concerns/completion_step.rb
app/presenters/check_answers_presenter.rb
app/presenters/check_group_presenter.rb
app/presenters/spent_date_panel.rb
app/services/calculators/multiples/multiple_offenses_calculator.rb
app/views/steps/check/check_your_answers/shared/_check.html.erb
app/views/steps/check/results/shared/_spent_date_panel.html.erb
config/locales/en/results.yml
spec/presenters/check_answers_presenter_spec.rb
spec/presenters/check_group_presenter_spec.rb
spec/presenters/spent_date_panel_spec.rb
spec/services/calculators/multiples/multiple_offenses_calculator_spec.rb
spec/support/step_controller_shared_examples.rb

For each of the different groups in the results page, we retrieve the spent date from the `multiple_offenses_calculator` and build little `SpentDatePanel` instances to hold the logic to know what to show in the results page.
Still to do in following PR(s): remaining copy in the results page, specially, the header must be dynamic depending if we have or not spent convictions.

Retrieve the spent date from the calculator

---

app/presenters/check_answers_presenter.rb
app/services/base_multiples_calculator.rb
app/services/calculators/multiples/multiple_offenses_calculator.rb
app/services/calculators/multiples/same_proceedings.rb
app/services/calculators/multiples/separate_proceedings.rb
app/views/steps/check/results/show.en.html+multiples.erb
spec/presenters/check_answers_presenter_spec.rb
spec/services/calculators/multiples/multiple_offenses_calculator_spec.rb
spec/services/calculators/multiples/same_proceedings_spec.rb
spec/services/calculators/multiples/separate_proceedings_spec.rb

Depending on whether there are spent or unspent cautions/convictions.
As a pending refinment, the copy should be singular if there is only a caution or a conviction, and plural when there are multiple cautions and/or convictions.
But this is not priority right now.

Make multiple results header dynamic

---

app/views/steps/check/results/shared/_disclaimer.en.html.erb
app/views/steps/check/results/shared/_guidance.en.html.erb
app/views/steps/check/results/shared/_meaning.en.html.erb
app/views/steps/check/results/shared/_summary.en.html.erb
app/views/steps/check/results/show.en.html+caution_not_spent.erb
app/views/steps/check/results/show.en.html+caution_spent.erb
app/views/steps/check/results/show.en.html+conviction_no_record.erb
app/views/steps/check/results/show.en.html+conviction_not_spent.erb
app/views/steps/check/results/show.en.html+conviction_spent.erb

The different result pages copy:
- [Never spent](https://docs.google.com/document/d/1nTdqYh8PF2tMzNX_4R4-tp9GAZkXSR3kO5dIFIn80Kk/edit)
- [Spent](https://docs.google.com/document/d/1aXBIBiZbLHPG91lJk0123xHy8joIK-uaATZ5vH0KV34/edit)
- [No record](https://docs.google.com/document/d/167HZS72vuGZyl-xtdu1IgG6T6vbhWtB0tVn4y5uDH_4/edit)
- [Not spent](https://docs.google.com/document/d/1Bm3jAea3BmoPjZI4xqdHcx8QzXnuyyRCoOgWt5M9M0Y/edit)
- [Motoring life time ban (the same as never spent)](https://docs.google.com/document/d/111LDeMBZoIiYuCcPU21UHtgq-iS3SFJDp9VRVT_64LA/edit)
- [Motoring](https://docs.google.com/document/d/1yLFoj7P3EQxfsnjk_d7dswzoeiq94sMAuv7flIKZuI4/edit)
- [Spent custodial](https://docs.google.com/document/d/1qBStZPNiMSPSCK8MHwnnG4kfWMM1_LPGx_YK7dkniUI/edit)

Update result page copy

---

app/helpers/analytics_helper.rb
app/helpers/application_helper.rb
app/views/steps/check/results/shared/_feedback.en.html.erb
spec/helpers/analytics_helper_spec.rb
spec/helpers/application_helper_spec.rb

And propagate an extra parameter in the survey link in the header, whether it was a check for under-18 or over-18 (only if we know it, otherwise we pass `unknown`).

Add a separate results survey for adults

---

app/presenters/caution_result_presenter.rb
app/presenters/conviction_result_presenter.rb
config/locales/en/results.yml
spec/i18n_spec.rb
spec/presenters/caution_result_presenter_spec.rb
spec/presenters/check_presenter_spec.rb
spec/presenters/conviction_result_presenter_spec.rb

As per Simon new designs for multiples, we are going to partially implement this for the current version of the service, as it makes for a simplified and more easy to understand summary table.
Essentially we remove 1 row in cautions, and 2 rows in convictions.
There is still a change that we might want to do, which is replacing the word `conviction` with `sentence` in the tables, but only for certain conviction types.
This will require some UR so it is not implemented yet.
Adapt the tests and locales.
Cautions:
Convictions:

Simplify results summary tables

---

app/controllers/about_controller.rb
app/helpers/application_helper.rb
app/views/about/contact.en.html.erb
app/views/layouts/_phase_banner.html.erb
config/locales/en/layouts.yml
config/routes.rb
spec/controllers/about_controller_spec.rb
spec/helpers/application_helper_spec.rb

Same to what we did on C100, we link to a contact page where we give instructions on how to contact us to provide feedback.

Add contact page and link from header

---

app/services/conviction_length_choices.rb
app/value_objects/conviction_type.rb
config/locales/en/helpers.yml
config/locales/en/results.yml
features/youth/conviction_armed_forces.feature
features/youth/conviction_military.feature
spec/services/conviction_length_choices_spec.rb
spec/value_objects/conviction_type_spec.rb

This was already implemented into the service but hidden as for the YOT pilot there was no audience to test with.
Added the hint text, renamed to `military`, reordered alphabetically and fixed a couple of calculations.
Individual commits for an easier review.
This can be deployed to staging for testing, make any further amendments and, if we decide so, release it.
If not, we can use again the `DISABLED_PARENT_TYPES` array to hide it but leave it prepared for a quick release at a later date.

Show armed forces, was hidden for YOTs

---

app/value_objects/conviction_type.rb
features/youth/conviction_military.feature
spec/value_objects/conviction_type_spec.rb

This was enabled briefly to test it and make any amendments if needed, but we do not intend to deploy to production just yet.
After the testing is done, we are making this hidden again, so staging and prod environments are the same.

Hide military convictions for under 18s

---

Dockerfile
config/database.yml
config/environments/production.rb
docker-compose.yml

For production environments we are going to force the verify-full SSL mode in all connections to the database.
It will be overriden (`DATABASE_SSLMODE=disable`) when using docker-compose so we are still able to run and test the application locally.
This follows best practices and guidance from Cloud Platforms here:
https://user-guide.cloud-platform.service.justice.gov.uk/tasks.html#ssl-connections-with-rds

Enable postgres `verify-full` SSL mode

---

app/controllers/steps/conviction/conviction_bail_days_controller.rb
app/forms/steps/conviction/conviction_bail_days_form.rb
app/services/conviction_decision_tree.rb
app/views/steps/conviction/conviction_bail_days/edit.html.erb
config/locales/en/conviction.yml
config/locales/en/errors.yml
config/locales/en/helpers.yml
config/routes.rb
db/migrate/20191120120826_add_conviction_bail_days_to_disclosure_check.rb
db/schema.rb
lib/govuk_components/form_builder.rb
spec/controllers/steps/conviction/conviction_bail_days_controller_spec.rb
spec/forms/steps/conviction/conviction_bail_days_form_spec.rb
spec/services/conviction_decision_tree_spec.rb

As part of the bail journey, this is the follow-up question after the previous yes-no question.
It is not yet visible in the "normal" journey but can be accessed directly knowing the URL.
Fixed an issue in our custom form builder where a `text_field` would not maintain their value between reloads.

Add days spent on bail step

---

app/services/base_calculator.rb
app/services/calculators/sentence_calculator.rb
spec/services/base_calculator_spec.rb
spec/services/calculators/sentence_calculator_spec.rb

Each full day spent on bail with a tag offsets half a day from the sentence length.
We must take this into consideration also to calculate the different rehabilitation bands or periods.
Updated the method `#sentence_length_in_months` so we can pass an offset (negative number of days, or zero) to subtract.

Add calculation of bail time to SentenceCalculator

---

app/forms/steps/conviction/conviction_bail_days_form.rb
app/presenters/conviction_result_presenter.rb
app/presenters/results_presenter.rb
app/views/steps/check/results/shared/_summary.en.html.erb
config/locales/en/errors.yml
config/locales/en/results.yml
spec/forms/steps/conviction/conviction_bail_days_form_spec.rb
spec/presenters/caution_result_presenter_spec.rb
spec/presenters/conviction_result_presenter_spec.rb

We show a message when we detect there is time spent on bail.
Also, added a validation to the `ConvictionBailDaysForm` to enter a number greater than zero. But can still be left blank if the user doesn't know this information.

Update results page for bail

---

app/views/steps/conviction/compensation_payment_date/edit.html.erb
config/locales/en/conviction.yml
config/locales/en/helpers.yml

After a copy audit, we detected some hint text needed amendments to be consistent with the type of offense they were referring to.

Amend some date hint text

---

app/controllers/steps/conviction/conviction_subtype_controller.rb
app/helpers/experiments_helper.rb
app/services/conviction_decision_tree.rb

We are going to leave this enabled on local/staging envs but for the time being we will not show the bail questions on production as this is still WIP.
This way we can continue deploying fixes and copy changes to prod without opening this to the public.

Bypass bail journey on prod envs

---

app/forms/form_attribute_methods.rb
app/models/disclosure_check.rb
lib/tasks/daily_tasks.rake
spec/models/disclosure_check_spec.rb

Instead of doing the cleanup through the `DisclosureCheck` model, we can now do it through the `DisclosureReport` as all records will have this model as the enclosure and dependents will be destroyed.

Update daily_tasks to cleanup reports

---

app/presenters/question_answer_row.rb
app/presenters/results_presenter.rb
config/locales/en/results.yml
spec/presenters/caution_result_presenter_spec.rb
spec/presenters/conviction_result_presenter_spec.rb
spec/presenters/question_answer_row_spec.rb

If any of the dates given entered by the user are marked as being approximate, then we show this next to the date in the results page answer table.

Indicate approximate dates on results page

---

config/locales/en/helpers.yml
spec/fixtures/files/check_box_fieldset.html

Following suggestions from content designer. We basically remove the hint text from the check box and incorporate the copy into the date hint text.

Amend copy in approximate date check box

---

app/helpers/experiments_helper.rb
app/views/steps/caution/conditional_end_date/edit.html.erb
app/views/steps/caution/known_date/edit.html.erb
app/views/steps/conviction/compensation_payment_date/edit.html.erb
app/views/steps/conviction/known_date/edit.html.erb
app/views/steps/conviction/motoring_disqualification_end_date/edit.html.erb
app/views/steps/shared/_approx_date_checkbox.html.erb
spec/helpers/experiments_helper_spec.rb

We don't want this showing on production just yet, but we want it on staging/local.
Same as we did with bail, we are going to feature-flag it based on the environment.

Feature-flag the approximate date check boxes

---

app/value_objects/conviction_type.rb
features/youth/conviction_military.feature
spec/value_objects/conviction_type_spec.rb

We can enable this now, so we revert the commit where we hide these convictions.
This reverts commit d79e8a5f9d2da8a5fac39008ade7a277a68e5183, reversing
changes made to 065554690cba6e3d4bf01b8204271dad6b5004e7.

Show military convictions for under 18s

---

app/helpers/experiments_helper.rb
app/views/steps/shared/_approx_date_checkbox.html.erb
spec/helpers/experiments_helper_spec.rb

This was previously hidden on production envs.
Now we can enable it.

Enable approximate dates check box

---

Dockerfile
docker-compose.yml
run.sh
worker.sh

The Dockerfiles in the repo docker-templates [1] is being deprecated and it is recommended to keep Dockerfiles and docker images as lightweight and simple as possible.
In this case we are going to refactor the Dockerfile to use an alpine image and add dependencies on top.
[1] https://github.com/ministryofjustice/docker-templates

Stop using ministryofjustice/docker-templates

---

app/services/calculators/sentence_calculator.rb
app/views/steps/check/results/shared/_summary.en.html.erb
spec/services/calculators/sentence_calculator_spec.rb

Ticket: https://mojdigital.teamwork.com/#/tasks/19868485
This is an urgent change as per sentencing policy:
Courts already calculate days on bail into the sentence, to keep calculations accurate we need to have a whole day taken off the spent date for each day spent on bail tag.
Instead of half a day as before, now the bail time substract the total amount (of bail time) from the sentence which effectively is equivalent to multiply by -1.

Change bail offset from half a day to a whole day

---

config/locales/en/errors.yml
features/adults/conviction_financial.feature

This commit updates the radio button error message to be more specific instead
of using a generic phrase.
I decided to use cucumber to test that the error message is correct, but happy to discuss this if you think it's too much.

Update the error message when user does not select a radio button

---

app/views/steps/conviction/compensation_unable_to_tell/show.html.erb

We are already tracking some things in this service, with Google Analytics
transactions, because goals can't trigger more than once for the same session and
many users of this service will do multiple checks in one session if they have
multiple convictions etc.
So in order to track those, we use a helper method named `track_transaction`,
and although it tracks automatically completions, it doesn't track exit pages
(or kick outs) out of the box so we have to add the call manually.

Add transaction tracking to "Unable to tell" (exit page)

---

app/views/steps/check/results/shared/_motoring.en.html.erb
app/views/steps/check/results/show.en.html+conviction_never_spent.erb

https://mojdigital.teamwork.com/#/tasks/19966291
Minor copy changes to motoring convictions in the results page.
Added the motoring partial also to the never spent results page, as even when never spent, the information and links in the partial is valuable and still apply.

Update motoring results page copy

---

app/decorators/conviction_decorator.rb
app/services/calculators/motoring_calculator.rb
app/services/conviction_decision_tree.rb
app/value_objects/conviction_type.rb
config/locales/en/helpers.yml
config/locales/en/results.yml
features/step_definitions/common.rb
features/youth/conviction_motoring.feature
spec/decorators/conviction_decorator_spec.rb
spec/services/calculators/motoring_calculator_spec.rb
spec/services/conviction_length_choices_spec.rb
spec/value_objects/conviction_type_spec.rb

This commit introduces motoring convictions for under age, it slightly differs from adult motoring convictions,
for under age, the convictions are spent sooner.
The differences are:
- [Endorsement is 2.5 years (30 months)](https://www.gov.uk/guidance/telling-people-about-your-criminal-record#motoring) instead of 5 years (60 months)
- [Fines are 6 months](https://www.gov.uk/guidance/telling-people-about-your-criminal-record#fine) instead of 1 year (12 months)
Story: https://mojdigital.teamwork.com/#/tasks/20007708

Introduce under age motoring convictions

---

app/services/base_calculator.rb
app/services/calculators/sentence_calculator.rb
features/adults/conviction_custodial_sentence.feature
features/youth/conviction_custodial_sentence.feature
spec/services/base_calculator_spec.rb
spec/services/calculators/sentence_calculator_spec.rb

Note: bail is not yet "visible" in production. This can be tested on dev/staging environments.
Previously, we deducted the bail time before we looked at the rehabilitation periods.
This is incorrect - the rehabilitation period should be determined on the basis of the full sentence as given by the court, irrespective of any bail time.
Changed the order of the calculations for bail to reflect the correct policy.
Extended and improved some of the tests.

Fix the order of bail time calculations

---

app/services/calculators/motoring/adult/disqualification.rb
app/services/calculators/motoring/adult/fine.rb
app/services/calculators/motoring/adult/penalty_notice.rb
app/services/calculators/motoring/adult/penalty_points.rb
app/services/calculators/motoring/youth/disqualification.rb
app/services/calculators/motoring/youth/fine.rb
app/services/calculators/motoring/youth/penalty_notice.rb
app/services/calculators/motoring/youth/penalty_points.rb
app/services/calculators/motoring_calculator.rb
app/value_objects/conviction_type.rb
features/youth/conviction_motoring.feature
spec/services/calculators/motoring/adult/disqualification_spec.rb
spec/services/calculators/motoring/adult/fine_spec.rb
spec/services/calculators/motoring/adult/penalty_notice_spec.rb
spec/services/calculators/motoring/adult/penalty_points_spec.rb
spec/services/calculators/motoring/youth/disqualification_spec.rb
spec/services/calculators/motoring/youth/fine_spec.rb
spec/services/calculators/motoring/youth/penalty_notice_spec.rb
spec/services/calculators/motoring/youth/penalty_points_spec.rb
spec/services/calculators/motoring_calculator_spec.rb
spec/value_objects/conviction_type_spec.rb

I have reorganised the way the MotoringCalculator has been written, I find this was useful and essential to avoid logical problems between Under 18 and Over 18.
Before there was only Over 18 Motoring Calculations, but with the addition of Under 18 https://github.com/ministryofjustice/disclosure-checker/pull/350 it became clear this needed some refactor to accommodate both.
This also gave me the opportunity to spot two bugs on Under 18 which would have been hard to spot before.
There are cucumber features to back up the changes as well as unit tests.
I've tried to make the changes as small as I could in individual commits.
Story: https://mojdigital.teamwork.com/#/tasks/20007708

Reorganise Motoring Calculator

---

app/decorators/conviction_decorator.rb
app/services/conviction_decision_tree.rb
spec/decorators/conviction_decorator_spec.rb
spec/services/conviction_decision_tree_spec.rb

This is just a refactor of the latest changes done around motoring (adult and youth) as this was clogging the ConvictionDecisionTree.
The ConvictionDecorator is now the place where logic decisions are made between adult/youth.

Refactor conviction decision tree

---

app/controllers/steps/conviction/conviction_subtype_controller.rb
app/helpers/experiments_helper.rb
app/services/conviction_decision_tree.rb
app/views/home/index.en.html.erb
app/views/steps/check/results/shared/_disclaimer.en.html.erb
app/views/steps/check/results/show.en.html+multiples.erb
spec/helpers/experiments_helper_spec.rb

This was behind a feature flag and only visible on dev/staging envs up until now.
Minor copy changes to remove references to bail that we no longer need after enabling this.

Enable bail journey in all environments

---

package.json
yarn.lock

A new version has been released:
https://github.com/alphagov/govuk-frontend/releases/tag/v3.7.0
There should not be any breaking changes, and the only noticeable change is the Back link styling, as indicated in the changelog.

Bump GOV.UK Frontend v3.7.0

---

db/migrate/20200716114413_remove_motoring_lifetime_ban_from_disclosure_checks.rb
db/schema.rb

We have remove the functionality around motoring lifetime ban, this is just to tidy up and remove the database column which is no longer in use.
Follow up on https://github.com/ministryofjustice/disclosure-checker/pull/361/files
Story: https://mojdigital.teamwork.com/#/tasks/20951241

Remove motoring_lifetime_ban from disclosure checks table

---

app/decorators/conviction_decorator.rb
app/forms/steps/conviction/conviction_subtype_form.rb
app/services/calculators/motoring/adult/penalty_points.rb
app/services/calculators/motoring/youth/penalty_points.rb
app/services/conviction_decision_tree.rb
features/adults/conviction_motoring.feature
features/youth/conviction_motoring.feature
spec/forms/steps/conviction/conviction_subtype_form_spec.rb
spec/services/calculators/motoring/adult/penalty_points_spec.rb
spec/services/calculators/motoring/youth/penalty_points_spec.rb
spec/services/conviction_decision_tree_spec.rb

Penalty points can only be accrued if the offence has been endorsed. So  you won’t see penalty points without endorsement.
Co-Authored-by: @njseeto 
Story: https://mojdigital.teamwork.com/#/tasks/21245933

Remove endorsement question from motoring penalty points

---

app/views/layouts/_sentry_feedback.html.erb

We've moved away from the self-hosted sentry instance, so this code needs to be updated.
It also was using a very old JS version.

Update sentry feedback code

---

app/forms/steps/conviction/conviction_subtype_form.rb
spec/forms/steps/conviction/conviction_subtype_form_spec.rb

Task: https://mojdigital.teamwork.com/#/tasks/21392749
Reseting the motoring attributes allows us to minimise the affect on calculations if a user to goes back and changes their journey.
I think there's only the motor attributes that need to be reset, please do let me know if there are any others.
List of attributes:

Reset motoring attributes to nil

---

app/views/steps/conviction/compensation_paid/edit.html.erb
config/locales/en/helpers.yml

Needs to be rebased after https://github.com/ministryofjustice/disclosure-checker/pull/377 is merged to use the YAML constant YESNO.
Story: https://mojdigital.teamwork.com/#/tasks/21707828

Update Design System for steps/conviction/compensation_paid

---

app/forms/steps/conviction/compensation_payment_date_form.rb
app/views/steps/conviction/compensation_payment_date/edit.html.erb
config/locales/en/helpers.yml
spec/forms/steps/conviction/compensation_payment_date_form_spec.rb

Ticket: https://mojdigital.teamwork.com/#/tasks/21707830
Continuation of PR #375, migrating all the dates in the service to use the new gem.

Migrate `compensation_payment_date` to use new gem

---

app/forms/steps/conviction/known_date_form.rb
app/helpers/custom_form_helpers.rb
app/views/steps/conviction/known_date/edit.html.erb
config/locales/en/helpers.yml
spec/forms/steps/conviction/known_date_form_spec.rb
spec/helpers/custom_form_helpers_spec.rb

Similar to previous PR to migrate gems, but this one is a bit special as this is the first form to be migrated with our custom `i18n_attribute` that we created to allow a same form to be reused in multiple views with different legends and hint texts.
This is a preliminary version of a potential solution that more or less maintain the same interface and same locales and should be easy to migrate the rest of the forms.

Migrate `conviction_known_date` to use new gem

---

app/forms/steps/conviction/motoring_disqualification_end_date_form.rb
app/views/steps/conviction/motoring_disqualification_end_date/edit.html.erb
config/locales/en/errors.yml
config/locales/en/helpers.yml
spec/forms/steps/conviction/motoring_disqualification_end_date_form_spec.rb

Ticket: https://mojdigital.teamwork.com/#/tasks/21737618
Same as with previous dates.
This one however allows to be in the future, and also to be left blank.
In a follow-up PR, I will remove all the code related to the old dates gem and refactor the duplication in the tests now that we've migrated all the dates.

Migrate `motoring_disqualification_end_date` to use new gem

---

db/migrate/20190926082054_add_motoring_endorsement_to_disclosure_check.rb

I had to drop and recreate my local DB and I found this issue.
This does not affect already created databases.

Fix typo in DB migration

---

Gemfile
Gemfile.lock
app/views/steps/caution/conditional_end_date/edit.html.erb
app/views/steps/caution/known_date/edit.html.erb
app/views/steps/conviction/compensation_payment_date/edit.html.erb
app/views/steps/conviction/known_date/edit.html.erb
app/views/steps/conviction/motoring_disqualification_end_date/edit.html.erb
app/views/steps/shared/_approx_date_checkbox.html.erb
app/views/steps/shared/_new_approx_date_checkbox.html.erb
lib/generators/step/templates/date/edit.html.erb
spec/forms/steps/caution/conditional_end_date_form_spec.rb
spec/forms/steps/caution/known_date_form_spec.rb
spec/forms/steps/conviction/compensation_payment_date_form_spec.rb
spec/forms/steps/conviction/known_date_form_spec.rb
spec/forms/steps/conviction/motoring_disqualification_end_date_form_spec.rb
spec/support/form_validation_shared_examples.rb

This is the final PR to the work done to migrate the dates to use the new gem.
In this PR we remove the gem, and cleanup/refactor the old code or the code introduced while we were migrating.

Remove old `gov_uk_date_fields` gem and cleanup old code

---

app/views/steps/conviction/conviction_bail_days/edit.html.erb

Story: https://mojdigital.teamwork.com/#/tasks/21725162
There's a bit of a discrepancy between before and now:
- 'number of days' is not bold (I've tried to play with the size option but nothing changed, ideas?)
- title of the page used to be larger
- On C100 we normally used `one-half` or similar, but any of those sizes made the text field look really wide, so I used `width: 3` instead
Left is new design, right is old design

Update Design System for steps/conviction/conviction_bail_days/

---

app/helpers/application_helper.rb
app/views/steps/caution/caution_type/edit.html.erb
app/views/steps/caution/conditional_end_date/edit.html.erb
app/views/steps/caution/known_date/edit.html.erb
app/views/steps/check/kind/edit.html.erb
app/views/steps/check/under_age/edit.html.erb
app/views/steps/conviction/compensation_paid/edit.html.erb
app/views/steps/conviction/compensation_paid_amount/edit.html.erb
app/views/steps/conviction/compensation_payment_date/edit.html.erb
app/views/steps/conviction/compensation_payment_receipt/edit.html.erb
app/views/steps/conviction/conviction_bail/edit.html.erb
app/views/steps/conviction/conviction_bail_days/edit.html.erb
app/views/steps/conviction/conviction_length/edit.html.erb
app/views/steps/conviction/conviction_length_type/edit.html.erb
app/views/steps/conviction/conviction_subtype/edit.html.erb
app/views/steps/conviction/conviction_type/edit.html.erb
app/views/steps/conviction/known_date/edit.html.erb
app/views/steps/conviction/motoring_disqualification_end_date/edit.html.erb
app/views/steps/conviction/motoring_endorsement/edit.html.erb
config/initializers/form_builder.rb

This commit removes all the explicit places where we had previously defined which form builder to be used and make it the default form builder in this project.

Define GOVUKDesignSystemFormBuilder::FormBuilder as the default

---

.gitignore
app/helpers/application_helper.rb
app/helpers/custom_form_helpers.rb
app/views/application/_step_subsection.html.erb
app/views/steps/conviction/compensation_paid/edit.html.erb
app/views/steps/conviction/compensation_paid_amount/edit.html.erb
app/views/steps/conviction/compensation_payment_date/edit.html.erb
app/views/steps/conviction/compensation_payment_receipt/edit.html.erb
app/views/steps/conviction/conviction_bail/edit.html.erb
app/views/steps/conviction/conviction_bail_days/edit.html.erb
app/views/steps/conviction/conviction_length/edit.html.erb
app/views/steps/conviction/conviction_length_type/edit.html.erb
app/views/steps/conviction/known_date/edit.html.erb
app/views/steps/conviction/motoring_disqualification_end_date/edit.html.erb
app/views/steps/conviction/motoring_endorsement/edit.html.erb
config/locales/en/helpers.yml
features/step_definitions/common.rb
spec/helpers/application_helper_spec.rb
spec/helpers/custom_form_helpers_spec.rb

The caption is now part of the form, that means that if there's an error message the whole vertical red line also covers the caption above the page header (h1)
Example:
Story: https://mojdigital.teamwork.com/#/tasks/21724564

Use the caption field provided by the Design System gem

---

config/locales/en/helpers.yml

Missed the compensation paid page caption translation key.
This did not affect production (just staging)

add missing translation key for compensation paid page

---

app/assets/javascripts/modules/ga-events.js

The new gem produce a slighly different markup with multiparam text inputs.
In order to keep tracking these (only the year part) as before, with the same event category, we need to do some tweaks.

Update GA dates tracking to work with new gem

---

app/views/steps/check/results/shared/_disclaimer.en.html.erb
app/views/steps/check/results/shared/_summary.en.html.erb
app/views/steps/check/results/show.en.html+caution_not_spent.erb
app/views/steps/check/results/show.en.html+caution_spent.erb
app/views/steps/check/results/show.en.html+caution_spent_simple.erb
app/views/steps/check/results/show.en.html+conviction_never_spent.erb
app/views/steps/check/results/show.en.html+conviction_no_record.erb
app/views/steps/check/results/show.en.html+conviction_not_spent.erb
app/views/steps/check/results/show.en.html+conviction_spent.erb

Task: https://mojdigital.teamwork.com/#/tasks/21185823
The changes include:
- Remove heading "What this result means" and the first sentence "based on what you've told us..."
- Replace bullet points under the heading "How this result has been worked out" with a sentence outlining similar information
- Remove "rehabilitation periods" link
- Remove the sentence with the "start a new check" link
- Add the final sentence, "If you need to change..."
- Add a button for "Start a new check"

Copy changes to Results Page

---

app/views/steps/check/results/show.en.html+conviction_not_spent.erb
app/views/steps/check/results/show.en.html+conviction_spent.erb

Task: https://mojdigital.teamwork.com/#/tasks/21185823
- Ensure the sentence below the green box make sense for both convictions spent and convictions not spent.
- Also have the sentence appear for all convictions, not just custodial sentences.
No changes required for Cautions, Convictions that will never be spent or Convictions that do not need to be disclosed (eg: motoring fines)
If merged:

Add sentence to Results Page

---

Dockerfile

Running the docker image won't know about the `.ruby-version` file without copying it into the image.
This happened on #402 when I changed the Gemfile to read the ruby version from that file.
I should have run `docker-compose up` to see the problem.

Add .ruby-version file in Dockerfile

---

app/helpers/custom_form_helpers.rb

No breaking changes but there are some new features in ruby 2.7.x as well as some deprecations in preparation for the next major version.
General changes in 2.7.x:
https://www.ruby-lang.org/en/news/2019/12/25/ruby-2-7-0-released/
Deprecations turned off in 2.7.2:
https://www.ruby-lang.org/en/news/2020/10/02/ruby-2-7-2-released/
As these deprecations are turned off by default on 2.7.2, to see them I did the following,
running all the tests to see only the deprecations in our code, NOT in the gems as we don't have control over those ones:
```bash
RUBYOPT='-W:deprecated' RAILS_ENV=test bundle exec rake test:all_the_things 2>&1 | grep -v gems | grep deprecated
```
More info about these deprecations and the next ruby version 3.0 here: …

Fix warnings on ruby 2.7.2

---

app/lib/markup_normaliser.rb
features/fixtures/README.md
features/fixtures/files/steps_check_kind.html
features/fixtures/files/steps_check_kind_with_errors.html
features/fixtures/files/steps_conviction_known_date.html
features/fixtures/files/steps_conviction_known_date_with_errors.html
features/markup_smoke_tests.feature
features/step_definitions/common.rb
features/step_definitions/fixturers.rb

During an upgrade to the Design System on C100 it was noticed that the forms were not working properly with hints on check boxes (https://github.com/DFE-Digital/govuk_design_system_formbuilder/pull/211).
We decided to introduce the same mechanism used on C100 in Disclosure Checker.
Story: https://mojdigital.teamwork.com/#/tasks/22441209

Design System smoke tests

---

app/value_objects/conviction_type.rb
spec/value_objects/conviction_type_spec.rb

Ticket: https://mojdigital.teamwork.com/#/tasks/22733126
The calculation of the criminal behaviour order needs to be changed from `A+B+1y` to `A+B`.

Fix criminal behaviour order calculation

---

app/value_objects/conviction_type.rb
spec/value_objects/conviction_type_spec.rb

This change won't affect any existing calculations or journeys. This is a pre step purely to identify which sub conviction types are considered relevant orders. This will be important to help calculations when a user is given a conviction with several sentences, if one of them is a relevant order, that sentence is not considered - meaning that even if ends later than all others, it won't affect the spent end date.
**Please do note** that the codebase defines a Sentence as a Conviction, although in real life it works as such:
A person is given a Conviction and this may have 1 or more sentences within.
Story: https://mojdigital.teamwork.com/#/tasks/23009279
Supporting Document: https://docs.google.com/spreadsheets/d/1ZSCk-wgMfIc22GQahKH_ys4u-E9GWIn6dQ7mm5t1RFI/edit#gid=2019860123

Identify which sub conviction types are relevant orders

---

.circleci/config.yml

This is neccessary as more recent versions in CircleCI starts giving errors when writing assets:
```
error An unexpected error occurred: "EPERM: operation not permitted, copyfile '/usr/local/share/.cache/yarn/v6/npm-govuk-frontend-3.10.2-6589401e4adad1ab1dc340a18057ec88c9435a84-integrity/node_modules/govuk-frontend/README.md' -> '/usr/src/app/node_modules/govuk-frontend/README.md'".
info If you think this is a bug, please open a bug report with the information provided in "/usr/src/app/yarn-error.log".
```
Kudos to another team who found this problem first and shared the solution:
https://mojdt.slack.com/archives/CCSD5F397/p1610108410041100

Specify version of docker to use in CircleCI

---

app/services/conviction_length_choices.rb
spec/services/conviction_length_choices_spec.rb

This was noticed as part of a related ticket:
https://trello.com/c/MrEm9UKp
According to the matrix of convictions that should show/hide the "no length was given" radio option, `serious crime prevention orders` should show the option.
It was hidden before.

Show no length option in `serious crime prevention` orders

---

app/services/base_multiples_calculator.rb
spec/services/calculators/multiples/multiple_offenses_calculator_spec.rb

Back in pull request [#364](https://github.com/ministryofjustice/disclosure-checker/pull/364) the simple caution was simplified and the date question was skipped.
While this is currently working, this work is necessary in preparation for multiple convictions.
This fixes the following error:
```
NoMethodError:
undefined method `past?' for :spent_simple:Symbol
```
When a user has a simple caution, that caution is spent on the day it was given, therefore the return value is true.
Story: https://trello.com/c/Gbnpo8Hu

Fix BaseMultiplesCalculator to consider spent_simple

---

app/presenters/results_presenter.rb
app/services/base_calculator.rb
app/services/calculators/addition_calculator.rb
app/services/calculators/multiples/same_proceedings.rb
app/services/conviction_decision_tree.rb
app/services/conviction_length_choices.rb
app/value_objects/conviction_length_type.rb
app/views/steps/check/results/show.en.html+conviction_indefinite.erb
config/locales/en/helpers.yml
config/locales/en/results.yml
features/adults/conviction_custodial_sentence.feature
features/youth/conviction_custodial_sentence.feature
spec/forms/steps/conviction/conviction_length_type_form_spec.rb
spec/presenters/conviction_result_presenter_spec.rb
spec/services/calculators/addition_calculator_spec.rb
spec/services/calculators/multiples/same_proceedings_spec.rb
spec/services/conviction_decision_tree_spec.rb
spec/services/conviction_length_choices_spec.rb
spec/value_objects/conviction_length_type_spec.rb

Ticket: https://trello.com/c/MrEm9UKp
Individual commits for more detail.
Relevant orders need to expose a new "length" option apart from the existing ones. In total now there are up to 5 different options: weeks, months, years, no length, indefinite (until further order).
If the conviction has an indefinite length, then a different results page, specific for indefinite is shown to the user.
**Note**: 18 out of 20 relevant orders now have the ability of selecting indefinite option. We still have 2 more that requires it but will be done as part of a separate ticket as will require design and probably a new question to ask. These are motoring disqualifications (youths and adults).

Add an "indefinite" length option to relevant orders

---

app/services/base_multiples_calculator.rb
app/services/calculators/multiples/same_proceedings.rb
spec/presenters/conviction_result_presenter_spec.rb
spec/presenters/spent_date_panel_spec.rb
spec/services/calculators/multiples/multiple_offenses_calculator_spec.rb
spec/services/calculators/multiples/same_proceedings_spec.rb

We've removed FPN in PR #419, so we don't use anymore the special result `no_record`.
Some code can be cleaned up.
As part of a following PR I'm refactoring the different variants we have (never_spent, spent_simple, indefinite, etc) as it is becoming increasingly difficult to find all the places where we are using them and will be easier to work with a single value-object.

Delete some old code no longer needed for `no_record`

---

app/presenters/results_presenter.rb
app/presenters/spent_date_panel.rb
app/services/base_multiples_calculator.rb
app/services/calculators/addition_calculator.rb
app/services/calculators/caution_calculator.rb
app/services/calculators/multiples/same_proceedings.rb
app/services/calculators/sentence_calculator.rb
app/value_objects/results_variant.rb
config/locales/en/results.yml
spec/presenters/conviction_result_presenter_spec.rb
spec/presenters/spent_date_panel_spec.rb
spec/services/calculators/addition_calculator_spec.rb
spec/services/calculators/caution_calculator_spec.rb
spec/services/calculators/multiples/multiple_offenses_calculator_spec.rb
spec/services/calculators/multiples/same_proceedings_spec.rb
spec/services/calculators/sentence_calculator_spec.rb
spec/value_objects/results_variant_spec.rb

Ticket: https://trello.com/c/LS4gr8Uh
Over the last few months, we've had to add some "exceptions" to the rule and some cautions or convictions do not return just a date when they are spent, some returns special variants, like:
* never_spent
* spent_simple
* indefinite
We also had before `no_record` for FPN but this is no longer necessary as we've removed FPN from the service.
Unify in the `ResultsVariant` value-object all these possible result variants and always use them through the value-object so it is easy to either remove them, add more or change them in the future.

Refactor and DRY the different result variants

---

app/decorators/conviction_decorator.rb
app/services/calculators/disqualification_calculator.rb
app/services/conviction_decision_tree.rb
config/locales/en/conviction.yml
config/locales/en/helpers.yml
config/locales/en/results.yml
features/adults/conviction_motoring.feature
features/youth/conviction_motoring.feature
spec/decorators/conviction_decorator_spec.rb
spec/services/calculators/disqualification_calculator_spec.rb
spec/services/conviction_decision_tree_spec.rb

Ticket: https://trello.com/c/PhgvFgKM
This is a follow-up to PR #351.
Individual commits for more details.
For motoring disqualifications we should also support an "indefinite / until further order" option, but because motoring disqualifications did not "flow" through the conviction length type step as other orders, they did not get the "indefinite" functionality we implemented in PR #418.
With this PR we change the disqualification journey to ask for a length, instead of an end date, and update the calculator to work with this. This way we also expose the `no length was given` and the `until further order` options.
**Note**: in a future PR we will remove the unused step/views/locales, and the DB attribute.

Implement "indefinite" length for motoring disqualifications

---

spec/factories/disclosure_check.rb

Story: https://trello.com/c/kj6dxoFV/58-dc-create-factories-to-ease-testing-multiple-convictions
In this PR I'm introducing the following factories:
- Fine
- Motoring Disqualification
- Motoring Penalty Points
- Motoring Fine
I've also made some small changes that should allow us to create scenarios on both Youth and Adult by simply using the one we need. 
Example of usage:
```ruby
FactoryBot.create(:disclosure_check, :youth, :with_fine_conviction)
FactoryBot.create(:disclosure_check, :adult, :with_fine_conviction)
```
Internally the factory should be handling all other settings.
----
In a later PR I will be introducing the following:
- Conditional Discharge Order
- Community Order Selected
- Prison Sentence
- Bind Order
- Sexual Harm

Add factory examples

---

.rubocop.yml
app/services/base_multiples_calculator.rb
app/services/calculators/multiples/multiple_offenses_calculator.rb
spec/presenters/check_answers_presenter_spec.rb
spec/services/calculators/multiples/multiple_offenses_calculator_spec.rb
spec/services/calculators/multiples/same_proceedings_spec.rb
spec/services/calculators/multiples/separate_proceedings_spec.rb

Ticket: https://trello.com/c/W2K1PV43
This is a first (and admittedly not very elegant) attempt to perform drag-through calculations for **separate proceedings**, meaning we need to extend the spent date of a conviction if the rehabilitation period of said conviction overlaps (even if it is just 1 day) with the rehabilitation period of another conviction.
Note, some limitations with this first version that will be sorted out in follow-up PRs:
- The loop is not sorted by conviction date, so the final result is not idempotent (depends on the order the convictions are added to the "basket"). This loop will need to be sorted.
- We will need to do something similar, if not identical, in the `SameProceedings` calculator, because the sentences inside a conviction can also have drag-through, but …

First attempt to perform drag-through calculations

---

app/services/base_multiples_calculator.rb
app/services/calculators/multiples/multiple_offenses_calculator.rb
spec/services/calculators/multiples/multiple_offenses_calculator_spec.rb
spec/services/calculators/multiples/same_proceedings_spec.rb
spec/services/calculators/multiples/separate_proceedings_spec.rb

Ticket: https://trello.com/c/W2K1PV43
Follow-up to PR #427.
As mentioned before the results were not idempotent. This is now solved by having a predictable iteration order in the loop, by conviction `start date`.
The start date for a conviction with more than one sentences is the earliest of the dates.
Some of the scenarios in the Unlock spreadsheet can now be coded into tests with factories and should give us predictable (and accurate) results.
Other scenarios can't be run just yet as they will fail.

Sort drag-through loop by conviction start date

---

app/controllers/checks_controller.rb
app/forms/steps/conviction/conviction_subtype_form.rb
app/models/check_group.rb
app/services/calculators/multiples/multiple_offenses_calculator.rb
app/services/calculators/multiples/same_proceedings.rb
app/services/calculators/multiples/separate_proceedings.rb
app/services/conviction_decision_tree.rb
spec/controllers/checks_controller_spec.rb
spec/forms/steps/conviction/conviction_subtype_form_spec.rb
spec/services/calculators/multiples/multiple_offenses_calculator_spec.rb
spec/services/conviction_decision_tree_spec.rb

Ticket: https://trello.com/c/W2K1PV43
Follow-up to PR #428.
Using a range is more accurate as there were some edge cases where otherwises the loop would return wrong results.
Also, tweak the multiples journey to not ask again for the conviction date, in same proceedings, as the start date is shared between all sentences.

Multiple offences calculator tweaks

---

app/presenters/check_answers_presenter.rb
app/services/calculators/multiples/multiple_offenses_calculator.rb
app/services/caution_decision_tree.rb
features/adults/caution.feature
features/youth/caution.feature
spec/factories/disclosure_check.rb
spec/presenters/caution_result_presenter_spec.rb
spec/presenters/check_answers_presenter_spec.rb
spec/services/calculators/multiples/multiple_offenses_calculator_spec.rb
spec/services/caution_decision_tree_spec.rb

Instead of working with "check_group" objects, it is best to work with proceedings (meaning SameProceedings or SeparateProceedings) classes.
A bit of refactor to the calculator interface, so now instead of passing a check_group to the `#spent_date_for` method we pass the proceeding directly. Internally it knows what to do.
Also no need to call `#process!` manually anymore as that is now part of the initialization.
Finally, making sure the proceedings are returned always sorted by start date, in the "Check your answers" and in the results page.
For this sorting to work properly, I've reintroduce the simple caution "known date" step, otherwise we can't sort as for simple cautions we removed the date step.
The results page for simple caution however are left as before: `This caution is spent …

Refactor multiples calculator to work with proceedings

---

db/migrate/20210129153053_remove_approximate_end_date.rb
db/schema.rb

We removed the approximate motoring disqualification end date step in PR #424 but forgot to also remove this DB field, as it is no longer used in any other place.

Remove unused DB field

---

app/services/calculators/multiples/multiple_offenses_calculator.rb

We only need to sort the proceedings by `start date` in the `#spent_date_for` loop, as we need to see if some drag-through is needed.
But in the "check your answers" and final results page, the order should be that of the user, so it is predictable and the user as they enter cautions or convictions, see them being added to the bottom and not jumping around depending on start date.

Tweak the sorting of proceedings

---

app/controllers/steps/conviction/conviction_date_controller.rb
app/forms/steps/conviction/conviction_date_form.rb
app/views/steps/conviction/conviction_date/edit.html.erb
config/locales/en/conviction.yml
config/locales/en/errors.yml
config/locales/en/helpers.yml
config/routes.rb
db/migrate/20210201114508_add_conviction_date.rb
db/schema.rb
spec/controllers/steps/conviction/conviction_date_controller_spec.rb
spec/forms/steps/conviction/conviction_date_form_spec.rb

Ticket: https://trello.com/c/1eRx0JeU
We need to capture and extra date, which will be needed for proper multiple sentences inside a conviction calculations.
Up until now for these calculations we've been using the `known_date` but that is incorrect as that's the date the sentence started. We need the date of the conviction, which might be different.
This PR only adds the new DB fields and controller/view/form but it does not link it yet to the decision tree, that will be done in a follow-up PR.
Also, once we have all this wired up, we will need to update th multiples calculators (uh oh).

Add new conviction date step

---

app/controllers/checks_controller.rb
app/controllers/step_controller.rb
app/forms/steps/check/kind_form.rb
app/forms/steps/conviction/conviction_subtype_form.rb
app/services/base_decision_tree.rb
app/services/check_decision_tree.rb
app/services/conviction_decision_tree.rb
spec/controllers/checks_controller_spec.rb
spec/forms/steps/check/kind_form_spec.rb
spec/forms/steps/conviction/conviction_subtype_form_spec.rb
spec/services/check_decision_tree_spec.rb
spec/services/conviction_decision_tree_spec.rb

Ticket: https://trello.com/c/1eRx0JeU
Ask this new date, but only if we are running the "multiples" MVP (so it will not show for simples or in production).
Revert some of the changes introduced in PR #429.
Unfortunately to do this we have to add some conditional code and propagate the `multiples_enabled` boolean to the decision trees as these do not have access to the controller/session and can't read the cookie.
In a follow-up PR the calculators will need to be updated.

Show conviction date step in multiples MVP

---

app/forms/steps/conviction/known_date_form.rb
config/locales/en/errors.yml
config/locales/en/helpers.yml
features/fixtures/files/steps_conviction_known_date_with_errors.html
spec/forms/steps/conviction/known_date_form_spec.rb

Ticket: https://trello.com/c/1eRx0JeU
Little follow-up to PR #435 to add a validation to the form so the `known_date` can't be *before* the `conviction_date` as that would not make sense and could invalidate the calculations without the user even noticing.
If `conviction_date` or `known_date` are `nil` then we don't perform this validation (currently for "simples" the `conviction_date` is always nil so we must maintain backwards compatibility).

Validate `known_date` against the `conviction_date`

---

app/services/conviction_length_choices.rb
app/value_objects/conviction_length_type.rb
spec/forms/steps/conviction/conviction_length_type_form_spec.rb
spec/services/conviction_length_choices_spec.rb
spec/value_objects/conviction_length_type_spec.rb

A recommendation from legal to change the order of the `indefinite` and `no_length` radio options, so the `no_length` is the last one, and kind of a "catch-all" option.
This does not affect calculations in any way and is only a minor interface change.

Swap order of `indefinite` and `no_length` radio options

---

app/services/base_multiples_calculator.rb
app/services/calculators/multiples/multiple_offenses_calculator.rb
app/services/calculators/multiples/separate_proceedings.rb
spec/factories/disclosure_check.rb
spec/services/calculators/multiples/same_proceedings_spec.rb
spec/services/calculators/multiples/separate_proceedings_spec.rb

Ticket: https://trello.com/c/1eRx0JeU
Instead of the `start_date` (which is the `known_date` DB field), we need to use the new `conviction_date` because although some times both dates can be the same, when deciding if a spent date falls inside another rehabilitation period, we have to use the date of the conviction, not when the sentence or order started, as per legal clarification.

Use the `conviction_date` in multiples calculator

---

app/models/disclosure_check.rb
spec/models/disclosure_check_spec.rb

It's necessary to identify which disclosure check objects have a conviction subtype that is identified as a relevant order.
A relevant order has an important role when it comes to 'drag through' other convictions within the same timeline, meaning, relevant orders only relate to the conviction that they’re linked to, they don’t ‘drag through’ other convictions.
Therefore, a relevant order sentence shall not influence another conviction that it's not part of.
Consider the following scenario:
Marisa, age 38, a company director was convicted on **02/08/15** of fraud.
As a result, she received:
-  a six-month custodial sentence (would become ‘spent’ **02/02/18**) and;
-  a six-year company director disqualification (would become ‘spent’ **02/08/21**).
The fraud conviction would therefore …

Adds method #relevant_order? to DisclosureCheck

---

.rubocop.yml
app/services/calculators/multiples/multiple_offenses_calculator.rb
app/value_objects/results_variant.rb
spec/services/calculators/multiples/multiple_offenses_calculator_spec.rb
spec/value_objects/results_variant_spec.rb

Ticket: https://trello.com/c/PcAlcOaz
This work relates to the edge case where under certain circunstances a never spent, or indefinite conviction could take over the other convictions even if there was no overlapping between them.
In doing this I realised the loop can be simplified further, if we trick the special variants into behave like a Date in terms of ranges.
What this means is:
- A `ResultsVariant::NEVER_SPENT` is like an infinity date, it has no end.
- A `ResultsVariant::INDEFINITE` is a very far in the future date, but is not infinity (this difference is important as one takes precedence over the other).
There might be further tweaks/fixes to do and also it is still pending the work for relevant orders that _might_ affect the loop or the date we need to use on it. But that will …

More tweaks to the MultipleOffensesCalculator

---

app/services/base_multiples_calculator.rb
spec/services/calculators/multiples/same_proceedings_spec.rb
spec/services/calculators/multiples/separate_proceedings_spec.rb

Follow up on #442 where the method `#relevant_order?` was added to DisclosureCheck.
And taken the idea of ignoring relevant orders from #438 
We need this capabilities of ignoring relevant orders when comparing two convictions,
relevant orders only affect their own Conviction without interfering with other Convictions.
By discarding the relevant orders, we will be able to loop through several
convictions without compromising their spent date with the relevant order spent
date.
I've added this method in BaseMultiplesCalculator as I think we may need the
method in both SameProceedings and SeparateProceedings so that it can be used
in MultipleOffensesCalculator.
This addition is a non-breaking change to current behaviour.
Story: https://trello.com/c/7scNWWCF/

Adds methods to identify and ignore relevant orders to BaseMultiplesCalculator

---

app/services/calculators/multiples/multiple_offenses_calculator.rb
spec/services/calculators/multiples/multiple_offenses_calculator_spec.rb

Ticket: https://trello.com/c/PcAlcOaz
Note: this does NOT yet cover the relevant orders.
But in particular with this PR we are trying to cover these scenarios:
* If a conviction is received before another conviction is spent, neither conviction will become spent until the rehabilitation periods for both are over i.e. the longest one applies to both. To clarify some cases and exceptions:
* If the first conviction has an end date and the second conviction is “never spent”, then the first conviction changes to “never spent”
* If the first conviction is “never spent” and the second has an end date, then neither changes
The following scenarios are covered with tests and pass our current algorithm implemented in `MultipleOffensesCalculator`:
---
---

Add multiple convictions test scenarios and tweak the calculator

---

app/models/disclosure_check.rb
app/services/base_multiples_calculator.rb
app/services/calculators/multiples/multiple_offenses_calculator.rb
spec/models/disclosure_check_spec.rb
spec/services/calculators/multiples/multiple_offenses_calculator_spec.rb
spec/services/calculators/multiples/same_proceedings_spec.rb
spec/services/calculators/multiples/separate_proceedings_spec.rb
spec/services/calculators/multiples/written_scenarios_spec.rb

The solution proposed here is to have two different methods, the existing #spent_date
which is used to iterate through all sentences.
And the new method #spent_date_without_relevant_orders,
which means it will ignore any relevant order sentence and
output the spent_date of a non relevant order.
It's possible that there's only a relevant order left, so
in this case the #spent_date_without_relevant_orders will return nil.
Hence having to check for a nil spent_date in the algorithm of MultipleOffensesCalculator.
All doubles have been adapted to represent their existing scenarios.
More examples should be added to represent relevant orders.
Scenarios have been written based on examples supplied in:
- Nacro Guidance
- https://www.gov.uk/guidance/rehabilitation-periods
- …

Ignore relevant orders on overlapping convictions 

---

app/services/calculators/multiples/multiple_offenses_calculator.rb
spec/services/calculators/multiples/multiple_offenses_calculator_spec.rb

We almost got it correct before.
To solve the issue of the scenario represented in the graph I had to compare the range of dates without the relevant order.
But first one needs to confirm if a conviction only holds a relevant order, if so, skip the range comparison.
If there's a date that does not belong to a relevant order, then we compare the overlapping, but never with relevant order dates.
My previous mistake was to only consider 1 proceeding, this now considers both proceedings
Story: https://trello.com/c/XJEnGNj6/109-ignore-relevant-order-sentences-in-other-separate-overlapping-convictions

Fixes overlapping convictions spent_dates

---

app/forms/value_object_methods.rb
app/views/steps/check/results/shared/_summary.en.html.erb
spec/forms/base_form_spec.rb

Ticket: https://trello.com/c/L2pqJMHo
First part of the work, to add an additional line of copy when we detect there is at least one approximate date in the check.
The other line of copy, shown always, has been tweaked according to content designer.
In a follow-up PR the copy will be implemented in the hint texts.

Add approximate date copy to results page

---

app/helpers/custom_form_helpers.rb
app/views/steps/caution/conditional_end_date/edit.html.erb
app/views/steps/conviction/compensation_payment_date/edit.html.erb
app/views/steps/conviction/conviction_date/edit.html.erb
app/views/steps/conviction/known_date/edit.html.erb
config/locales/en/caution.yml
config/locales/en/conviction.yml
config/locales/en/helpers.yml
features/fixtures/files/steps_conviction_known_date.html
features/fixtures/files/steps_conviction_known_date_with_errors.html
spec/helpers/custom_form_helpers_spec.rb

Ticket: https://trello.com/c/L2pqJMHo
Follow-up to PR #449.
We want to introduce some extra copy in all the dates hint text. However in doing this I realised we had many different hint texts depending if it was a caution/conviction and the type of the offence.
In order to make this more easy to maintain so we only have 1 hint text for all dates and it appears in the same place always, I've moved out from the hint text and into the `lead` paragraph some of the copy previously had in the hint text itself.
**Example 1**
---
**Example 2**

Amend hint text to clarify approximate dates

---

app/controllers/concerns/error_handling.rb
app/controllers/errors_controller.rb
app/controllers/results_controller.rb
app/errors/errors.rb
app/views/errors/results_not_found.html.erb
app/views/layouts/_developer_tools.html.erb
app/views/layouts/application.html.erb
app/views/layouts/govuk_template.html.erb
config/locales/en/errors.yml
config/routes.rb
spec/controllers/application_controller_spec.rb
spec/controllers/results_controller_spec.rb

This, for now, it is only for development/test purposes so it is hidden behind the "developer tools" footer menu.
Maybe in the future this is a feature we can expand and offer to end users so they can also share their results with other people.
The mechanism is simple. We use the ID of the `disclosure_report` to get the checks inside, and we pick one and assign their ID to the session, redirecting back to the results page to render the results by running the calculations again from the database.
As there is no personal identification at any point in the service, even if the link is shared publicly with unknown people, there is no risk at all, but just in case I'm using UUIDs so it is impossible to do enumeration attacks, for example.
Also once a …

Mechanism to share/return to the results page

---

app/value_objects/caution_type.rb
app/views/steps/check/results/shared/_meaning_cautions.en.html.erb
app/views/steps/check/results/show.en.html+caution_not_spent.erb
app/views/steps/check/results/show.en.html+caution_spent.erb
app/views/steps/check/results/show.en.html+caution_spent_simple.erb
spec/value_objects/caution_type_spec.rb

Ticket: https://trello.com/c/eRalDg7Z
Legislation changes were made that relate to Disclosure Checker on 28 November 2020. These were brought to the team's attention on 11 January.
Youth cautions, reprimands and warnings will no longer be automatically disclosed to employers on a Standard or Enhanced Disclosure and Barring Service (DBS) certificate.
Copy changes in the results page when we detect it is a youth caution. No changes for adult cautions (or convictions).

Copy changes for youth cautions in results page

---

Gemfile
Gemfile.lock
package.json
yarn.lock

Ticket: https://trello.com/c/cPMnLjfr
Bump `govuk-frontend` to latest version `3.11.0`.
It includes bug fixes. No breaking changes.

Bump design system version

---

app/services/calculators/multiples/proceedings.rb
spec/services/calculators/multiples/proceedings_spec.rb

Ticket: https://trello.com/c/HML7Aa42
As part of a recent refactor we probably missed the fact a check could be left incomplete (despite the "report" being completed).
Ensuring we work always with the collection of completed `disclosure_check` inside a Proceeding.

Ensure we work with completed checks

---

config/initializers/raven.rb

As part of ticket https://trello.com/c/HML7Aa42 we found out that Sentry by default was ignoring (not submitting) any `ActionView::MissingTemplate` errors so it was more difficult to find out where our code was failing.
Remove from the list of excluded exceptions `ActionView::MissingTemplate` so we can get these, including their backtrace.

Submit to sentry missing template exceptions

---

app/decorators/conviction_decorator.rb
app/services/calculators/motoring/adult/penalty_notice.rb
app/services/calculators/motoring/youth/penalty_notice.rb
app/services/conviction_decision_tree.rb
app/value_objects/conviction_type.rb
app/views/steps/check/results/show.en.html+conviction_no_record.erb
config/locales/en/helpers.yml
config/locales/en/results.yml
features/adults/conviction_motoring.feature
features/youth/conviction_motoring.feature
spec/decorators/conviction_decorator_spec.rb
spec/services/calculators/motoring/adult/penalty_notice_spec.rb
spec/services/calculators/motoring/youth/penalty_notice_spec.rb
spec/services/conviction_decision_tree_spec.rb
spec/services/conviction_length_choices_spec.rb
spec/value_objects/conviction_type_spec.rb

This reverts commit ef87968bdfc518fd624b96e3a3de1748dad18d3c, reversing
changes made to bfa55a8d517e23a3ce8907053f1d0b000cfcaa7a.
Ticket: https://trello.com/c/Vcpqhlqr
As per policy and legal decision, instead of removing completely from
the service FPNs, we are going to maintain them but only when they are
given an endorsement and thus they become a conviction.
In order to do this as clean as possible, first I'm reverting the PR
where the FPNs were removed, fixing any conflicts, so it works as it
was before for `singles`.
It will not work for `multiples` as the work/refactors we did in the
multiples calculator was under the assumption we didn't have FPNs.
In a follow-up PR I will adapt the code so we only leave in the service
FPNs with endorsement, and this will work with multiples too.

Revert removal of FPNs

---

app/views/steps/check/results/shared/_meaning.en.html.erb
app/views/steps/check/results/shared/_meaning_cautions.en.html.erb

Ticket: https://trello.com/c/18AS69LI
Feedback from GDS:
Currently the first 2 headings appear to be h3s:
‘If a basic criminal record check is requested’
‘If a standard or enhanced criminal record check is requested’
These then skip to an h2:
‘How this result has been worked out’
Our internal accessibility guidance states:
'Each page should get one H1 (the title), followed by H2s and H3s. Don’t skip from an h1 to an h3. Nest headings appropriately so that screen reader users, who can navigate using a list of headings, don’t think they’ve missed one which doesn’t exist.'

Avoid jumping from h1 to h3 in results page

---

app/controllers/home_controller.rb
app/services/external_url.rb
app/views/layouts/application.html.erb
app/views/steps/check/kind/edit.html.erb
app/views/steps/check/results/shared/_disclaimer.en.html.erb
features/adults/caution.feature
features/step_definitions/common.rb
features/youth/caution.feature
spec/controllers/home_controller_spec.rb
spec/services/external_url_spec.rb

This is a requirement to be able to send users back to the
GOV.UK page that will be live tomorrow (25th February 2021, at 1pm).
The intention is to make the user feel it never left to a different platform.
Technically I decided to use a new class, to identify external URLs given that
we may have other external urls around, it would become easier to find and change them
in the future.
Story: https://trello.com/c/HPTKJ7Dp

Change back link to GOV.UK page

---

app/forms/steps/conviction/conviction_subtype_form.rb
app/services/conviction_decision_tree.rb
app/views/steps/conviction/conviction_subtype/edit.html.erb
config/locales/en/helpers.yml
config/locales/en/results.yml
features/adults/conviction_motoring.feature
features/youth/conviction_motoring.feature
spec/forms/steps/conviction/conviction_subtype_form_spec.rb
spec/services/conviction_decision_tree_spec.rb

Story: https://trello.com/c/jdhA6rjb/64-dc-endorsed-fpns-journey
We are not removing the page that questions users about endorsement, we are just removing non-endorsed FPN from the journey.

Update journey to only have endorsed FPN

---

app/models/disclosure_check.rb
app/services/calculators/multiples/proceedings.rb
app/value_objects/conviction_type.rb
spec/models/disclosure_check_spec.rb
spec/services/calculators/multiples/given_scenarios_spec.rb
spec/services/calculators/multiples/proceedings_spec.rb
spec/value_objects/conviction_type_spec.rb

We have learned that not all relevant orders behave the same, meaning that some relevant orders do not drag through and others do.
The meaning of drag through is when 2 separate convictions share the same timeline. A relevant order that doesn't drag through ignores the overlap and ends when the conviction is spent. A relevant order that does drag through won't ignore the overlap and may be extended to the spent date of another conviction.
It's important to identify the relevant order, because relevant orders have an [additional length option](https://trello.com/c/MrEm9UKp).
The `drag_through` flag is to be used specifically for calculation purposes.
Story: https://trello.com/c/R9VWuOAu

Introduce drag through to relevant orders

---

Dockerfile
Gemfile
Gemfile.lock
README.md

Following long discussions we have an intermediate solution to upgrade 
mimemagic.
This also updates Docker to have the package.
It requires each individual to have a copy of `shared-mime-info`. 
More details here:
https://github.com/mimemagicrb/mimemagic/blob/master/README.md#dependencies

Update mimemagic to 0.3.9

---

app/views/steps/check/results/show.en.html+multiples.erb

This commit is about replacing the URL's regarding DBS, in the results page to a different page in GOV.UK
This PR is to be merged into #473 
Story: https://trello.com/c/9ouucUgh
Main Story: https://trello.com/c/IimlbdWM

Update DBS url's to a different GOV.UK page

---

app/helpers/analytics_helper.rb
app/presenters/check_answers_presenter.rb
app/views/steps/check/check_your_answers/show.html.erb
app/views/steps/check/results/show.en.html+multiples.erb
spec/helpers/analytics_helper_spec.rb
spec/presenters/check_answers_presenter_spec.rb

Ticket: https://trello.com/c/KF3PYWfT
Up until now we only had "single checks", as 1 check equals to just 1 caution or 1 conviction transaction on GA.
However going forward with multiples this needs to change, as 1 check (as in all the way to the results page) can equal to X number of convictions or cautions (added previously to a "basket").
As a first step so our current analytics don't start to get too skewed after the release of multiples we did in PR #473, we are adding a new transaction to the "CYA - Check your answer page" that triggers each time a new caution or conviction is added.
In addition, we modify the results page transaction so it contains information about how many proceedings it had and identify it by their report ID.
This is a first step and will be improved as we …

Update GA transactions to cope with multiples

---

app/views/steps/conviction/conviction_length/edit.html.erb
config/locales/en/conviction.yml
features/adults/conviction_custodial_sentence.feature
features/youth/conviction_custodial_sentence.feature

Ticket: https://trello.com/c/nJnRENsS
Slack thread: https://mojdt.slack.com/archives/CKZT0MY1G/p1617784023002500
Add an explanatory copy, hidden behind a revealing link, for how to enter the sentence length depending if there are consecutive or concurrent sentences.
Cleaned up some unused code and locales from a previous version of the page.

Add explanatory copy for consecutive/concurrent sentences

---

app/value_objects/conviction_type.rb
spec/value_objects/conviction_type_spec.rb

Just some small cleanup of a functionality no longer in use (DISABLED_PARENT_TYPES) as well as code reorganisation.
Also removal of the hardcoded `drag_through: false` because the default is already false so no need to specify it, so it is easier to find the ones that are `drag_through: true` as these are just a handful.
Functionality is the same, this is only shuffling around some code.

Small cleanup and code reorganisation

---

Gemfile
Gemfile.lock
spec/helpers/custom_form_helpers_spec.rb

Updates the `govuk_design_system_formbuilder` gem to the latest version as the one we were using was a bit outdated.
There are several changes but nothing breaking. Our tests and cukes continue to pass and I did some manual testing as well with no obvious regressions.
Also starting with v2.2.0 the gem dropped support for Rails 5.2.4 so good thing we've upgraded to Rails 6.2 already.
Note: I had to lock `cucumber` to < 6.0.0 otherwise we would start getting an error, I suppose this is because some of the other gems are not yet updated to support cucumber > 6.0
We can test further on staging before releasing to production.

Bump govuk_design_system_formbuilder gem

---

app/helpers/analytics_helper.rb
app/models/disclosure_report.rb
db/migrate/20210419110220_add_completed_at_to_disclosure_reports.rb
db/schema.rb
spec/helpers/analytics_helper_spec.rb
spec/models/disclosure_report_spec.rb

This is an improvement over a piece of work we did some time ago.
In essence, so we can use the "replay" functionality where we can see the results page at a later moment for a completed check, we need to avoid triggering some of the transactions and analytics otherwise it gets super skewed.
In order to do that, we add an extra attribute to the `disclosure_report` records, `completed_at` which is filled when the report is completed and then we can use this date later on to make decisions.
This will make it possible to replay old checks without tracking anything to GA.

Do not track analytics for completed reports again

---

app/helpers/analytics_helper.rb
app/presenters/check_answers_presenter.rb
app/services/calculators/multiples/proceedings.rb
app/views/steps/check/results/show.en.html+multiples.erb
spec/helpers/analytics_helper_spec.rb
spec/presenters/check_answers_presenter_spec.rb
spec/services/calculators/multiples/proceedings_spec.rb

We were reporting only cautions or convictions, but not the sentences/orders inside a conviction, which means a conviction with 3 sentences was reported just as 1 proceedings to google analytics, and in reality we want to know how many "multiples" checks are done and having more than 1 sentence qualify as "multiples".

Fix under reporting of proceedings in GA

---

app/services/calculators/multiples/multiple_offenses_calculator.rb
app/value_objects/conviction_type.rb
spec/factories/disclosure_check.rb
spec/services/calculators/multiples/given_scenarios_spec.rb
spec/value_objects/conviction_type_spec.rb

This PR does two things:
1. Addresses the observation done by Legal that a Community Order shouldn't be a relevant order
> Youth rehab orders and Community orders are not relevant orders so are subject to the drag on effect. 
2. Fixes the scenario given by Legal by using the modified date (spent_date) as the comparison point between dates when this variable is modified from the initial assigned value.
> YRO is shown as spent on until 1 July 2016 but it should be showing as spent on 29 June 2021 along with the community order and custodial sentence.
This PR does not address the following quote:
> Also, it is not clear to me why the Referral order is prompting me to include the date that person attended first panel meeting. 
> My understanding is that referral orders like all other offences …

Fix legal scenario 9

---

config/locales/en/helpers.yml
config/locales/en/results.yml
features/adults/conviction_community_prevention_reparation.feature

Ticket: https://trello.com/c/7SK4PLNz
The work in the above ticket will be split into 2 parts. This PR is the first part.
Renaming of the `Community, prevention or reparation order` conviction group to `Community, reparation or other order with requirements`.

Rename adults community orders conviction group

---

app/value_objects/conviction_type.rb
config/locales/en/helpers.yml
config/locales/en/results.yml
docs/relevant_orders.md
features/adults/conviction_community_prevention_reparation.feature
spec/i18n_spec.rb
spec/services/conviction_length_choices_spec.rb
spec/value_objects/conviction_type_spec.rb

Ticket: https://trello.com/c/7SK4PLNz
This is the 2nd part of the work requested in the above ticket.
A new catch-all radio option in the "Community, prevention or reparation order" (note this bucket will be renamed once the PR #485 is merged) has been added, named "Any other order with a requirement".
At the moment this is a relevant order, with no drag through, and the calculation rules are the same as in the community order conviction.
However we need confirmation if these rules are correct before merging. Other than that the rest of the work is done.
---

Add new catch-all requirement order option

---

app/assets/stylesheets/local/custom.scss
app/presenters/basket_presenter.rb
app/presenters/check_group_presenter.rb
app/views/steps/check/check_your_answers/shared/_check.html.erb
app/views/steps/check/check_your_answers/show.en.html.erb
app/views/steps/check/results/shared/_check.html.erb
config/locales/en/results.yml
features/step_definitions/common.rb
spec/presenters/check_group_presenter_spec.rb

To make it more closer to the prototype, changed the headings from:
```
1. Conviction
2. Caution
...
```
To:
```
Conviction 1
Caution 1
...
```
Few copy changes. Still all these is a bit WIP and pending final design.

Design tweaks to basket headings

---

app/assets/stylesheets/local/custom.scss
app/views/steps/check/check_your_answers/shared/_check.html.erb
app/views/steps/check/check_your_answers/show.en.html.erb
app/views/steps/check/results/shared/_check.html.erb

Just adding the nice boxes around each of the proceedings (cautions or convictions) as I think this really makes a difference to clarify each of them.
Although the results page needs to change dramatically, I've added the box there too for consistency as it looks nicer.
This is following some of the latest changes to the prototype, so still WIP but starting to take form.
---

More design tweaks to CYA/results

---

app/services/calculators/motoring/adult/penalty_notice.rb
app/services/calculators/motoring/youth/penalty_notice.rb
config/locales/en/results.yml
spec/services/calculators/motoring/adult/penalty_notice_spec.rb
spec/services/calculators/motoring/youth/penalty_notice_spec.rb

Back in PR #466 we have agreed to only have endorsed FPN's in the 
service - this is due to non endorsed FPN not being considered a 
conviction. 
Now that we have the possibility to calculate multiple convictions, we 
no longer support non endorsed FPN's as they are not a conviction.
This is more of a follow up cleanup on #466

Remove reference to non endorsed FPN

---

app/helpers/application_helper.rb
app/views/errors/report_completed.html.erb
app/views/steps/check/results/shared/_feedback.en.html.erb
app/views/steps/check/results/show.en.html.erb
app/views/steps/shared/_kickout_buttons.html.erb
spec/helpers/application_helper_spec.rb

A very minor fix.
There were some edge cases where the links to start a new check would still show the message "you have a check in progress" which is not what we wanted.
This is because they were missing the "magic" parameter that indicates to not show that message and instead reset/start a new session.
Similarly, in the completed report error page, do not link to the results page if there are no completed checks as that makes no sense.
Renamed the helper method to make more clear what it does.

Ensure we start a new session in some links

---

app/controllers/concerns/error_handling.rb
app/controllers/errors_controller.rb
app/controllers/steps/check/results_controller.rb
app/errors/errors.rb
app/views/errors/report_not_completed.html.erb
app/views/steps/shared/_kickout_buttons.html.erb
config/locales/en/errors.yml
config/locales/en/helpers.yml
config/routes.rb
spec/controllers/application_controller_spec.rb
spec/controllers/steps/check/results_controller_spec.rb

There was a missing validation in the results page.
If a user, for whatever reason bookmarks the result page, next time they come back to the service they might not complete any check or leave midway a check and then jump straight to the results page.
It would show an empty page (as in no items: cautions or convictions in the basket) which would be weird.
With this validation we ensure we show the results page only if we have a "completed" report. If not we show an error message and let them either get back to the CYA page if they had something in the basket, or to start a new check.

Check we have a completed report before results page

---

app/assets/stylesheets/local/custom.scss
app/presenters/check_group_presenter.rb
app/presenters/spent_date_panel.rb
app/presenters/spent_tag.rb
app/views/steps/check/results/shared/_check.html.erb
app/views/steps/check/results/shared/_spent_date_panel.html.erb
app/views/steps/check/results/show.en.html.erb
config/locales/en/results.yml
spec/presenters/check_group_presenter_spec.rb
spec/presenters/spent_date_panel_spec.rb
spec/presenters/spent_tag_spec.rb

Story: https://trello.com/c/QmITv0Rd
I've reconsiders the addition of the conviction date within the paragraph and found that it adds too much code for a minimal gain, because cautions do not have "conviction_date" but a "known_date". We already have that information on the table underneath so I think it's not worth the extra code for repeated information.
I'm also considering changing the name of "SpentDatePanel" but right now I don't have a better naming for it.

Results page new design

---

app/presenters/check_group_presenter.rb
app/presenters/spent_date_panel.rb
app/presenters/spent_tag.rb
app/value_objects/results_variant.rb
spec/factories/disclosure_check.rb
spec/presenters/check_group_presenter_spec.rb
spec/presenters/spent_date_panel_spec.rb
spec/presenters/spent_tag_spec.rb
spec/services/check_result_spec.rb
spec/value_objects/results_variant_spec.rb

Ticket: https://trello.com/c/urHOEzjZ
Note: There will be a follow-up PR, didn't want this to grow too much with the introduction of the DBS code.
We have exposed an `#spent?` method in the `ResultsVariant` so we can simplify some code.
Also, instead of repeating the `variant` or `tense` code snippet to know if a given date is in the past or not, we just pass to the `SpentTag` and to the (future) `DbsVisibility` classes the variant, as these don't need to know the specific `spent_date` or do any calculation with it.

Refactor and DRY some code in preparation for DBS

---

app/presenters/check_group_presenter.rb
app/presenters/dbs_visibility.rb
app/views/steps/check/results/shared/_check.html.erb
app/views/steps/check/results/shared/_dbs_visibility.html.erb
app/views/steps/check/results/show.en.html.erb
config/locales/en/results.yml
spec/presenters/check_group_presenter_spec.rb
spec/presenters/dbs_visibility_spec.rb

Ticket: https://trello.com/c/urHOEzjZ
Follow-up to PR #504.
Implement the DBS informational inset block on the results page, but for now it will only show on local/staging envs until we have the green light.
Also, the rules for enhanced checks are not completely clear, so my best attempt was when in doubt, to say `may appear`.
Basic checks are correct to the best of my knowledge. Also enhanced youth cautions.

Show DBS information on results page (feature-flagged)

---

app/presenters/dbs_visibility.rb
spec/presenters/dbs_visibility_spec.rb

Follow up to PR #505.
Little misunderstanding with the rules.
Youth cautions that are not spent will appear on both, standard and enhanced checks (it’s only those that are spent that will not).

Fix the DBS youth caution rules

---

app/forms/value_object_methods.rb
app/presenters/results_presenter.rb
app/views/steps/check/results/show.en.html.erb
spec/forms/base_form_spec.rb
spec/presenters/results_presenter_spec.rb

The following text had been removed in PR #492 as part of
moving towards the service being capable of dealing with multiple cautions and convictions.
The added code now checks for any disclosure check that has:
- approximate dates selected
- bail time
- motoring conviction
Story: https://trello.com/c/ONHg9IzX/278-dc-results-page-missing-copy
----

Re-introduce text in the results page

---

app/presenters/results_presenter.rb
app/views/steps/check/results/show.en.html.erb
spec/presenters/results_presenter_spec.rb

Update from Leigh:
1. The line for approximate dates should appear under the opening line beginning: “Your results are calculated using…”
2. The line for approximate dates should read: As you entered an approximate date, your results will be approximate.
3. This paragraph is conditional to be shown only when it’s a conviction: [CONDITIONAL FOR CONVICTIONS] Your results are correct if you served your sentence in full as the court ordered you to. The conviction might not be spent if you did not stick to the terms of your sentence.
Story: https://trello.com/c/ONHg9IzX/278-dc-results-page-missing-copy

Copy amendments and introduction of convictions logic

---

app/models/disclosure_report.rb
app/presenters/dbs_visibility.rb
app/presenters/results_presenter.rb
spec/models/disclosure_report_spec.rb
spec/presenters/check_group_presenter_spec.rb
spec/presenters/dbs_visibility_spec.rb
spec/presenters/results_presenter_spec.rb

Ticket: https://trello.com/c/urHOEzjZ
Add the rule for custodial convictions (these are always shown on the enhanced DBS check).
Simplified/refactored some more code to make use of a more declarative syntax, easier to read, introduce in previous PRs.

Add DBS rule for custodial convictions

---

app/assets/stylesheets/application.scss
package.json
yarn.lock

Ticket: https://trello.com/c/gr75HUCY
Version 3.12.0 of the GOV.UK Frontend was released recently.
https://github.com/alphagov/govuk-frontend/releases/tag/v3.12.0
Main change is links are now easier to read and have a clearer hover state. This is opt-in (in future releases will be enabled by default).

Bump GOV.UK Frontend

---

app/views/steps/check/check_your_answers/show.en.html.erb
app/views/steps/check/kind/edit.html.erb
config/locales/en/check.yml
features/fixtures/files/steps_check_kind.html
features/fixtures/files/steps_check_kind_with_errors.html

Ticket: https://trello.com/c/55y9BdCo
A couple of minor copy addition/tweaks to better signify the fact users can check more than 1 caution or conviction.
Copy as per content designer.
Ideally to be released ASAP before any further undergoing CYA work.

Minor copy improvements for multiple checks

---

app/assets/stylesheets/local/custom.scss
app/controllers/application_controller.rb
app/controllers/steps/checks_controller.rb
app/forms/steps/check/remove_check_form.rb
app/services/base_decision_tree.rb
app/services/check_decision_tree.rb
app/views/steps/check/check_your_answers/shared/_check_row.html.erb
app/views/steps/checks/edit.html.erb
config/locales/en/check.yml
config/locales/en/errors.yml
config/locales/en/helpers.yml
config/routes.rb
features/multiples/remove_caution_or_convictions.feature
features/step_definitions/common.rb
spec/forms/steps/check/remove_check_form_spec.rb
spec/services/check_decision_tree_spec.rb

This adds functionality for the user to be able to remove sentences in the Check Your Answers page.
When a sentence is deleted, it's crucial to know wether there was other sentences
in the same report. Specially when the deleted sentence was the last one to be created,
since, until now, the session relied purely on the last `disclosure_check`, if that is deleted
we must find the Report id in order to know if there was other sentences present in order to send
the user to CYA or to the first page of the service (and restart their journey).
Story: https://trello.com/c/D6Goc7YV

Functionality to remove sentences in CYA

---

app/controllers/application_controller.rb
app/controllers/step_controller.rb
app/presenters/caution_result_presenter.rb
app/presenters/conviction_result_presenter.rb
app/presenters/question_answer_row.rb
app/presenters/results_item_presenter.rb
app/views/steps/check/check_your_answers/shared/_change_link.html.erb
app/views/steps/check/check_your_answers/shared/_row.html.erb
config/locales/en/results.yml
spec/controllers/step_controller_spec.rb
spec/presenters/caution_result_presenter_spec.rb
spec/presenters/question_answer_row_spec.rb
spec/support/step_controller_shared_examples.rb

Ticket: https://trello.com/c/lrx02rsR
First attempt and kind of Proof of Concept of the ability to `change` answers to previous questions in cautions or convictions.
Right now this PR only implements Cautions as these are much simpler (only 2 questions can be edited).
Some questions will not be editable because in doing so, the caution (or conviction) change fundamentally, for example the under age question. If a user answered over 18 and then they change it to under 18, the whole caution or conviction will become wrong as the "type" is linked to the age (for example, youth cautions vs. adult cautions).
The implementation is simple: all of the "change" links will have as a query param the ID of the `disclosure_check` record being edited (because when in the basket there are more than 1, …

Check your answers `change` functionality

---

app/forms/steps/caution/known_date_form.rb
config/locales/en/errors.yml
spec/forms/steps/caution/known_date_form_spec.rb

For conditional cautions, the "known_date" (caution date) must be before the conditions end date.
This so far has been fine but with the `change` functionality in the CYA, the user might edit a conditional caution date and introduce a wrong date without noticing.
We might need to revisit other places where this can happen in convictions for the same reason, but for now I'm focusing on cautions as per PR #519.

Add validation to caution date

---

app/helpers/custom_form_helpers.rb
app/presenters/caution_result_presenter.rb
spec/helpers/custom_form_helpers_spec.rb
spec/presenters/caution_result_presenter_spec.rb

Some attributes can be edited without having to go through the following steps. This way after changing something, we can take the user back to the CYA page quickly.
This is done by marking these attributes with the `?next_step=cya` query param.
After editing something and clicking the `continue` button, if the `next_step` was set, the decision tree logic will be skipped and jump straight to the path specified in the next step (it is a hidden tag in the form).
If the attribute is the last one in a journey, there is no need to add this query param as it is redundant because the next step is always the CYA in these cases.
For example for cautions, `conditional_end_date` is the last attribute in the journey and the next step is always the CYA anyways.

Some attributes can jump back to CYA

---

app/controllers/application_controller.rb
spec/controllers/home_controller_spec.rb

Introduced in PR #518, I forgot to  delete the `disclosure_report` session so that the user can start a new check. Without  deleting the session the user would be prevented from starting a new check without deleting the service session cookies manually.

Delete disclosure report session

---

app/presenters/conviction_result_presenter.rb
config/locales/en/helpers.yml
config/locales/en/results.yml
spec/presenters/conviction_result_presenter_spec.rb

Ticket: https://trello.com/c/lrx02rsR
Follow-up to PR #519.
This PR adds the "change" functionality to the convictions, similar to cautions.
There is one without the change link for now (`conviction_date`) because it is the top level conviction date, so changing it would affect all the disposals/orders that are part of the conviction (we would have to iterate through all of them changing the attribute in their corresponding DB records).
Will investigate some alternatives in another PR if possible. But it is best probably to not allow this to be changed.

Change conviction attributes in CYA

---

app/assets/stylesheets/local/custom.scss

Fix color contrast in CYA remove link

---

app/controllers/application_controller.rb
app/controllers/steps/checks_controller.rb
spec/controllers/home_controller_spec.rb

Upon removing a disclosure check record, if there's other records within the same report, we swap them so that the user continues to iterate through other records.
This deprecates the second session that was introduced in 84ce9d77038c860dc0a6650e69b9db5eea7ed4f5 and uses the swap functionality introduced in 252db539d8261e8f3cab9d9bc7f822aff3df3574.

When removing a record, change the session if possible.

---

app/assets/stylesheets/local/custom.scss
app/views/steps/check/check_your_answers/shared/_check_row.html.erb
config/locales/en/results.yml

Convert the proceeding heading (caution / conviction name) to a definition list so the remove link move automatically down below the name when on small screens.
Also simplify a bit the styles of the red remove link.
Desktop:
Mobile:

A few more markups improvements

---

app/decorators/conviction_decorator.rb
app/forms/steps/conviction/conviction_subtype_form.rb
app/services/calculators/disqualification_calculator.rb
app/services/calculators/motoring/adult/penalty_notice.rb
app/services/calculators/motoring/adult/penalty_points.rb
app/services/calculators/motoring/youth/penalty_notice.rb
app/services/calculators/motoring/youth/penalty_points.rb
app/services/conviction_decision_tree.rb
features/adults/conviction_motoring.feature
features/youth/conviction_motoring.feature
spec/decorators/conviction_decorator_spec.rb
spec/forms/steps/conviction/conviction_subtype_form_spec.rb
spec/services/calculators/disqualification_calculator_spec.rb
spec/services/conviction_decision_tree_spec.rb

Ticket: https://trello.com/c/1RtNkemH
During DC demos, feedback was given that it is unnecessary to ask users who enter that they have a driving disqualification whether they have an endorsement, as all disqualifications are endorsed.
Legal confirmed that we should remove the question for the service.
Refactor the code around the disqualification logic because we now only have 1 motoring conviction where we need to still ask this question (fines). The others can be simplified.

Remove endorsement question for motoring disqualifications

---

app/views/steps/check/check_your_answers/shared/_change_link.html.erb
app/views/steps/check/check_your_answers/shared/_check_row.html.erb
app/views/steps/check/check_your_answers/shared/_row.html.erb

Ticket: https://trello.com/c/lrx02rsR
This was hidden behind a feature flag and only visible on staging but now we have the green light to release to production.
Also added GA tracking (including the remove links for parity).

Enable CYA change links

---

app/views/steps/check/results/show.en.html.erb

As instructed by content designers.
There was a duplicated sentence and a wrong link.

Minor copy amendments to results page

---

features/multiples/change_answers.feature

Ticket: https://trello.com/c/ABI0WCOR
Add a simple cucumber scenario to cover the change links functionality on the check your answers page, similar to what we did with the remove functionality.
Note how we can nicely write these by using, for example, `I click the "Change start date" link` despite on the page only the word `Change` is visible, the `start date` part is visually hidden, but still it can be used to target elements with cucumber.

Add cucumber scenario for CYA change links

---

config/locales/en/conviction.yml
config/locales/en/results.yml
features/multiples/change_answers.feature

Ticket: https://trello.com/c/DTKQQcwt
This was raised by policy and suggested we could use `Length of sentence` instead of previously `Length of conviction`.
This affects the Check your answers page and the Results page.

Copy change `Length of conviction` to `Length of sentence`

---

app/services/conviction_decision_tree.rb
features/adults/conviction_financial.feature
features/youth/conviction_financial.feature
spec/services/conviction_decision_tree_spec.rb

Ticket: https://trello.com/c/cETYcVq3
This is work in progress. We are awaiting for copy changes (maybe) to be
introduced in the journey.
For now I've just reorganised the journey to get rid of the kick out
page and the amount question, as it was only used to trigger the
kick out when the amount was over 100 but does not affect any of the
calculations.
Pending things: removal of form objects, controllers, views, locales,
etc. and even the unused DB fields. once we are clear on the copy
changes and where we have to apply them.

Remove compensation to a victim DBS receipt kick out

---

app/views/steps/check/results/shared/_feedback.en.html.erb

Ticket: https://trello.com/c/8oxpSW1n
Very minor tweak, as raised by a recent accessibility report, to change the survey heading from an h2 to an h3 so it is consistent with the rest of headings.

Change heading from h2 to h3 in results page

---

app/forms/steps/conviction/conviction_length_form.rb
app/services/base_calculator.rb
app/value_objects/conviction_length_type.rb
config/locales/en/errors.yml
config/locales/en/helpers.yml
config/locales/en/results.yml
features/adults/conviction_community_prevention_reparation.feature
features/adults/conviction_custodial_sentence.feature
features/adults/conviction_discharge.feature
features/adults/conviction_military.feature
features/adults/conviction_motoring.feature
features/multiples/change_answers.feature
features/youth/conviction_custodial_sentence.feature
features/youth/conviction_discharge.feature
features/youth/conviction_military.feature
features/youth/conviction_motoring.feature
features/youth/conviction_prevention_reparation.feature
features/youth/conviction_referral_supervision_yro.feature
spec/forms/steps/conviction/conviction_length_form_spec.rb
spec/forms/steps/conviction/conviction_length_type_form_spec.rb
spec/services/base_calculator_spec.rb
spec/services/conviction_length_choices_spec.rb
spec/value_objects/conviction_length_type_spec.rb

We have received feedback that sometimes courts give the sentence in days,
which means that users would have to convert those days into one of our options,
this is not ideal as it could prone users to introduce decimal numbers (which are not allowed).
So this commit allows users to introduce days, and internally we convert those days into months.
I've removed the conversion constants and replaced the calculations with ActiveSupport own methods.
The reason the specs have been changeds is that ActiveSupport calculates seconds per month,
so there's was a tiny discrepancy with the previous implementation, but nothing drastic (at least not in short periods of time)
```ruby
ActiveSupport::Duration::SECONDS_PER_MONTH
1.month.in_seconds
=> 2629746
```
Story: https://trello.com/c/DqoWLnHu

Introduce days to sentence length

---

app/controllers/concerns/completion_step.rb
app/services/external_url.rb
app/views/steps/check/kind/edit.html.erb
spec/controllers/reports_controller_spec.rb
spec/services/external_url_spec.rb

Ticket: https://trello.com/c/gtvCFFpA
There was a nasty edge case where the session could become invalid (as in, pointing to a non-existing DB record) if, in the CYA, a user pressed any of the buttons to add a new sentence or a new caution/conviction but didn't complete this new journey, leaving an incomplete check (record) in the DB.
When returning to the CYA and pressing the `continue to results` button, then there is code to purge any incomplete checks from DB, purging also the record currently in the session and thus failing to render the results page (with the generic error `session expired`).
Fixed this by making sure after the purge of any incomplete checks, we re-assign an existing check back to the session from those in the report (the last one, but could be any, doesn't matter). …

Improve handling of session on CYA page

---

app/views/steps/check/results/shared/_check.html.erb
features/adults/caution.feature
features/youth/caution.feature

Ticket: https://trello.com/c/urHOEzjZ
We've got confirmation the DBS banners are good to go. It was hidden behind a feature flag.

Show DBS info banners on production

---

app/controllers/home_controller.rb
app/controllers/warning_controller.rb
app/helpers/application_helper.rb
app/views/layouts/application.html.erb
app/views/warning/reset_session.html.erb
features/multiples/cautions_and_convictions.feature
spec/controllers/home_controller_spec.rb
spec/controllers/warning_controller_spec.rb
spec/helpers/application_helper_spec.rb

Ticket: https://trello.com/c/gtvCFFpA
Follow-up to PR #539 to fix/improve another issue, where the CYA didn't have the "check in progress" protection, so if a user had added let's say a few cautions/convictions in the basket and for some reason they click the header, it will just start a journey from the beginning, wiping from the session all previous entered cautions/convictions, which can be very frustrating.
This has been improved by not only checking for a "disclosure_check" record `in_progress` but also a disclosure_report, because when the user reach the CYA, the current disclosure_check is marked as completed and thus this is why the in progress warning wasn't showing.

Show check in progress warning when on CYA

---

.env.example
app/controllers/backoffice/reports_controller.rb
app/views/backoffice/reports/_report_row.html.erb
app/views/backoffice/reports/index.en.html.erb

Very simple, and using what we had already in place, report page in the back office, listing the last 50 completed reports, ordered by completion date, with some basic information and a link to show the results.
This is behind http auth credentials (same credentials as usual) and also is totally anonymous as we don't ask or collect any personal information.
It is just a starting point in case we want to extend/improve it. And is just a page we can remove if we don't use it or need it anymore.

Add a checks report to the back office

---

app/controllers/backoffice/reports_controller.rb
app/models/disclosure_report.rb
app/views/backoffice/reports/_report_row.html.erb
app/views/backoffice/reports/index.en.html.erb
spec/controllers/backoffice/reports_controller_spec.rb
spec/models/disclosure_report_spec.rb

Just a small improvement so it is now possible to sort the completed reports by its number of sentences
This way is easier to find at the top those that are more interesting because have many convictions/sentences.
Added a new `sentences` column to the report table, because 1 conviction, can have more than 1 sentence. It also counts as sentence the cautions, although this is probably not technically correct, but for the purpose of the report it makes more sense.

Ability to sort the report by number of sentences

---

app/decorators/conviction_decorator.rb
app/presenters/dbs_visibility.rb
app/value_objects/caution_type.rb
spec/decorators/conviction_decorator_spec.rb
spec/presenters/dbs_visibility_spec.rb
spec/value_objects/caution_type_spec.rb

Ticket: https://trello.com/c/lK5NwwEM
In addition to the rules we already have for the enhanced DBS checks, we are now introducing the recency ones too, as follows:
```
- Adult cautions given within 6 years of the check: will appear.
- Youth convictions imposed within 5.5 years of the check: will appear.
- Adult convictions imposed within 11 years of the check: will appear.
```
This only affects some **spent caution/convictions**.
We keep saying `maybe` if none of the rules are triggered, as a precaution.
**Note**: pending copy updates in the results page to indicate the results are valid as of the day of the check. Will be done in a separate PR when we have confirmation.

Implement DBS recency rules

---

app/views/steps/check/results/show.en.html.erb

This work is related to the DBS recency rules introduced.
As part of this our content designer has identified a few changes to be done and some other copy to be refined in the results page, particularly to mention the fact the `results are valid on the date of the check`.

Copy changes in results page

---

app/presenters/dbs_visibility.rb
features/adults/caution.feature
spec/presenters/dbs_visibility_spec.rb

Follow-up to PR #547.
We are still awaiting confirmation but it is quite possible spent adult cautions given more than 6 years ago will not show in the standard or enhanced DBS check.
If given within 6 years they will appear.
More context in the slack convo: https://mojdt.slack.com/archives/CKZT0MY1G/p1627375025048900
As a consequence of this I had to do some refactor of the code but now it should be even more easier to read and follow and also easier to make changes in the future if needed.

Tweak DBS recency rules for older adult cautions

---

app/assets/javascripts/application.js
app/assets/javascripts/modules/cookie-banner.js
app/views/layouts/_cookie_banner.html.erb
app/views/layouts/_cookie_banner_confirmation.html.erb
app/views/layouts/application.html.erb
app/views/layouts/govuk_template.html.erb
config/locales/en/layouts.yml

Ticket: https://trello.com/c/i5IitID9
Follow-up to PR #564.
Show the cookies permission banner on page load, and hook the accept/reject buttons to the controller.
Add a bit of javascript to allow to close the banner without reloading the page.
This follows the guidelines and design stated in the design system:
https://design-system.service.gov.uk/components/cookie-banner/
In the next PR we will implement the cookies preferences in the cookies page and add cucumber tests.

Implement cookies permission banner - Part 2

---

app/views/steps/check/results/shared/_dbs_visibility.html.erb

Ticket: https://trello.com/c/qRnvt0Oy
The results page might repeat a whole chunk of copy if there were more than 1 caution or conviction that `may appear` on enhanced DBS.
Using `flush` fixes the problem and will only show the content once, even if `content_for` was called more than once.

Avoid content repetition in results page

---

app/views/steps/check/results/show.en.html.erb

Ticket: https://trello.com/c/8NJm6gNh
On the back of the above ticket, it was decided a quick and immediate action we can take is to modify the DBS links to go to the paragraph "Using your results" as otherwise users, specially on mobile devices might miss it and contains important information about the DBS.
Previously links would jump to the underneath section, skipping the "Using your results" paragraph that may contain important information depending on the DBS results.

Modify link anchor in results page

---

app/helpers/application_helper.rb
app/presenters/results_presenter.rb

Ticket: https://trello.com/c/i6m6IrA2
This is part of the investigation to fix or mitigate some (very small in number) exceptions that are captured in Sentry.
These errors happen when a user (could be even a bot scanning the website) access a page after the session has ended and thus there was no protection against a potential `nil` object.
I might raise a separate PR for other kind of errors.

Protect against some uninitialized objects

---

app/controllers/step_controller.rb
app/controllers/steps/caution_step_controller.rb
app/controllers/steps/conviction_step_controller.rb
spec/factories/disclosure_check.rb
spec/support/step_controller_shared_examples.rb

An exception can occur when a user reaches an invalid step for the current check. e.g. they reach a conviction step when it should be checking a caution. They are also not able to resume the previous check because the navigation stack is invalid.
To recreate:
1. Select "Cautioned" as the check type
2. Change the URL to `/steps/conviction/conviction_subtype`
The additional validation added means that if this occurs, the user will be redirected to the reset_session page which will allow them to start a new check, or resume the previous one. The invalid step is removed from the navigation stack so that they can continue.

CDPT-393 Validate current disclosure check is valid for step

---

config/application.rb
config/environments/development.rb
config/environments/test.rb
config/initializers/sentry.rb

Don't send exceptions to sentry in test and local environments

Disable sentry running when not in production like environment

---

.github/workflows/test-build-deploy.yml

The ECR_URL secret value has been deprecated and will go away at some point. I've created the repository variable `ECR_URL` to replace it (https://github.com/ministryofjustice/disclosure-checker/settings/variables/actions).

Use short lived credentials for ECR

---

.github/workflows/deploy.yml
.github/workflows/test.yml

Uses `workflow_call` so deploy to Staging when PR is merged to main only occurs after tests have been run.

Deploy main after test run

---

.github/workflows/deploy.yml
.github/workflows/test.yml

The value of `github.workflow` was the same for both workflow when one is called via `workflow_call` so this caused a deadlock and stopped the deploy working.
Hardcoding the names to be different should fix this.

Fix workflow deadlock

---

.github/workflows/test.yml

Called workflow does not have access to secrets by default

Inherit secrets

---

app/services/calculators/sentence_calculator.rb

Sentence lengths over 6 months and below 7 months are not being caught correctly by the case statement.
NB: I have not added any tests for this fix as this code is changing anyway as part of the upcoming CDPT-954 changes.

CDPT-967 Fix calculation bug

---

app/value_objects/conviction_type.rb
spec/forms/steps/conviction/conviction_length_type_form_spec.rb
spec/value_objects/conviction_type_spec.rb

Makes Youth Community Order and Adult Community Orders relevant orders which "until further order" option to appear.

CDPT-948 Add "Until further order" options

---

app/models/disclosure_check.rb
app/services/calculators/multiples/proceedings.rb
app/value_objects/conviction_type.rb
spec/models/disclosure_check_spec.rb
spec/services/calculators/multiples/proceedings_spec.rb
spec/value_objects/conviction_type_spec.rb

Changes are based on legal advice from Government Legal Department
Also renames variable to `no_drag_through` as a true value means that drag through does not apply.

CDPT-1015 Add/Remove Drag Through

---

app/services/calculators/multiples/multiple_offenses_calculator.rb
app/value_objects/conviction_type.rb
spec/services/calculators/multiples/multiple_offenses_calculator_spec.rb
spec/spec_helper.rb
spec/value_objects/conviction_type_spec.rb

Convictions that were overlapped by earlier convictions were not having drag through correctly applied.

CDPT-1049 Fix drag through calculations

---

app/value_objects/conviction_type.rb
spec/value_objects/conviction_type_spec.rb

Changes to match civilian community orders:
- Adds "until further order" option
- rehabilitation period matches end date given by the order

CDPT-1115 Change military commmunity order rehabilitation periods

---

app/services/calculators/multiples/proceedings.rb
spec/services/calculators/multiples/proceedings_spec.rb

Handles comparison when NEVER_SPENT or INDEFINITE is present. 
`spent_date` and `spent_date_without_relevant_orders` methods now work the same way.

CDPT-1133 Fix multiple sentence bug

---

.env.example
.github/workflows/deploy.yml
config/kubernetes/production/config_map.yml
config/kubernetes/production/cronjob.yml
config/kubernetes/production/deployment.yml
config/kubernetes/production/ingress.yml
config/kubernetes/production/service.yml
config/kubernetes/qa/config_map.yml
config/kubernetes/qa/cronjob.yml
config/kubernetes/qa/deployment.yml
config/kubernetes/qa/ingress.yml
config/kubernetes/qa/service.yml
config/kubernetes/staging/config_map.yml
config/kubernetes/staging/cronjob.yml
config/kubernetes/staging/dashboard.yml
config/kubernetes/staging/deployment.yml
config/kubernetes/staging/ingress.yml
config/kubernetes/staging/service.yml

Kubernetes config has been in a separate repo - https://github.com/ministryofjustice/disclosure-checker-deploy
Move it to this repo, and add a deploy for step for the new QA environment.

Move deployment config to repo and add QA environment

---

.github/workflows/deploy.yml

Push to ECR with tagged image is failing because we haven't logged in first at this step.

Login to ECR before pushing

---

.github/workflows/deploy.yml
config/kubernetes/production/deployment.yml
config/kubernetes/qa/deployment.yml
config/kubernetes/staging/deployment.yml

Add permission, and pull image before re-tagging.
Also uses per environment variables that are now been set from cloud platform and updates replica numbers per environment.

Add permissions for each deploy step

---

config/kubernetes/production/ingress.yml

Enables [modsec](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/networking/modsecurity.html) in detection mode on production so we can be aware of any issues and evaluate if more protection is required.

CDPT-1952 Enable modsec detection mode on production

---

config/kubernetes/qa/ingress.yml
config/kubernetes/staging/ingress.yml

[Modsec](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/networking/modsecurity.html) will stop malicious traffic going to the service.

CDPT-1958 Enable modsec in non-prod namespaces

---

app/helpers/custom_form_helpers.rb
app/views/steps/caution/conditional_end_date/edit.html.erb
app/views/steps/conviction/compensation_payment_date/edit.html.erb
app/views/steps/conviction/conviction_date/edit.html.erb
app/views/steps/conviction/known_date/edit.html.erb
config/locales/en/helpers.yml
features/fixtures/files/steps_conviction_known_date.html
features/fixtures/files/steps_conviction_known_date_with_errors.html
spec/helpers/custom_form_helpers_spec.rb

The govuk_design_system_formbuilder gem allows for supplemental text to be added to a form element. An `aria-described-by` hint is added to the fieldset, but it is not in the same order that the text is displayed on the page which causes confusion when using a screen reader.
This change adds the supplemental text as part of the hint to avoid this confusion.

CDPT-2298 Change ordering of hint text for screen readers

---

app/services/calculators/sentence_calculator.rb
features/adults/conviction_custodial_sentence.feature
features/youth/conviction_custodial_sentence.feature
spec/presenters/check_answers_presenter_spec.rb
spec/presenters/results_presenter_spec.rb
spec/services/calculators/multiples/multiple_offenses_calculator_scenarios_spec.rb

**Description**
Prison sentence & Suspended Prison sentence rehabilitation date end is incorrect. 
For both these sentences an extra day needs to be added so for example instead of ending on 31st will end on the 1st.
**Jira ticket**
https://dsdmoj.atlassian.net/jira/software/c/projects/CDPT/boards/1152?selectedIssue=CDPT-2458

CDPT-2458 Fix prison and suspended sentence rehabilitation dates

---

Gemfile
Gemfile.lock
app/views/layouts/govuk_template.html.erb
features/support/env.rb

Added the capybara-lockstep gem to fix failing cucumber tests due to a chromedriver behavioural change.

Install capybara-lockstep gem

---

Gemfile
Gemfile.lock
app/views/layouts/govuk_template.html.erb
package.json
spec/features/feedback_link_spec.rb
yarn.lock

Update GOV header component with the new component. 
**Before**
**After**
> [!NOTE]  
> **govuk-components introduced a breaking change to update header and footer components in v5.11.0**
> https://github.com/x-govuk/govuk-components/releases/tag/v5.11.0

CDPT-2833: Update GOV.UK header
